### ISSUE TITLE
Testserver geeft foutmelding tijdens inloggen en is dus niet bereikbaar

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#10]
Als ik probeer in te loggen dan krijg ik bijgaande foutmelding:
![inlogfout_testserver](https://cloud.githubusercontent.com/assets/10232554/5615962/47d043c4-9500-11e4-8802-0c57500c0ca6.jpg)
Ik krijg de fout zowel op mijn desktop als op mijn laptop. Zowel via test.crs2.nl als via 148.251.183.26
Wat kan er aan de hand zijn?

**Comment by HermanAssink** [comment]
In de system log kan ik zien dat je wachtwoord is verlopen. Kun je dat wachtwoord zelf aanpassen?

**Comment by ejmeulenkamp** [comment]
Hallo Herman.

Om mijn wachtwoord te kunnen wijzigen moet ik volgens mij eerst inloggen, en dat lukt nu niet. 

Met vriendelijke groet, Evert Jan

**Comment by HermanAssink** [comment]
Raar, normaal krijg je een melding dat het wachtwoord is verlopen en moet je meteen een neiuwe aanmaken. Dat heb ik nu gedaan, zie email.

**Comment by ejmeulenkamp** [comment]
Gaat dit bij Linda en de testers ook gebeuren? Of kun je ergens instellen dat het wachtwoord niet verloopt?

**Comment by HermanAssink** [comment]
Met het IDgis account kreeg ik van te voren een melding dat het wachtwoord ging verlopen. Dat heb ik toen vernieuwd en verder geen probleem gehad. Instellen dat wachtwoorden niet verlopen vind ik een te groot risico omdat deze server toegankelijk is via het internet.
Om het probleem in de toekomst te voorkomen heb ik de oplossing uit dit artikel http://www.petenetlive.com/KB/Article/0000826.htm toegepast.
