### ISSUE TITLE
Kaartlagen zijn nog niet gevuld maar BRT Achtergrondkaart is super!!!

### ISSUE THREAD

**Issue by willempeters** [IDgis/CRS2#100]
De kaartlagen zijn nog niet gevuld in de Viewer. We hebben er alle vertrouwen in dat dat goed gaat komen. De BRT Achtergrondkaart is wel een hele mooie. We houden ons aanbevolen om er die standaard bijgeleverd te krijgen bij oplevering.

**Comment by willempeters** [comment]
In dit kader denken wij dat als we een contract in CRS-Contracten-Details openen de Viewer niet automatisch naar dat perceel of percelen gaan die aan het contract zijn gekoppeld. We komen er echter wel via Select huidige en Inzoomen. Het zou toch handig zijn als je in Lijst een op Toon selectie drukt dat je dan meteen in Details ook de ligging van het gekoppelde gaat zien.

**Comment by ejmeulenkamp** [comment]
Als je op Toon Selectie klikt, dan verschijnen volgens mij ook de percelen op de kaart.
@willempeters Kun je dit bevestigen?
