### ISSUE TITLE
We kunnen de Labels en dergelijke niet vinden in GitHub

### ISSUE THREAD

**Issue by willempeters** [IDgis/CRS2#102]
We hebben in al onze haast vanmorgen de Labels, Milestones ed vergeten in te vullen. Het zou een degelijk GitHub programma sieren als dat alsnog zou kunnen. Wij zien bij het aanmaken van deze vraag deze zaken niet staan zodat we ze kunnen invullen.

**Comment by ejmeulenkamp** [comment]
Waarschijnlijk was je niet ingelogd in GitHub. Je kunt dan alleen maar teksten invullen, maar geen labels, milestones en assignees invullen. Ik heb dit nu voor jullie gedaan.
