### ISSUE TITLE
zoomen op eigen server

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#103]
Als er ingezoomd word met vergrootglasje op een bepaald perceel dan komt dit perceel niet mooi gecentreerd in beeld. Een deel van het ingezoomde perceel ligt buiten de view.
In de test.crs2.nl werkt dit wel correct.

**Comment by LimburgsLandschapHarry** [comment]
nog een keer getest. Ook in de testomgeving internet werkt dit niet goed. Als je inzoomt op een perceel hoort het gecentreerd in het scherm weergegeven te worden. Dit is nu niet het geval. Een deel van het zoom kader verdwijnt buiten beeld.

**Comment by erikorbons** [comment]
Duplicaat van #140
