### ISSUE TITLE
knoppenbalk in viewer

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#104]
De knoppenbalk in de viewer bestaat uit losse knoppen die rechtstreeks in het kaartbeeld staan. Internet viewers die ik ken hebben de knoppen in een balk staan, zodat ze visueel los staan van de kaart. Lijkt me hier ook een fraaiere en eenvoudig te maken oplossing.

**Comment by LimburgsLandschapHarry** [comment]
net getest op de internetserver. Ook daar wordt niet naar het aangegeven vlakje gezoomd, maar ligt het perceel een beetje uit het midden en deels buiten beeld.

**Comment by LindaVels** [comment]
Als de knoppenbalk los komt te staan van de viewer dan moet de hoogte van de knoppenbalk worden vastgezet met als gevolg dat de knoppen niet verdeeld worden over meerdere regels wanneer de viewer verkleind wordt.
