### ISSUE TITLE
module kad.percelen zoomt niet in

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#105]
Vanuit module contracten in tabblad koppelingen een perceel dubbelklikken. Dan opent module kad.percelen. In het linker scherm verschijnt de info. In het rechter scherm verschijnt de hele kaart van Limburg. Er wordt niet ingezoomd op het geselecteerde perceel. Dit zou wel moeten. 
Inzoomen op het geselecteerde perceel is ook niet mogelijk, omdat de knop [inzoomen] grijs is.

**Comment by LimburgsLandschapHarry** [comment]
ook het selecteren van het perceel in het linkerscherm om vervolgens in te zoomen werkt niet.

**Comment by LimburgsLandschapHarry** [comment]
Ik heb overigens wel een lijst van 99 paginas met kad percelen die wel in crs voorkomen maar niet in akr. Een test perceel dat niet in wil zoomen staat in deze lijst. Als het daar aan ligt moeten we kijken hoe we dat op lossen.

**Comment by LimburgsLandschapHarry** [comment]
ik heb het idee dat er nog een paar problemen hieraan gerelateerd zijn. In de view krijg ik wel beeld van de kad percelen die van ons zijn, maar geen onderscheid in eigendom, beheer, erfpacht etc. Klikken in de view levert geen selectie op van het aangeklikte perceel en ook geen info op het linker scherm. Dit werkt in kad.percelen ook al niet op de internetserver omgeving. Bij afdelingen werkt het wel.
Verder testen van kad.percelen gaat niet lukken tot dit punt is opgelost.

**Comment by LindaVels** [comment]
Het probleem wordt veroorzaakt doordat er een discrepantie is tussen de door CRS2 gebruikte laagnaam (kad-percelen) en de in de viewer bekende laagnaam (percelen).
@ejmeulenkamp: Pak ik dit op of pas jij dit aan?

**Comment by ejmeulenkamp** [comment]
@LimburgsLandschapHarry In het venster Opties, op het tabblad GIS-Koppelingen dient in het veld "kaartlaagnaam" van het venster "Kad.Objecten" "Percelen" te staan. Je kunt dit aanpassen als je als applicatiebeheer in CRS2 ingelogd bent. Daarna zou de kaart in het venster Kad.Objecten moeten werken.
Ik zal er voor zorgen dat dit voor de volgende testronde bij iedereen aangepast is. Je kunt het dus nu ook zelf al aanpassen (op de centrale testserver en op de lokale testversie) om te zien of het werkt.

**Comment by ejmeulenkamp** [comment]
Na aanpassen van de kaartlaagnaam in het venster Opties opent het venster Kad.Objecten foutloos en zoomt het in naar het juiste perceel / percelen.
