### ISSUE TITLE
overzichten oppervlakte per terreintype per district naar excel werkt niet

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#106]
afdelingen, selectie = object = 102, overzichten oppervlakte per terreintype per district naar excel, van alle objecten.
foutmelding die ik hier niet in gekopieerd krijg: de gegevens voor de tabel cFinal kunnen niet opgehaald worden, en vervolgens nog een heleboel.
Enkelvoudige selectie naar excel werkt overigens wel.

**Comment by LimburgsLandschapHarry** [comment]
andere meervoudige selecties werken ook. Alleen meervoudeige selectie met terreintype doet moeilijk. Enkelvoudige selectie met terreintype functioneert.

**Comment by ejmeulenkamp** [comment]
Wat bedoel je met en enkelvoudige of meervoudige selectie?

**Comment by LimburgsLandschapHarry** [comment]
oppervlakte per terreintype, of opp per district; ipv per terreintype per district.

Valt me overigens nu pas op dat er wel per tereintype uitgedraaid kan worden, maar niet per beheertype. Dit terwijl beheertype de ingang voor het beheer is.

**Comment by ejmeulenkamp** [comment]
Alle oppervlakteoverzichten in het venster Afdelingen zijn opnieuw gecontroleerd. Vanaf versie 1.06.12 zouden ze foutloos moeten werken.

**Comment by ejmeulenkamp** [comment]
@LimburgsLandschapHarry  Zou je dit kunnen bevestigen?

**Comment by LimburgsLandschapHarry** [comment]
Ik krijg een foutmelding:

FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET LIMBURGS LANDSCHAP

Datum / Tijd:    23-04-2015 11:42:42
Gebruiker:       Bussink, Harry                          
Programmaversie: 1.06.13
Foutnummer:      1733 
Programmaregel:  54   

Foutboodschap:
    Class definition EXCEL.APPLICATION is not found.

Methode/Programma:
    C2EXCEL                                                                                                                 

Code:
    ASTACKINFO(laStackInfo)

Inhoud AERROR():
    1733
    Class definition GNERRORNUMBER is not found.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\LIMLAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEAFD.CMDPRINT.CLICK C:\HELPDESK\LIMLAND\C2FWFRM.VCT
    PROCEDURE CUSC2MENU.DOFORM C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE CUSC2FORMS.DOFORM C:\HELPDESK\LIMLAND\C2FW.VCT
    PROCEDURE FRMC2REPORTCATALOG.CMDRUN.CLICK C:\HELPDESK\VMP2005\XLIB\XXFWFRM.VCT
    PROCEDURE FRMC2REPORTCATALOG.RUNREPORT C:\HELPDESK\LIMLAND\C2FWFRM.VCT
    PROCEDURE FRMDIVTOT.INIT C:\HELPDESK\VMP2005\XLIB\XXFWMISC.VCT
    PROCEDURE FRMDIVTOT.PREPAREDATA C:\HELPDESK\LIMLAND\C2.VCT
    C2EXCEL.FXP
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2EXCEL)


Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    afdelingen, selectie object = 102, printer button > Oppervlakte per terreintype per district, dan volgt deze foutmelding.

**Comment by LimburgsLandschapHarry** [comment]
Hoi,

ook deze foutmelding heeft te maken met het niet aanwezig zijn van Excel in de internetomgeving. Op de eigen testomgeving werken de overzichten wel.
