### ISSUE TITLE
afdelingen selectie nsw = j, selectie onduidelijk in beeld

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#107]
ide crs krijg ik duidelijk middels blauwe selectie alle percelen in limburg in beeld die nsw=j hebben. In testversies geen blauwe omkadering bij zoomnivo heel limburg.
Oorzaak is dat ik in de huidige crs de omlijning blauw laat worden. Bij opschaling blijft dit in beeld. In de testversies is gekozen voor het blauw kleuren van de vlakken en de omlijning grijs te houden. Hierdoor verdwijnt het overzicht bij ver uitzoomen.
Nu of later aan te passen naar wensen gebruiker.

**Comment by LindaVels** [comment]
@LimburgsLandschapHarry: Kun je precies aangeven hoe je de selectie in beeld wilt hebben?
blauwe omlijning van de geselecteerde vlakken  zonder blauwe invulling? Welke kleur blauw heeft jullie voorkeur?

**Comment by LindaVels** [comment]
@LimburgsLandschapHarry : Op de test omgeving is de styling voor verschillende kaartlagen aangepast, bijvoorbeeld selectie van afdelingen worden nu getoond dmv een blauw randje en een "witte waas".  Verder zijn alle vlakvullingen transparant gemaakt zodat bijv de luchtfoto erdoorheen zichtbaar wordt. Zou je kunnen aangeven of deze styling in orde is?

**Comment by LimburgsLandschapHarry** [comment]
Hoi Linda,

ziet er voorlopig prima en werkbaar uit. De selectie blijft mooi duidelijk zichtbaar. De transparantie mag nog iets doorzichtiger. Ik denk echter dat ik her zelf tzt maar eens wat aan moet veranderen. Gewoon kijken wat het beste toont bij de verschillende lagen.
