### ISSUE TITLE
contracten-jachthuur-samenvoegen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#109]
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET LIMBURGS LANDSCHAP

Datum / Tijd:    17-03-2015 14:26:16
Gebruiker:       Bussink, Harry                          
Programmaversie: 1.06.11
Foutnummer:      1429 
Programmaregel:  3630 

Foutboodschap:
    OLE IDispatch exception code 0 from Microsoft Word: Record 1 bevat te weinig veldscheidingstekens ( , )...

Methode/Programma:
    C2DECTR.SAMEN.SAM                                                                                                       

Code:
    

Inhoud AERROR():
    1429
    GNERRORNUMBER.
    Record 1 bevat te weinig veldscheidingstekens ( , ).
    Microsoft Word
    wdmain11.chm
    25073
    5593

Programmapad:
    \\APP01\MEULENKAMP\CRS2SQLTEST\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS \\APP01\MEULENKAMP\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DECTR.CMDSAMEN.CLICK \\APP01\MEULENKAMP\CRS2SQLTEST\C2DECTR.SCT
    PROCEDURE C2DECTR.SAMEN.SAM \\APP01\MEULENKAMP\CRS2SQLTEST\C2.VCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DECTR.SAMEN.SAM)

Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    samenvoegen bij jachtcontract. Dit na aanpassen van de locatie waar de samenvoegbestanden staan.

**Comment by ejmeulenkamp** [comment]
@LindaVels Als ik nu in Brabant, het venster Transacties met de knop [Informatie opvragen] klik op een grondnummer, dan verschijnt de melding "In dit venster zijn geen gegevens bekend over de huidige kaartlagen".  Dit betekent in CRS2 dat er geen kaartlaagnaam gevonden is die overeenkomt met de voor dit venster ingestelde kaartlagen (venster 'Opties'). Ik ga er van uit dat de laag 'Aankopen' en de laag 'Verkopen' aanwezig zijn. Is dat zo?

**Comment by ejmeulenkamp** [comment]
Bovenstaande melding hoort in een ander issue thuis. Vergeten dus maar...

**Comment by ejmeulenkamp** [comment]
Het samenvoegen zou vanaf versie 4.06.15 foutloos moeten werken.

**Comment by LimburgsLandschapHarry** [comment]
nog steeds een foutmelding:

FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET LIMBURGS LANDSCHAP

Datum / Tijd:    24-06-2015 09:17:16
Gebruiker:       Bussink, Harry                          
Programmaversie: 1.06.17
Foutnummer:      11   
Programmaregel:  37   

Foutboodschap:
    Function argument value, type, or count is invalid.

Methode/Programma:
    CTRDAT1B                                                                                                                

Code:
    

Inhoud AERROR():
    11
    Function argument value, type, or count is invalid.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\LIMLAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DECTR.CMDSAMEN.CLICK C:\HELPDESK\LIMLAND\C2DECTR.SCT
    PROCEDURE C2DECTR.SAMEN.SAM C:\HELPDESK\LIMLAND\C2.VCT
    CTRDAT1B.FXP
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (CTRDAT1B)


Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    contracten, soort = jachthuur, selecteer. Op 103401 gaan staan en printknop gedrukt. Uit printvoorbeelden het bestand 'voorbeeld' geselecteerd.

**Comment by ejmeulenkamp** [comment]
Is dit issue nog steeds actueel?
