### ISSUE TITLE
toevoegen weekstaatregel lukt niet

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#11]
er volgt een foutmelding die ik hier niet in geplakt krijg. wellicht zelf even proberen een weekstaatregel toe te voegen.

**Comment by LimburgsLandschapHarry** [comment]
eerder plakken en knippen lukte niet. na alle foutmeldingen doorlopen te hebben kreeg ik deze systeemfout die ik middels [kopieer naar klembord] er wel ingevoegd kreeg.

FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET LIMBURGS LANDSCHAP

Datum / Tijd:    06-01-2015 12:35:08
Gebruiker:       Bussink, Harry                          
Programmaversie: 1.06.05
Foutnummer:      2005 
Programmaregel:  107  

Foutboodschap:
    Error loading file - record number 3.  c2pkprorsr <or one of its members>.  ControlSource : Alias 'CBEGR' is not found

Methode/Programma:
    C2DEWKSRSR.CTRPRO.TXTPV.DOPICKLISTFORM                                                                                  

Code:
    ASTACKINFO(laStackInfo)

Inhoud AERROR():
    2005
    GNERRORNUMBER
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\LIMLAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRRSR.CMDTOEV.CLICK C:\HELPDESK\VMP2005\XLIB\XXFWGRD.VCT
    PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRRSR.GRDSUB.ADDROW C:\HELPDESK\LIMLAND\C2DEWKS.SCT
    PROCEDURE GRDC2DATAENTRY.ADDROW C:\HELPDESK\LIMLAND\C2FWGRD.VCT
    PROCEDURE C2DEWKSRSR.CTRPRO.CMDICPICKLISTVALID1.CLICK C:\HELPDESK\VMP2005\XLIB\XXFWCOMP.VCT
    PROCEDURE C2DEWKSRSR.CTRPRO.ONBUTTONCLICK C:\HELPDESK\VMP2005\XLIB\XXFWCOMP.VCT
    PROCEDURE C2DEWKSRSR.CTRPRO.TXTPV.MENULOOKUP C:\HELPDESK\VMP2005\XLIB\XXFWCTRL.VCT
    PROCEDURE C2DEWKSRSR.CTRPRO.TXTPV.ACTIONONINVALID C:\HELPDESK\VMP2005\XLIB\XXFWCTRL.VCT
    PROCEDURE C2DEWKSRSR.CTRPRO.TXTPV.DOPICKLISTFORM C:\HELPDESK\VMP2005\XLIB\XXFWCTRL.VCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DEWKSRSR.CTRPRO.TXTPV.DOPICKLISTFORM)


Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================

**Comment by ejmeulenkamp** [comment]
Werkt het toevoegen van weekstaatregels nu wel?

**Comment by LimburgsLandschapHarry** [comment]
ja, toevoegen weekstaatregel is gelukt

**Comment by ejmeulenkamp** [comment]
Als een issue afgehandeld is, dan mag je hem ook sluiten (knop [Close issue] of [Close and comment].
Ik zal dit issue nu sluiten.
