### ISSUE TITLE
print lijsten van afdelingen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#110]
In afdelingen, met selecteer met vlak selectie maken van enkele afdelingen. Vervolgens print lijst van afdelingen. Daar zou de selectie geprint moeten worden. Alles wordt echter geprint. Dit is ook zo in het huidige crs, maar lijkt me niet de bedoeling.

**Comment by ejmeulenkamp** [comment]
Nadat je met "Selecteer via vlak" een selectie hebt gemaakt, moet je eerst op de knop [Info] (naast de knop [Nieuwe]) klikken. Daarmee worden alle via de kaart geselecteerde afdelingen administratief geselecteerd en zou je daarna wel alleen de geselecteerde afdelingen moeten kunnen afdrukken.
Werkt dit wel?

**Comment by LimburgsLandschapHarry** [comment]
n74 paginas krijgen met info over alle afdelingen van sll

**Comment by ejmeulenkamp** [comment]
Ik begrijp je antwoord niet

**Comment by LimburgsLandschapHarry** [comment]
Dat snap ik. Soms pakt ie het niet meteen als ik aan het typen ben.

Punt is dat het selecteren, vervolgens op knop info drukken en dan lijst van afdelingen printen nog steeds een lijst van alle afdelingen oplevert, van in totaal 74 pagina's. Terwijl ik een selectie heb gemaakt van 19 records.

**Comment by ejmeulenkamp** [comment]
Vanaf versie 1.06.12 worden alleen de geselecteerde records afgedrukt, voorlopig met een maximum van 250. Komt het voor dat er meer dan 250 objecten geselecteerd worden om iets mee te doen? Bij een administratieve selectie kan ik de selectiecriteria doorgeven naar de database om een overzicht te maken. Na een kaartselectie moet ik een serie nummertjes doorgeven. Daar zit een maximum aan. Kan zijn dat het nog naar 500 kan. Hoor graag wat nodig / zinvol is.

**Comment by ejmeulenkamp** [comment]
@LimburgsLandschapHarry Kun je bevestigen dat de lijst nu wel goed werkt en is 250 voldoende?

**Comment by LimburgsLandschapHarry** [comment]
Het werkt,
ik denk dat 250 voldoende is. Als je echter al een max van 500 in kunt stellen lijkt me dat beter. Loop je er later ook minder snel tegen aan.
