### ISSUE TITLE
odbc koppeling fout

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#113]
in projecten toevoegen begrotingsregel. Ook al via mail gemeld, met foutmelding. Hier ter documentatie en afhandeling.

**Comment by ejmeulenkamp** [comment]
Mij is niet duidelijk welke 'odbc-fout' er optreedt. Kun je er een schermafdruk van maken? De rest van de foutmeldingen wordt waarschijnlijk veroorzaakt door die odbc-fout.

**Comment by LimburgsLandschapHarry** [comment]
Nogmaals getest, geen foutmelding gekregen. Issue wordt afgesloten.
