### ISSUE TITLE
projecten-maatregelen-print maatregelen per project werkt niet

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#115]
gegevens voor tabel cFinal kunnen niet opgehaald worden.

**Comment by LimburgsLandschapHarry** [comment]
bij projectbewaking een soortgelijke foutmelding alleen kan dan tFinal niet gevonden worden.

**Comment by LimburgsLandschapHarry** [comment]
tabblad subsidies, maartegelenoverzicht exact. Soortgelijke foutmelding gegevens cFinal kunnen niet opgehaald worden.

**Comment by ejmeulenkamp** [comment]
Vanaf versie 1.06.12 zouden deze overzichten weer moeten werken.

**Comment by ejmeulenkamp** [comment]
@LimburgsLandschapHarry  Kun je dit bevestigen?

**Comment by LimburgsLandschapHarry** [comment]
laatste poging liep vast. zie onderstaande melding.

FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET LIMBURGS LANDSCHAP

Datum / Tijd:    23-04-2015 12:56:50
Gebruiker:       Bussink, Harry                          
Programmaversie: 1.06.13
Foutnummer:      1733 
Programmaregel:  54   

Foutboodschap:
    Class definition EXCEL.APPLICATION is not found.

Methode/Programma:
    C2EXCEL                                                                                                                 

Code:
    ASTACKINFO(laStackInfo)

Inhoud AERROR():
    1733
    Class definition GNERRORNUMBER is not found.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\LIMLAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEPRZ.CMDPRINT.CLICK C:\HELPDESK\LIMLAND\C2FWFRM.VCT
    PROCEDURE CUSC2MENU.DOFORM C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE CUSC2FORMS.DOFORM C:\HELPDESK\LIMLAND\C2FW.VCT
    PROCEDURE FRMC2REPORTCATALOG.CMDRUN.CLICK C:\HELPDESK\VMP2005\XLIB\XXFWFRM.VCT
    PROCEDURE FRMC2REPORTCATALOG.RUNREPORT C:\HELPDESK\LIMLAND\C2FWFRM.VCT
    PROCEDURE FRMPROEXA.INIT C:\HELPDESK\VMP2005\XLIB\XXFWMISC.VCT
    PROCEDURE FRMPROEXA.PREPAREDATA C:\HELPDESK\LIMLAND\C2.VCT
    C2EXCEL.FXP
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2EXCEL)


Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    project; tabblad subsidies; overzichtenctalogus; Maatregelenoverzicht Exact

**Comment by LimburgsLandschapHarry** [comment]
sorry, excelfoutje, en die zit hier nog steeds niet op. Ik zal het lokaal nog eens testen.

**Comment by LimburgsLandschapHarry** [comment]
lokaal werkt het
