### ISSUE TITLE
Encoding probleem selectie keuze velden

### ISSUE THREAD

**Issue by LindaVels** [IDgis/CRS2#117]
In het scherm waarnemingen in Zeeland kun je als hoofdgroep Kreeft-, spin- ... selecteren. CRS2 geeft een melding dat deze niet voorkomen terwijl ze wel in de database staan. Ook de viewer kan ze niet selecteren.

Dit wordt veroorzaakt door de encoding van het keuze veld. Ik zie de komma verschijnen als een vraagteken op de kop in de viewer.

De waarden van de selectie velden zouden UTF8 encoded moeten zijn.

**Comment by ejmeulenkamp** [comment]
Ik heb de waarden van de selectievelden omgezet naar UTF-8. Maar dat lost het probleem niet op. Heeft dit misschien iets te maken met de Server collation? Die is nu Latin1_General_CI_AS.
@HermanAssink  Weet jij hier misschien een antwoord op?

**Comment by ejmeulenkamp** [comment]
Vanaf versie 1.06.16 is het omgekeerde vraagteken verdwenen. De fout zat in de code van CRS2. Dit is nu opgelost.
