### ISSUE TITLE
wegschrijven waarneming geeft db fout

### ISSUE THREAD

**Issue by LindaVels** [IDgis/CRS2#118]
Bij wegschrijven waarneming in Zeeland krijg ik een ODBC verbindingsfout

**Comment by ejmeulenkamp** [comment]
Dit ligt waarschijnlijk aan het feit dat één of meer verplichte velden leeg zijn tijdens het opslaan. Ik zal onderzoeken of dit zo is en kijken of ik een melding kan geven in zo'n situatie.

**Comment by LindaVels** [comment]
treedt niet meer op
