### ISSUE TITLE
ZoomToLayer werkt lang niet altijd

### ISSUE THREAD

**Issue by LindaVels** [IDgis/CRS2#119]
Te reproduceren door
Scherm afdelingen in Zeeland:
Eerst object code 102 selecteren => selectie wordt getoond en kaart zoomt in
Vervolgens object code 307 selecteren => selectie wordt gezet maar kaart zoomt niet in

*** zoomToLayer(afdelingen,SELECT Afdelingen.Afdeling AS id, Afdelingen.Afdeling, Afdelingen.ogr_geometry AS geom FROM Afdelingen, afd, obj WHERE Afdelingen.Afdeling = obj.obj_code + afd.afd_afd AND obj.obj_pk = afd.afd_obj_fk AND afd_pk IN ( SELECT afd_pk FROM afd, obj, bhr, dis, rel, ren, prv, lnd, ter, ttg, ltd, fun, jbl, clu, bht, btg WHERE obj_pk = afd_obj_fk AND rel_pk = obj_rel_fk AND bhr_pk = obj_bhr_fk AND dis_pk = bhr_dis_fk AND ter_pk = afd_ter_fk AND ttg_pk = ter_ttg_fk AND ltd_pk = afd_ltd_fk AND fun_pk = afd_fun_fk AND jbl_pk = afd_jbl_fk AND prv.prv_pk = rel.rel_prv_fk AND lnd.lnd_pk = prv.prv_lnd_fk AND ren.ren_pk = rel.rel_ren_fk AND clu.clu_pk = afd.afd_clu_fk AND bht.bht_pk = afd.afd_bht_fk AND btg.btg_pk = bht.bht_btg_fk AND RTRIM(LTRIM(obj_code)) = '102' ),5000,99999999,true)
*** isFiltered(Afdelingen)
*** isLabeled(Afdelingen)
*** zoomToLayer(afdelingen,SELECT Afdelingen.Afdeling AS id, Afdelingen.Afdeling, Afdelingen.ogr_geometry AS geom FROM Afdelingen, afd, obj WHERE Afdelingen.Afdeling = obj.obj_code + afd.afd_afd AND obj.obj_pk = afd.afd_obj_fk AND afd_pk IN ( SELECT afd_pk FROM afd, obj, bhr, dis, rel, ren, prv, lnd, ter, ttg, ltd, fun, jbl, clu, bht, btg WHERE obj_pk = afd_obj_fk AND rel_pk = obj_rel_fk AND bhr_pk = obj_bhr_fk AND dis_pk = bhr_dis_fk AND ter_pk = afd_ter_fk AND ttg_pk = ter_ttg_fk AND ltd_pk = afd_ltd_fk AND fun_pk = afd_fun_fk AND jbl_pk = afd_jbl_fk AND prv.prv_pk = rel.rel_prv_fk AND lnd.lnd_pk = prv.prv_lnd_fk AND ren.ren_pk = rel.rel_ren_fk AND clu.clu_pk = afd.afd_clu_fk AND bht.bht_pk = afd.afd_bht_fk AND btg.btg_pk = bht.bht_btg_fk AND RTRIM(LTRIM(obj_code)) = '307' ),5000,99999999,true)

**Comment by ejmeulenkamp** [comment]
@LindaVels  Is dit issue nog openstaand?

**Comment by LindaVels** [comment]
Is inmiddels opgelost. Werd veroorzaakt door een bug in de js code (this moest zijn this.viewer)
