### ISSUE TITLE
kan niet plakken in Github

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#12]
meldingen krijg ik wel geknipt op de testserver, maar ik kan ze niet plakken in dit GitHub Write tabblad.
iemand een idee?

**Comment by HermanAssink** [comment]
Heb je GitHub open in de browser op de testserver of in de browser op je client?

**Comment by LimburgsLandschapHarry** [comment]
in eerste instantie op mijn eigen pc (de client dus). Vervolgens zag ik dat er ook op de testserver een link naar github was en het dus daar nogmaals geprobeerd met prtscn, ctr prtscn, ctr-alt prtscn. Geen van de opties werkte. Als ik vervolgens rechtermuisknop klik zit er niks om te 'pasten'.

**Comment by ejmeulenkamp** [comment]
Je kunt een fout via Print-Screen vastleggen, vervolgens Paint openen (taakbalk) en de fout opslaan. Daarna kun je in GitHub het bestand selecteren (onder het tekstvak waar je een bevinding intypt).

**Comment by HermanAssink** [comment]
De snipping tool voor het maken van een uitsnede van het scherm is geïnstalleerd en er is een snelkoppeling op de desktop gemaakt.
Hiermee is onderstaand "knipsel" gemaakt en uit het clipboard in dit venster geplakt:
![image](https://cloud.githubusercontent.com/assets/2979044/5636060/eb55ce62-95ee-11e4-9bc1-511dcd0a6631.png)

**Comment by LimburgsLandschapHarry** [comment]
Ik heb met de snap tool een foutmelding in crs geknipt. Ik krijg hem echter niet in dit tekstvak geplakt.
Normalerwijze zit het plaatje in het geheugen als je het knipt met de tool en hoef je alleen maar in dit tekstvak te gaan staan en ctr v te toetsen om het hier in beeld te krijgen. Ik heb het plaatje ook nog opgeslagen als png en jpg, om Evert Jan zijn aanwijzingen te volgen middels onderstaand [attach immages by dragging & dropping]. Dat resulteert in onderstaande onbegrijpelijke tekst, maar niet in een plaatje dat is ingevoegd.
Nog meer suggesties?

![capture](https://cloud.githubusercontent.com/assets/10415606/5659762/474872d6-9718-11e4-9fce-5fe71fcf9885.PNG)
![capture](https://cloud.githubusercontent.com/assets/10415606/5659789/760e906e-9718-11e4-81b6-164811c2d161.JPG)

**Comment by LimburgsLandschapHarry** [comment]
zo te zien lijkt het erop dat de plaatjes toch zijn ingevoegd, maar eerst tijdens het schrijven van het commentaar alleen als tekst in beeld komt. Beetje raar, maar is mee te werken. Nog mooier zou zijn dat ik gewoon op ctr v kan drukken. Dit is wat omslachtig.

**Comment by ejmeulenkamp** [comment]
Het is misschien niet optimaal, maar ik hoop dat het went.
