### ISSUE TITLE
Waarnemingen zeeland performen niet goed genoeg

### ISSUE THREAD

**Issue by LindaVels** [IDgis/CRS2#120]
- Gezien de enorme hoeveelheid worden waarnemingen pas zichtbaar gemaakt wanneer ze er een selectie wordt opgevraagd. Desondanks is het selecteren en tekenen van waarnemingen nog erg traag.

**Comment by LindaVels** [comment]
In de versie van 4 mei is het perfomance probleem opgelost door de waarnemingen te clusteren. De waarnemingen worden dus niet pas zichtbaar als er een selectie wordt gemaakt. Deze oplossing heeft onze voorkeur omdat de waarnemingenlaag dan hetzelfde reageert op selecteren e.d. dan de overige CRS2 lagen.
@HZLWannes : graag testen

**Comment by LindaVels** [comment]
Na testen op de testserver blijkt de huidige oplossing nog niet te voldoen.

**Comment by HZLWannes** [comment]
Ik werd al enthousiast, klinkt als een goede oplossing. Maar dan wacht ik nog even af.

**Comment by LindaVels** [comment]
Alleen de geselecteerde waarnemingen worden getoond, meer dan 10.000 waarnemingen worden niet op de kaart getoond
@HZLWannes voldoet deze oplossing?
