### ISSUE TITLE
Methode setSelectionLayer niet geïmplementeerd

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#122]
Voor het selecteren van afdelingen die aan een contract of project gekoppeld moeten worden, roep ik de methode setSelectionLayer aan. Hierdoor ben ik er zeker van dat men afdelingen gaat selecteren.
Ik krijg echter de melding '003 methode niet geïmplementeerd' terug. Ook via het testformulier verschijnt dezelfde melding.
Ik weet niet precies wat hierover is afgesproken, maar het koppelen van afdelingen aan een contract via de kaart wordt beschouwd als een basisfeature.

**Comment by ejmeulenkamp** [comment]
@HermanAssink  Kun jij achterhalen of deze methode bij de eerste oplevering hoort?

**Comment by HermanAssink** [comment]
Deze methode staat niet op onze todo lijst voor de huidige of latere oplevering. Daarom veronderstel ik dat deze al eerder is ontwikkeld. Was dit niet eerder getest?

**Comment by LindaVels** [comment]
Dit stond op mijn lijstje als "wordt niet gebruikt" en is dus ook niet geïmplementeerd. Ik denk dat we eerst eens goed duidelijk moeten krijgen wat selectionlayer en activelayer nou precies moeten doen. Momenteel kun je altijd selecteren in alle crs2 lagen, ongeacht  de waarde van active layer/selectionlayer. Het opvragen van informatie van een selectie wordt beperkt door de waarde van responsefields bij een crs2 laag.

**Comment by ejmeulenkamp** [comment]
In het venster Contracten is het voldoende dat de selectie beperkt wordt door de responsefields. In de vensters Projecten en Beheersubsidies moet je naast afdelingen ook lijnelementen en puntelementen kunnen selecteren. Dit gaat via aparte koppelknoppen: een voor afdelingen, een voor lijnelementen en een voor puntelementen. Gaat dat dan wel goed?
Eigenlijk is de vraag of ik vlak voordat men gaat selecteren eerst tegen de viewer moet zeggen in welke laag er geselecteerd moet gaan worden.

**Comment by ejmeulenkamp** [comment]
Na onderzoek is gebleken dat de methode niet meer nodig is. Als men bijvoorbeeld in een project op de knop "Koppel puntelementen" klikt, dan mag er van alles geselecteerd worden, maar CRS2 filtert er alleen de puntelementen uit en koppelt die aan het project. Dit geldt ook voor afdelingen en lijnelementen.
CRS2 zal de methode voortaan niet meer aanroepen.
