### ISSUE TITLE
Opvragen info transacties geeft foutmelding

### ISSUE THREAD

**Issue by LindaVels** [IDgis/CRS2#125]
@ejmeulenkamp 
testserver, CRS2 Brabant, scherm transacties:
- selecteer een vlakje in de kaart en druk op knopje Info -> volgende foutmelding verschijnt.
![foutmeldingtransacties](https://cloud.githubusercontent.com/assets/9080474/7292459/48216196-e99c-11e4-8f7d-67be515551c4.png)

**Comment by ejmeulenkamp** [comment]
@LindaVels Als ik nu op de testserver, in versie Brabant, het venster Transacties met de knop [Informatie opvragen] klik op een grondnummer, dan verschijnt de melding "In dit venster zijn geen gegevens bekend over de huidige kaartlagen". Dit betekent in CRS2 dat er geen kaartlaagnaam gevonden is die overeenkomt met de voor dit venster ingestelde kaartlagen (venster 'Opties'). Ik ga er van uit dat de laag 'Aankopen' en de laag 'Verkopen' aanwezig zijn. Is dat zo?
Ik kan momenteel de fout van dit issue niet reproduceren.

**Comment by LindaVels** [comment]
Dit probleem is opgelost in de versie van geoide-crs die staat geïnstalleerd op de testomgeving.
@ejmeulenkamp Graag testen.

**Comment by ejmeulenkamp** [comment]
Na klik op grondnummer in de kaart, verschijnen de gegevens van de transactie en staat de cursor op het bijbehorende grondnummer. Dit is zoals het zou moeten werken.
