### ISSUE TITLE
selelctie werkt niet

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#126]
de selectie van dennen eiken beuken bossen werkt niet. Op code wel, op omschrijving niet. Oorzaak is dat er een typefout in de beschrijving zit. 
![capture](https://cloud.githubusercontent.com/assets/10415606/7295636/e9b555d6-e9af-11e4-8e73-74b3ce06a594.JPG)

**Comment by LimburgsLandschapHarry** [comment]
bij bovenstaand plaatje is een cirkel gezet om de foute beschrijving. ER staat een spatie tussen het streepje en de komma.

**Comment by ejmeulenkamp** [comment]
We hebben uitgevonden dat het komt door de komma in het veld en het verschil in 'taal' dat CRS2 en SQL Server spreken. Voor cijfers en letters gaat dat wel goed, maar de wat meer bijzondere tekens wijken blijkbaar af. Een komma verschijnt hierdoor in SQL Server als een omgekeerd vraagteken en "Dennen-¿ eiken en beukenbossen" vindt ie niet. Ik ga dit onderzoeken.

**Comment by ejmeulenkamp** [comment]
Vanaf versie 1.06.16 worden selecties waar een komma in voorkomt wel goed uitgevoerd.

**Comment by LimburgsLandschapHarry** [comment]
het werkt!
