### ISSUE TITLE
afdelingen - overzichten beheertypen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#127]
Onze ingang voor het aansturen van beheer en het maken van overzichten voor management is 'beheertypen'. Op dit moment zijn deze niet uit CRS2 te draaien. Kunnen deze ook ingevoegd worden?

**Comment by ejmeulenkamp** [comment]
In het venster Afdelingen kun je wel selecteren op Beheertype (zie afbeelding). Is dit jou vraag of bedoel je nog iets anders?
![knipsel](https://cloud.githubusercontent.com/assets/10232554/7313473/25b2c802-ea5a-11e4-9841-9e371dd92bec.JPG)

**Comment by LimburgsLandschapHarry** [comment]
lijkt erop dat ik er overheen gekeken heb.
