### ISSUE TITLE
informatie opvragen in kaart, zoomt niet meer in.

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#128]
in afdelingen; met button i informatie opvragen een perceel geselecteerd. Na selectie van perceel zoomt de kaart automatisch in. Je kunt dan echter niet meer met de muiswiel verder in - of uit zoomen. Als je in de buttonbalk het handje selecteert kan het wel weer. Als je vervolgens de i button selecteert kan het ook weer wel.

**Comment by LindaVels** [comment]
De focus is het beschreven moment in het CRS2 scherm waardoor muisscroll events niet werken in de viewer. Het is niet wenselijk om de focus geforceerd op de viewer te zetten, dit kan ongewenste effecten hebben.
