### ISSUE TITLE
kan afdelingsnummer niet veranderen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#13]
in bestanden afdelingen, tabblad details probeer ik afdeling 223 02A te wijzigen in 223 02X. Dit is een niet bestaand nummer, komt niet voor op kaart. Ik kan wel wijzigen, maar niet opslaan. Dan reageert ie niet. Annuleren kan wel en dan kun je verder zonder foutmelding. 
Afdelingsnummer zou aangepast moeten kunnen worden naar elk gewenst (ook niet op kaart voorkomend) nummer.
Bij een reeds voorkomend nummer geeft ie keurig aan dat het nummer al in het bestand voorkomt.

**Comment by HZLWannes** [comment]
Bij nieuwe afdeling aanmaken kan ik niet verder dan het in vullen van de eerste twee velden (object afdeling). Vervolgens werkt niets, ik kan geen volgende velden invullen (niet met tab, niet met muis) en kan ook niet bewaren. Pas na klikken op annuleren, kan ik weer verder met het programma. Maar kan de nieuwe afdeling niet aanmaken.

**Comment by ejmeulenkamp** [comment]
Zou nu moeten werken

**Comment by LimburgsLandschapHarry** [comment]
Ik kan afdelingsnummers nu veranderen in niet bestaande. Krijg dan de gewenste melding dat ie in gis moet worden aangemaakt.
Als het bij Wannes ook werkt mag deze worden afgesloten.

**Comment by ejmeulenkamp** [comment]
@HZLWannes: Kun jij nu ook nieuwe afdelingen aanmaken en wijzigen?

**Comment by HZLWannes** [comment]
@LimburgsLandschapHarry @ejmeulenkamp Ook bij mij werkt het nu zoals het hoort.
