### ISSUE TITLE
kaart printen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#130]
fijn dat de kaart goed geprint wordt!!
Ziet er goed, scherp en duidelijk uit. labels zijn goed leesbaar.
graag onderstaande kleine puntjes aanpassen.
- logo en tekst uitlijnen, zodat een kleiner ruimtebeslag voor de stempel nodig is.
- vervolgens kaart maximaal op pagina zetten zodat bladzijde maximaal wordt benut.
- toevoegen variabele: datum.

**Comment by LindaVels** [comment]
@ejmeulenkamp In de templates staat een veld "datum". Ik dacht dat deze door CRS2 automatisch werd gevuld of ben ik abuis?

**Comment by ejmeulenkamp** [comment]
Als de variabele 'datum' in de lijst met variabelen van de template voorkomt, dan vult CRS2 die automatisch in met de datum van vandaag.

**Comment by LindaVels** [comment]
@ejmeulenkamp In alle templates komt een variabele datum voor (zie onderstaand event)

VFPS://onPrintButtonPressed/template=A3-liggend|Deze layout wordt organisatiebreed gebruikt voor standaardkaartjes op A3 Landscape.;notities;objectnaam;titel;gemaakt door;datum;template=A3-staand|Deze layout wordt organisatiebreed gebruikt voor standaardkaartjes op A3 Portrait.;notities;objectnaam;titel;gemaakt door;datum;template=A4-liggend|Deze layout wordt organisatiebreed gebruikt voor standaardkaartjes op A4 Landscape.;notities;objectnaam;titel;gemaakt door;datum;template=A4-staand|Deze layout wordt organisatiebreed gebruikt voor standaardkaartjes op A4 Portrait.;notities;objectnaam;titel;gemaakt door;datum;

**Comment by ejmeulenkamp** [comment]
Inderdaad, foutje. De variabele 'datum' staat toevallig altijd als laatste in de reeks. Tijdens het uitpluizen van de variabelen vergat ik de laatste. Dat is nu opgelost.
@LimburgsLandschapHarry  Wordt de datum nu wel als variabele meegenomen, ingevuld en afgedrukt op het kaartje?

**Comment by LimburgsLandschapHarry** [comment]
nee, nog niets te zien.

**Comment by LimburgsLandschapHarry** [comment]
kaartaanpassingen zijn doorgevoerd. 
Datum wordt geprint. 
uitlijning en bladverdeling zijn verbeterd. Prima!
Van mij mag de stempel (A4 liggend) nog wat kleiner, en dan ook het kaderveld waar die in staat met de tekst lager maken.
