### ISSUE TITLE
pagina printformaat

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#131]
bij keuze van kaart op A3 wordt deze nu automatisch uitgeprint op A4. Zal wel iets te maken hebben met het overrulen van de printerinstelling door pdf. Vooralsnog alleen op A3 te krijgen door in pdf/print te kiezen voor de eigenschappen van de pagina.

**Comment by LindaVels** [comment]
@ejmeulenkamp Kun je voor het openen van de pdf viewer/printer settings (zoals papier formaat en orientatie) wijzigen?

**Comment by ejmeulenkamp** [comment]
Ik kan wel settings van het PDF-venster wijzigen, maar printersettings niet, voor zover ik weet.
Ondersteunt de printer het formaat A3 wel?

**Comment by LimburgsLandschapHarry** [comment]
ja hoor, ik krijg er wel een A3 print uit, maar echter niet automatisch als ik A3 formaat print selecteer. Dat verwacht je wel als je op A3 kunt klikken dat er een A3 uitkomt.

**Comment by LindaVels** [comment]
De pdf reader vormt geen (direct)onderdeel van de applicatie. Voor ons is het niet mogelijk om de printersettings van de reader van buitenaf te beinvloeden.

**Comment by LimburgsLandschapHarry** [comment]
Ik heb ondervonden dat de kaartschaal nagenoeg goed gaat als bij printen wordt aangegeven dat ie op 100% moet afdrukken. In ieder geval niet verkleinen om de print goed op A4 te laten passen. Op 100% past ie ook prima en klopt de schaal.
