### ISSUE TITLE
kaart schaal

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#132]
de schaal van de kaart klopt niet helemaal. bij schaal 1:6000 op A3 is het schaalbalkje 9.2 cm lang op papier.

**Comment by LindaVels** [comment]
@LimburgsLandschapHarry : Een deel van de afwijking (niet alles, ik kom zelf aan 9.6 cm) wordt volgens mij veroorzaakt doordat de pdf printer default opstart met de optie "te grote pagina's verkleinen". Het kan zijn dat de marges te krap zijn gekozen. Of we de instellingen van de pdf printer kunnen beïnvloeden weet ik (nog) niet.
![naamloos](https://cloud.githubusercontent.com/assets/9080474/7300710/2358a828-e9de-11e4-8745-1074cd30822a.png)

**Comment by LindaVels** [comment]
In de oplevering van vorige week zou deze issue opgelost moeten zijn.
@LimburgsLandschapHarry :Zou jij dit kunnen testen/bevestigen

**Comment by LimburgsLandschapHarry** [comment]
Hallo Linda,

de schaal blijft een lastig punt. Dat heeft volgens mij alles te maken met het printen van een pdf. Wellicht dat het op te lossen is door de juiste instellingen bij het printen van een pdf, maar dat zou inhouden dat elke print de instellingen aangepast moeten worden. Dat kun je van een standard crs gebruiker niet verlangen. Tenzij je kunt zorgen dat de schaal op de print klopt stel ik onderstaande voor:
De tekst wijzigen in 'schaal ca. 1: xxxxx', De schaalbalk is altijd schaalvast. Die dus gewoon laten staan.

**Comment by LimburgsLandschapHarry** [comment]
Nog een toevoeging.

Mijn collega wees me erop dat je natuurlijk een pdf ook makkelijk kunt versturen naar aannemers. Die dan vervolgens een A3 kaart uitprinten op A4 formaat. Dan klopt van de schaaltekst helemaal niets meer.
Dit kan volgens mij op twee manieren worden ondervangen:
1: ergens in stempel (bij voorkeur bij de tekst ca. schaal 1: xxx) opnemen 'formaat A3 liggend' 
2: verwijderen tekst 'ca. schaal 1: xxxx' en alleen schaalbalk handhaven.

Mijn voorkeur gaat daarbij uit naar optie 1, dat geeft wat meer benul van de kaartschaal dan een balk.
