### ISSUE TITLE
logo's voor printtemplates updaten

### ISSUE THREAD

**Issue by LindaVels** [IDgis/CRS2#136]
Voor alle landschappen (behalve Limburg) dient het logo in de templates configuratie te worden vervangen door de juiste.

@ejmeulenkamp Zet jij de logo's klaar op de testserver

**Comment by ejmeulenkamp** [comment]
Ik heb de logo's klaargezet in de map \Helpdesk\Meulenkamp\Logos

**Comment by LindaVels** [comment]
De logo's zijn omgezet naar png en in de juiste mappen geplaatst. Ze worden getoond op de print. Een aantal logo's zijn van matige kwaliteit (zoals Groningen en Zeeland).
