### ISSUE TITLE
kaart printen toevoegingen tekst

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#137]
bij het printen van een kaart kan ik als tekst mijn naam invoegen bij 'gemaakt door:' Echter, deze verschijnt niet op de print.

**Comment by erikorbons** [comment]
Het lukt mij niet om dit te reproduceren in de huidige testversie.

Wel valt het mij op dat wanneer er in het afdrukvenster een andere template wordt gekozen terwijl er al velden zijn ingevuld (zoals bijvoorbeeld "gemaakt door") dat deze waardes weer leeg worden gemaakt. Zou het kunnen dat deze bevinding hier mee te maken heeft? De procedure is dan: 

1. "gemaakt door" invullen
2.  een template kiezen
3. Op de knop afdrukken klikken

**Comment by LimburgsLandschapHarry** [comment]
Net een test uitgevoerd. Alle ingevulde velden verschijnen in beeld. Fout kan door mij ook niet meer herhaald worden. 
Werkvolgorde loopt bij mij van boven naar beneden (zoals logisch is) Eerst template kiezen, dan invullen velden, dan print.
