### ISSUE TITLE
akr levering verwerken

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#139]
Hier kan gekozen worden voor:
1. Akr database bijwerken. bij het uitvoeren van de deze actie kan de applicatie KadoMo niet gevonden worden.
2. CRS database bijwerken. Hier kan de database kd.dbc niet gevonden worden.

**Comment by HermanAssink** [comment]
KadoMO kan niet met SQL server werken. Dat wordt geregeld met BRK2DB. Om met BRK2DB verder te kunnen wachten we op testdata van de landschappen.

**Comment by LimburgsLandschapHarry** [comment]
Ok duidelijk. Ik heb een offerte aangevraagd. Daar afgelopen week nog een keer achteraan gebeld. Offerte zou deze week hier moeten zijn.
