### ISSUE TITLE
ongelijke inzoom in verschillende vensters

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#14]
Als ik in venster afdelingen een selectie maak, wordt ingezoomd op het geselecteerde vlak / de geselecteerde vlakken en een ruimere omgeving. Als ik vervolgens deze selectie open in het venster kad.objecten dan wordt volledig ingezoomd op de selectie. Kortom het hele perceel is dan beeldvullend in beeld. Mijn voorkeur heeft het om in alle vensters in te zoomen naar de selectie en een zone er omheen, tbv het overzicht.

**Comment by ejmeulenkamp** [comment]
In de opties van CRS2 (tabblad GIS-koppelingen) kun je schaalgrenzen instellen, zodat niet verder ingezoomd wordt dan bijvoorbeeld 1 op 5000. Lost dit je probleem op?

**Comment by LindaVels** [comment]
Het niveau van inzoomen wordt inderdaad bepaald aan de hand van de ingestelde schaalgrens.

**Comment by LimburgsLandschapHarry** [comment]
prima, dank jullie. Is dus gewoon een kwestie van instellen. Vraag bij deze beantwoord.
