### ISSUE TITLE
inzoomen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#140]
als mbv vergrootglas wordt ingezoomt op een gebied, verwacht je dat de extent die met het vergrootglas is aangegeven de nieuwe view wordt. Dit is niet het geval. het ingezoomde deel ligt niet centraal in beeld, en valt er zelfs deels buiten.
(Reeds eerder gemeld).

**Comment by erikorbons** [comment]
Duplicaat van #103 

Dit is opgelost en komt mee in de volgende versie van de viewer.

**Comment by LindaVels** [comment]
Deze laatste versie is op de testserver geïnstalleerd.

**Comment by LimburgsLandschapHarry** [comment]
Het werkt,

Kreeg deze opmerking niet in github, vandaar via de mail.

Dank.


Met vriendelijke groet,

Harry Bussink
medewerker Beheerplanning en Monitoring
Stichting het Limburgs Landschap

ps: vrijdags afwezig

Postbus 4301, 5944 ZG Arcen | bezoekadres: Rijksstraatweg 1, 5943 AA Lomm |
• 077-4737575 | 06-51130868 | • h.bussink@limburgs-landschap.nl<mailto:h.bussink@limburgs-landschap.nl> | www.limburgs-landschap.nl<http://www.limburgs-landschap.nl> |

Aan de inhoud van dit e-mailbericht kunnen geen rechten worden ontleend. De informatie is uitsluitend bestemd voor de geadresseerde. Stichting het Limburgs Landschap staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mailbericht, inclusief eventueel meegezonden bijlagen, noch voor tijdige aankomst daarvan. Stichting het Limburgs Landschap aanvaardt geen aansprakelijkheid voor schade, van welke aard ook, die verband houdt met risico's verbonden aan het elektronisch verzenden van berichten.

Van: LindaVels [mailto:notifications@github.com]
Verzonden: maandag 31 augustus 2015 10:25
Aan: IDgis/CRS2
CC: Harry Bussink
Onderwerp: Re: [CRS2] inzoomen (#140)


Deze laatste versie is op de testserver geïnstalleerd.
