### ISSUE TITLE
scherm kad.objecten - foutmelding

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#141]
fout begint met 
![foutmelding](https://cloud.githubusercontent.com/assets/10415606/8723178/e919833c-2bcb-11e5-838d-fa87dec85e19.jpg)

FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET LIMBURGS LANDSCHAP

Datum / Tijd:    16-07-2015 14:57:14
Gebruiker:       Bussink, Harry                          
Programmaversie: 1.06.18
Foutnummer:      1426 
Programmaregel:  63   

Foutboodschap:
    OLE error code 0x80020101: Unknown COM status code.

Methode/Programma:
    C2DEKAD.SETRESPONSEFIELDS                                                                                               

Code:
    

Inhoud AERROR():
    1426
    OLE error code 0xGNERRORNUMBER.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    \\APP01\MEULENKAMP\CRS2SQLTEST\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS \\APP01\MEULENKAMP\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEKAD.OLEMAP.BEFORENAVIGATE2 \\APP01\MEULENKAMP\CRS2SQLTEST\C2OLE.VCT
    PROCEDURE C2DEKAD.SETRESPONSEFIELDS \\APP01\MEULENKAMP\CRS2SQLTEST\C2FWFRM.VCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DEKAD.SETRESPONSEFIELDS)

Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    Bestanden, kad.objecten
    vervolgens foutmelding; error in script en vervolgens vraag of je sript wilt runnen on this page. Ongeacht of je daar ja of nee op antwoord krijg je deze foutmelding.

**Comment by ejmeulenkamp** [comment]
In Extra > Opties > Giskoppelingen stond bij Kad.Objecten de 'kaartlaagnaam' 'Kad-Percelen' ingesteld. Dit moest 'Percelen' zijn (configuratiefout van mij). Ik heb het aangepast en de fout treedt nu niet meer op.

**Comment by LimburgsLandschapHarry** [comment]
het venster start nu wel op zonder foutmeldingen, echter ik krijg de percelen niet in beeld.
Ook de andere kaartlagen (afdelingen, elementen, gebouwen, ...) komen niet meer in beeld.
Ook voor het venster afdelingen geldt dit. Bij selecteren op object xxx wordt wel op de juiste kaartlocatie ingezoomd.

**Comment by ejmeulenkamp** [comment]
Ik begrijp niet goed wat je bedoelt. Ik heb jullie lokale testversie van CRS2 opgestart. Daarna venster 'Afdelingen' geopend. Selectie gemaakt, kaart zoomt in op de geselecteerde afdelingen.
Daarna venster 'Kad.objecten' geopend, selectie gemaakt, kaart zoomt in naar geselecteerde kad.objecten. Na klik met knop "informatie opvragen" verschijnt de juiste informatie.
Is het nog iets anders wat er niet werkt?

**Comment by LimburgsLandschapHarry** [comment]
Ik heb getest op onze eigen server en op de internetserver. Onze eigen server werkt. Op de internetserver krijg ik geen beeld van onze afdelingen.
