### ISSUE TITLE
#36 doet zich opnieuw voor

### ISSUE THREAD

**Issue by HZLWannes** [IDgis/CRS2#143]
@ejmeulenkamp Selecteren van waarnemingen lijkt goed te gaan tot je de knoppen gebruikt die meerdere selectiecriteria toelaat (Gebied, regio, regelingen). Bij het klikken op een van de knoppen komt er een foutmelding, die er voor zorgt dat het programma afsluit.

**Comment by HZLWannes** [comment]
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET ZEEUWSE LANDSCHAP

Datum / Tijd:    14-08-2015 15:32:29
Gebruiker:       Castelijns, Wannes                      
Programmaversie: 1.06.18
Foutnummer:      1925 
Programmaregel:  15   

Foutboodschap:
    Unknown member CBOADV.

Methode/Programma:
    C2DEWRN.PGFPAGEREFRESH1.PAGE1.CTRSC.CMDOBJ.CLICK                                                                        

Code:
    

Inhoud AERROR():
    1925
    Unknown member GNERRORNUMBER.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    \\SERVER\CRS2\MEULENKAMP\CRS2SQLTEST\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS \\SERVER\CRS2\MEULENKAMP\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWRN.PGFPAGEREFRESH1.PAGE1.CTRSC.CMDOBJ.CLICK \\SERVER\CRS2\MEULENKAMP\CRS2SQLTEST\C2DEWRN.SCT
   XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DEWRN.PGFPAGEREFRESH1.PAGE1.CTRSC.CMDOBJ.CLICK)


Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================

**Comment by ejmeulenkamp** [comment]
De fout trad opnieuw op omdat ik de eerste twee datumvelden van de selectiecriteria op het tabblad Lijst veranderd had van keuzelijstjes naar invoervelden. Achter de knoppen: Districten, Beheerregio's, Objecten en Regelingen zat programmacode die daar nog op aangepast moest worden.
Dat is nu gebeurd en de gemelde fout treed vanaf de volgende versie niet meer op.

**Comment by HZLWannes** [comment]
Oke, ik wacht af. hartelijk dank.

**Comment by HZLWannes** [comment]
milestone 1.06.19?

**Comment by HZLWannes** [comment]
@ejmeulenkamp Evert-Jan. Dit lijkt inderdaad opgelost als je eerst op een van de knoppen klikt en dan pas verder selecteerd in omgekeerde volgorde krijg je toch nog een foutmelding. 

FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET ZEEUWSE LANDSCHAP

Datum / Tijd:    02-09-2015 12:40:51
Gebruiker:       Castelijns, Wannes                      
Programmaversie: 1.06.20
Foutnummer:      11   
Programmaregel:  17   

Foutboodschap:
    Function argument value, type, or count is invalid.

Methode/Programma:
    C2DEWRN.PGFPAGEREFRESH1.PAGE1.CTRSC.CMDOBJ.CLICK                                                                        

Code:
    

Inhoud AERROR():
    11
    Function argument value, type, or count is invalid.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\ZEELAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWRN.PGFPAGEREFRESH1.PAGE1.CTRSC.CMDOBJ.CLICK C:\HELPDESK\ZEELAND\C2DEWRN.SCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DEWRN.PGFPAGEREFRESH1.PAGE1.CTRSC.CMDOBJ.CLICK)


Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    Dit lijkt inderdaad opgelost als je eerst op een van de knoppen klikt en dan pas verder selecteerd in omgekeerde volgorde krijg je toch nog een foutmelding.

**Comment by ejmeulenkamp** [comment]
Ik heb de oorzaak van de fout gevonden. Kun je bevestigen dat hij opgelost is?

**Comment by HZLWannes** [comment]
Het werkt nu prima.
