### ISSUE TITLE
problemen kaart bij opstarten

### ISSUE THREAD

**Issue by HZLWannes** [IDgis/CRS2#144]
@LindaVels @ejmeulenkamp 
Ter kennis name:

Ik heb voor het presentaren van de kaart nog iedere werkdag onze ICT nodig. Eerst moest er een vinkje uit in explorer, dat vereist dat intranet geladen wordt met een compatibiliteitsweergave, na het weekend bleek het programma op de achtergrond weer ('weer' is aldus ICT) gestopt. Dit draait dus nog niet stabiel.

**Comment by LindaVels** [comment]
Wij gaan onderzoek doen naar de stabiliteit van de kaartservices voor Zeeland. We hebben het vermoeden dat door de grote aantallen waarnemingen er een probleem met het geheugen ontstaat.

**Comment by LindaVels** [comment]
We hebben de applicatie voor Zeeland getest en verder geen problemen meer ondervonden.
@HZLWannes Laat even weten of we hier nog verder actie op moeten ondernemen of dat je er met jullie ICT uit kan komen.

**Comment by HZLWannes** [comment]
@LindaVels  Het werkt momenteel weer niet, ik krijg weer geen viewer te zien en het ligt nu niet aan de instellingen van de brouwser de compatibillity is zoals mij is verteld dat hij moet staan (en het voorheen dus wel werkte).

**Comment by LindaVels** [comment]
@HZLWannes: Heb je er behoefte aan dat ik meekijk via bijv teamviewer?

**Comment by HZLWannes** [comment]
@LindaVels ja prima!

**Comment by HZLWannes** [comment]
@LindaVels    0113-569120

**Comment by ejmeulenkamp** [comment]
@LindaVels: Ik heb zojuist in de lokale SQL-testversie van Zeeland gezien dat de afdelingen niet getoond worden. Als je iets selecteert, dan wordt er wel op ingezoomd, maar je ziet ze niet. Is dit probleem bekend?
