### ISSUE TITLE
selectie van waarnemingen op kaart

### ISSUE THREAD

**Issue by HZLWannes** [IDgis/CRS2#146]
Het selecteren van warnemingen gaat super snel, en ook de presentatie van clusters bij veel stippen is een goed werkbare oplossing. Maar hij selecteren lijk een soort van willekeur, ik heb nog geen niveau kunnen ontdekken waarop alle waarnemingen in het administratieve deel ook op kaart worden geselecteerd. Ook wordt er nog niet naartoe gezoomd. Het filter werkt overigens wel. Wat mij betreft belangrijker.

**Comment by LindaVels** [comment]
Ik denk dat deze "willekeur" een resultaat is van de clustering van de geselecteerde waarnemingen. Welke en hoeveel waarnemingen geclusterd worden is afhankelijk van het zoomniveau. Als je inzoomt op een geselecteerd punt kan het bij inzoomen opeens om meerdere geselecteerde punten te gaan. De clustering van de geselecteerde punten kan ook verschillen van de clustering van alle punten waardoor een bepaald "punt" in twee clusters kan voorkomen (dus op twee verschillende plekken). 

Het zoomen naar de selectie moet ik nog nader onderzoeken. 

@HZLWannes Graag zou ik met jou jullie werkproces voor waarnemingen doornemen om zodoende tot een optimalisatie van de gekozen oplossing te komen. Wellicht dmv een teamviewer sessie op onze testomgeving.

**Comment by LindaVels** [comment]
De clustering bleek meer problemen te veroorzaken dan op te lossen, deze oplossingrichting is weer teruggedraaid. Nu worden in de viewer alleen de geselecteerde waarnemingen zichtbaar.
In het CRS deel is een blokkering ingebouwd: wanneer het aantal geselecteerde waarnemingen groter is dan 10.000 worden deze niet getoond op de kaart. 
@HZLWannes: Zou je dit kunnen testen op de testserver?

**Comment by HZLWannes** [comment]
@LindaVels lijkt nu prima te werken. Wordt er bij zo'n 7000 waarnemingen iets trager van, maar dat mag bij zo'n hoeveelheid, ik merk dat het bij minder sneller gaat, Dus dat is wat je zou verwachten. Prima zo.

**Comment by HZLWannes** [comment]
Nu dit selecteren ook direct als filter werkt, maar wat mij betreft de selectiekleur uit, of anders nadat je op de filterknop klikt, want nu kun je alleen een print maken met de selectiekleur.

**Comment by HZLWannes** [comment]
Dit is eigenlijk direct filteren, dus wat mij betreft mag ook de selectiekleur dan achterwege blijven.

**Comment by LindaVels** [comment]
@HZLWannes Ik heb de selectiekleur aangepast voor waarnemingen zodat er geen verschil meer is tussen geselecteerde en niet geselecteerde objecten. Zie centrale testserver

**Comment by LindaVels** [comment]
oplossing blijkt te voldoen
