### ISSUE TITLE
coordinaat invoeren bij het aanmaken van een waarnemingen

### ISSUE THREAD

**Issue by HZLWannes** [IDgis/CRS2#147]
Bij het invoeren van nieuwe waarnemingen kan ik momenteel alleen het intypen gebruiken, dat is de optie die we het minst gebruiken. Er zijn nog twee andere opties mogelijk (die nu niet werken). Het objectcoördinaat invullen (wat bij stambestand objecten is weggeschreven), nadat de objectnaam is ingevuld  en de digitaliseerstip via de viewer. Beide werken niet. Als ik wel een coördinaat invoer werkt momenteel de afkapfunctie wel goed.

**Comment by HZLWannes** [comment]
Het betreft alleen nog de digitaliseerstip die niet het coördinaat invult, ook blijft er nog geen stip achter.

**Comment by LindaVels** [comment]
De coördinaten worden nu op de juiste manier aan het crs scherm doorgegeven, te testen op de testserver.

**Comment by HZLWannes** [comment]
Digitaliseerstip lijkt prima te functioneren! Hartelijk dank.
