### ISSUE TITLE
foutmelding bij importeren waarnemingen

### ISSUE THREAD

**Issue by HZLWannes** [IDgis/CRS2#148]
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET ZEEUWSE LANDSCHAP

Datum / Tijd:    20-08-2015 14:55:31
Gebruiker:       Castelijns, Wannes                      
Programmaversie: 1.06.18
Foutnummer:      10   
Programmaregel:  118  

Foutboodschap:
    Syntax error.

Methode/Programma:
    C2WRNIMP.CMDCONTROLE.CLICK                                                                                              

Code:
    

Inhoud AERROR():
    10
    Syntax error.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    \\SERVER\CRS2\MEULENKAMP\CRS2SQLTEST\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS \\SERVER\CRS2\MEULENKAMP\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2WRNIMP.CMDCONTROLE.CLICK \\SERVER\CRS2\MEULENKAMP\CRS2SQLTEST\C2WRNIMP.SCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2WRNIMP.CMDCONTROLE.CLICK)

Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
Heb een importdefinitie aangemaakt, en krijg deze foutmelding. Nu is altijd de vraag of het aan mijn importdefinitie ligt of aan iets in crs-systeem. Kun jij dat zien @ejmeulenkamp .

**Comment by ejmeulenkamp** [comment]
Er is een nieuwe versie geplaatst. Hierna komt er een andere melding:
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
 STICHTING HET ZEEUWSE LANDSCHAP

Datum / Tijd: 20-01-2016 15:20:36
 Gebruiker: Castelijns, Wannes

 Programmaversie: 2.00.05
 Foutnummer: 1712 
 Programmaregel: 121

 Foutboodschap:
Field name is a duplicate or invalid.


Methode/Programma:
 C2WRNIMP.CMDCONTROLE.CLICK

 Code:
 Inhoud AERROR():
 1712
 Field name is a duplicate or invalid.
 GNERRORNUMBER

Programmapad:
 \SERVER\CRS2\MEULENKAMP\CRS2SQLTEST\CRS2.EXE
 XXFWMAIN.FXP
 PROCEDURE CTRC2APP.READEVENTS \SERVER\CRS2\MEULENKAMP\VMP2005\XLIB\XXFW.VCT
 PROCEDURE C2WRNIMP.CMDCONTROLE.CLICK \SERVER\CRS2\MEULENKAMP\CRS2SQLTEST\C2WRNIMP.SCT
 XXERROR.FXP
 PROCEDURE LOGERROR XXERROR.FXP
 (C2WRNIMP.CMDCONTROLE.CLICK)

Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:

**Comment by HZLWannes** [comment]
Ik ben erg benieuwd hoe het hier mee staat.

**Comment by HZLWannes** [comment]
Dit wordt binnenkort cruciaal, we hebben veel via apps ingevoerd, en dit willen we graag in onze database gaan zetten. We lopen hier al een jaartje mee achter.

**Comment by ejmeulenkamp** [comment]
Sorry dat het zo lang geduurd heeft. Het is een lastig probleem. De melding geeft aan dat het om een (1) dubbele veldnaam gaat of om een (2) ongeldige veldnaam. Zou je het volgende eens willen onderzoeken:

1) Een veldnaam mag maximaal 10 tekens lang zijn. Heb je velden in je importbestand waarvan de eerste 10 tekens hetzelfde zijn?
2) Een veldnaam mag alleen de volgende tekens bevatten: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_1234567890
Bovendien mag het eerste teken van een veld geen cijfer zijn.
Bevat één van de velden misschien een teken dat niet toegestaan is?

Ik hoor het graag van je.

**Comment by HZLWannes** [comment]
![image](https://cloud.githubusercontent.com/assets/10400913/16379935/4ee6eb00-3c74-11e6-966f-106bf711adbf.png)
![image](https://cloud.githubusercontent.com/assets/10400913/16379948/5b8c57c8-3c74-11e6-87d7-162fd2da2d65.png)

**Comment by HZLWannes** [comment]
Volgens mij heb ik het ingevuld zoals hierboven. Ook het bestand, dit is eigenlijk heel simpel, het is namelijk een export uit crs, die ik na wijziging van objectcode of iets degelijks terug wil importeren. Dat is een handeling die ik veel doe. In xls kun je namelijk een hele kolom meet waarden in 1 handeling veranderen. 
Daarnaast heb ik nog vele enkele import bestanden die ik veel gebruik, maar ik dacht dit zou de eenvoudigste moeten zijn. De volgende hele belangrijke zijn die van Sovon en waarneming.nl.

**Comment by HZLWannes** [comment]
Aha, leuk deze interactie. Want ik bedenk me dat een veld dubbel kan lijken. Ik wil namelijk ook meerdere gebieden tegelijk kunnen importeren. Ik kan namelijk ook een veld aanwijzen waar een objectcode in staat. Bij het importeren wordt nu verplicht (voorheen in crs een keuze) een standaard object in te geven. Zou het kunnen dat hij dat als dubbel ziet?!
