### ISSUE TITLE
Info knop werkt niet zoals verwacht

### ISSUE THREAD

**Issue by LindaVels** [IDgis/CRS2#149]
Afdelingen: Als ik in de kaart met een vlak of punt meerdere afdelingen selecteer en vervolgens op Info klik dan opent zich het detail scherm met 1 van de afdelingen, in de lijst staat vervolgens ook maar 1 afdeling, Dit werkte voorheen anders

**Comment by HZLWannes** [comment]
@ejmeulenkamp Hier kwam ik ook net achter @LindaVels. Bij de waarnemingen module gaat het nog een stap verder, daar blijft de info knop na selectie op kaart uitgegrijsd.

**Comment by ejmeulenkamp** [comment]
Ik heb de vermoedelijke oorzaak zojuist doorgemaild naar Linda. We komen hier op terug.

**Comment by ejmeulenkamp** [comment]
In het venster Waarnemingen gaat onSelectionChanged niet af na het selecteren van waarnemingen. Als ik op de kaart een selectie zie en ik klik op "Selectie wissen", dan gaat het event wel af.

**Comment by LindaVels** [comment]
@HZLWannes: een en ander zou nu opgelost moeten zijn op de centrale testserver, zou je kunnen testen?

**Comment by HZLWannes** [comment]
Klopt het werkt. Na het selectievlak te tekenen (laatste klik een dubbel klik) zou je verwachten dat je de selectie lijn kwijt bent die blijft nu hangen.

**Comment by LindaVels** [comment]
@HZLWannes: vreemd ... dat probleem kan ik niet reproduceren. Wat doe ik anders? Of liever gezegd wat doe jij precies?

**Comment by HZLWannes** [comment]
@LindaVels als je je selectie vorm echt volledig maakt en dus dubbelklikt op de eerste stip, gebeurt dit. Ik ben er achter dat je of moet dubbelklikken, maar niet op de eerste stip, of eenmaal klikken op de eerste stip om te stoppen. Werkt dus prima, moest het alleen even uitvinden.
