### ISSUE TITLE
uitgevinkte kaartlaag blijft in beeld

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#15]
vanuit tabblad afdelingen naar subsidies gegaan. Daar gekeken welke afdelingen aan de subsidie hangen. Vervolgens 'koppel afdelingen' aangeklikt. Een handvol afdelingen uit de subsidie verwijderd. Nog niet op bewaren geklikt maar wel naar tabblad afdelingen gegaan. Daar in de legenda de laag afdelingen uitgezet. De kaartlaag blijft echter wel in beeld. In dit geval als een paarse kleur. Zet ik het vinkje aan, dan komen de afdelingen roze in beeld (zoals door jullie geconfigureerd). Tevens is dan de geselecteerde afdeling blauw zichtbaar.
Vervolgens in tabblad beheersubsidies de wijzigingen bewaard. Opnieuw op [open venster afdelingen] geklikt. De uitgevinkte laag bleef zichtbaar (paars).
Het lijkt erop dat dit probleem (eerder gemeld door Willem Peeters) zich alleen voordoet als je een tabblad via een ander tabblad benaderd. Na afsluiten van alle tabbladen en opnieuw opstarten van afdelingen kan ik lagen gewoon aan- en uit zetten.

**Comment by LindaVels** [comment]
kadastrale percelen worden in paars getoond. Deze staan "aan" in de kaart behorend bij subsidies. Misschien is dit onterecht? Als je het mapje kadaster openklikt en vervolgens percelen uitvinkt dan verdwijnen de paarse percelen. Je kunt zien hoe de verschillend kaartlagen getekend worden door het plusje aan te klikken bij een kaartlaag in de legenda.

**Comment by LimburgsLandschapHarry** [comment]
Dat lagen aan of uit staan maakt niet zo veel uit. Dat is aan te passen door ze uit te vinken. Maar daar zit nu net het probleem. Net Subsidies geopend (selectie subsidienummer 2, tabblad details, select alle voordat ie inzoomt <dit probleem aangekaart onder ander issue>). De legenda open gezet. Daar blijkt kadaster niet aan te staan. 
![capture](https://cloud.githubusercontent.com/assets/10415606/5660368/bbf014ca-971f-11e4-85d6-79eeba1bdbec.JPG)
Als ik de lagen punten, lijnen, afdelingen uitzet verdwijnen die netjes uit beeld. Echter de kadasterlaag blijft in beeld, terwijl die niet eens aanstaat.

**Comment by LimburgsLandschapHarry** [comment]
net in de eigen testomgeving nogmaals deze fout tegen gekomen.
De laag staat uit maar blijft wel in beeld omdat een onderliggende laag nog aanstaat. Naast deze issue is dit volgens mij ook al een keer aangegeven in een ondertussen gesloten issue. Probleem is echter nog aanwezig.
