### ISSUE TITLE
logica selectie opheffen

### ISSUE THREAD

**Issue by LindaVels** [IDgis/CRS2#150]
Bij selecteren – vlak kom ik het volgende tegen.

Ik selecteer een 10tal percelen middels ‘vlak’. Als ik dan onderin op ‘info’ druk, krijg ik links de bijbehorende administratieve info te zien.

Als links op selectie wissen klik, verdwijnt zowel administratief als in de kaart de selectie. Als ik in de kaart op selectie wissen button druk verdwijnt de selectie alleen op kaart. Volgens mijn logica zou dan ook de administratieve info leeg moeten worden.

**Comment by ejmeulenkamp** [comment]
Goed punt. Dit is echter tot nu toe altijd zo geweest. Ik heb er geen vragen of opmerkingen over gekregen. Als er vragen over komen, dan kunnen we er alsnog naar kijken.
