### ISSUE TITLE
Kaartkoppeling werken plotseling niet meer binnen CRS. Wordt er momenteel misschien gewerkt aan de viewer?

### ISSUE THREAD

**Issue by MirellW** [IDgis/CRS2#151]

**Comment by MirellW** [comment]
Kaartkoppeling werken plotseling niet meer binnen CRS. Wordt er momenteel misschien gewerkt aan de viewer?

**Comment by ejmeulenkamp** [comment]
Hoi Mirella,
Is dit issue nog actueel?
