### ISSUE TITLE
fout in bijwerken objectnaam meerdere prints achter elkaar

### ISSUE THREAD

**Issue by MirellW** [IDgis/CRS2#157]
Als je meerdere contracten uit verschillende objecten achter elkaar wilt printen, blijft de objectnaam van de 1e contractprint staan en wordt niet ververst.

**Comment by LindaVels** [comment]
@MirellW Zou je kunnen aangeven wat precies de handelingen zijn om dit te reproduceren.

**Comment by MirellW** [comment]
Bestanden Contracten 
Filter District Noard en Contractsoort LBR1
Wanneer je een willekeurig ander contract in de voorbeeldlijst selecteert, blijft de objectnaam van het eerste contractnr in de printlayout staan.
Wanneer je filtert op beheerregio dan wordt standaard bij de objectnaam de beheerregionaam ingevuld ipv de objectnaam

**Comment by LindaVels** [comment]
Het vullen van de variabelen in de printlijst gebeurt vanuit CRS2, @ejmeulenkamp kun jij hier naar kijken

**Comment by LindaVels** [comment]
![image001](https://cloud.githubusercontent.com/assets/9080474/13629355/e4a9c7fe-e5d8-11e5-842a-66aafd5c74b3.jpg)

**Comment by ejmeulenkamp** [comment]
In versie 2.00.06 op de acceptatieserver is de fout opgelost. Als een contract nu op meerdere objecten valt, dan worden zelfs alle objecten vermeld, gescheiden door een komma.
@MirellW : Zou je even willen testen op de acceptatieserver of e.e.a. nu goed werkt?

**Comment by MirellW** [comment]
Hallo Evert Jan,

Ik heb het getest en het werkt nu wel goed volgens mij.

Groet Mirella


Mirella Wielenga
Specialist Informatiesystemen
It Fryske Gea

0512 - 30 58 65 (rechtstreeks)
06 - 29 59 16 21
(aanwezig op ma t/m do)

[Beschrijving: C:\Users\binne.IFG\Desktop\Email handtekening\Achtergrond e-mail opmaak def\achtergrond_emailopmaak_ifg(2).jpg]

Van: Evert Jan Meulenkamp [mailto:notifications@github.com]
Verzonden: 10-03-2016 15:55
Aan: IDgis/CRS2
CC: Mirella Wielenga
Onderwerp: Re: [CRS2] fout in bijwerken objectnaam meerdere prints achter elkaar (#157)


In versie 2.00.06 op de acceptatieserver is de fout opgelost. Als een contract nu op meerdere objecten valt, dan worden zelfs alle objecten vermeld, gescheiden door een komma.
@MirellW<https://github.com/MirellW> : Zou je even willen testen op de acceptatieserver of e.e.a. nu goed werkt?

**Comment by ejmeulenkamp** [comment]
Volgens mij werkt het nu goed, dus dan is er weer een issue opgelost.
