### ISSUE TITLE
Rode lijstsoorten exporteren

### ISSUE THREAD

**Issue by HZLWannes** [IDgis/CRS2#159]
Beste Evert-Jan,

Ten behoeve van beheerplannen of anderszins het in beeld brengen van waarden van een gebied, presenteren wij vaak de voorkomende rode lijstsoorten en hun status. 
De selectie van alle rode lijstvoorkomende soorten lukt in crs prima. Dan krijg je de lijst met allewaargenomen soorten (binnen die selectie) die op de rode lijst staan. Maar binnen crs is daar nog geen status in zichtbaar. Deze is wel in het stambestand rode lijstsoorten aanwezig. Als ik van de selectie een export (printertje) maak, kan ik kiezen voor 'soorten per regeling'. **Niet ** alle soorten, die wel in de selectie voorkomen, komen dan mee in de export. 

Mocht je het willen testen kun je als selectie "wallen van retranchement" en regeling "rode lijst" kiezen.

Groet, Wannes

**Comment by ejmeulenkamp** [comment]
Kun je ontdekken welke soorten niet meekomen in de export? Zijn het misschien soorten die niet gekoppeld zijn aan een object? Of soorten waarvan het aantal 0 is?
Begrijp ik het goed dat je in het overzicht ook de status wilt zien?

**Comment by HZLWannes** [comment]
Analytisch zeer scherpe vraag!! Haha. Het heeft inderdaad te maken met het aantal dat op 0 staat. Maar er staat wel een abundantie ingevuld dus de soort is wel aanwezig, 
De status (categorie) hoeft niet zichtbaar in crs, maar ik geef er mee aan dat de export erg cruciaal is, om de info zichtbaar te maken.

**Comment by ejmeulenkamp** [comment]
Begrijp ik het nu goed dat als er een abundantie ingevuld is, de soort toch opgenomen moet worden in het overzicht? Zo ja, wat vul ik dan bij aantal in?

**Comment by HZLWannes** [comment]
Dag Evert-Jan Dat maakt mij eigenlijk niet zo veel uit. 0 laten staan is prima. Nog mooier zou zijn tekst, een 'x' bijvoorbeeld.

**Comment by ejmeulenkamp** [comment]
Ik had dit al aangepast in de programmacode. Soorten waarvan het aantal 0 is komen nu ook mee. Een 'x' afdrukken in het overzicht levert een rare situatie op omdat alle getallen dan rechts uitgelijnd worden en de 'x' links. Dat lijkt me niet wenselijk.
Ik kan binnenkort wel een update in jullie testomgeving plaatsen, zodat jullie kunnen kijken of het nu wel goed werkt. Oké?

**Comment by ejmeulenkamp** [comment]
Is dit issue nu opgelost?

**Comment by HZLWannes** [comment]
Ja deze is opgelost.
