### ISSUE TITLE
uitgevinkte kaartlaag blijft in beeld 2

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#16]
tabblad afdelingen, transacties in legenda aangezet. Ik zie niet de transacties in beeld, maar de afdelingen kaart.
Allereerst blijft het beeld (de afdelingen) wazig. De topkaart is wel scherp. 
Nadat de laag transacties is uitgezet, de laag afdelingen aan, zijn de afdelingsgrenzen scherp in beeld. Afdelingen weer uitgezet en de laag transacties aangezet (waar je dus de afdelingen in beeld krijgt). Deze was nu wel scherp.
In de laag transacties kun je vervolgens aankopen en verkopen aanvinken. De een is blauw met rode rand, de ander roze met rode rand. Beide komen echter in beeld gelijk de afdelingen. Als je Transacties-Aankopen aanzet krijg je de afdelingen in beeld. Zet ik vervolgens de hoofdmap Transacties uit, dan blijft het beeld hetzelfde. Pas als ook de daaronder liggende laag Aankopen wordt uitgevinkt verdwijnt de laag uit beeld.

**Comment by LimburgsLandschapHarry** [comment]
Het in beeld blijven van lagen die onder een andere laag /map zitten geldt ook voor bijvoorbeeld de laag Percelen.

**Comment by LindaVels** [comment]
Vanochtend heb ik een nieuwe versie van de services (en cs config) neergezet. Dit lost ws bovenbeschreven probleem op. @Harry: Zou je nogmaals kunnen testen en kijken of de problemen nog bestaan?

**Comment by LimburgsLandschapHarry** [comment]
Ik krijg de juiste lagen in beeld, en het is niet meer eerst wazig. Probleem is wat dat betreft opgelost.
> Vreemd is wel dat bij het openen van de laag transacties-aankopen, eerst de laag verschijnt die het laatst openstond, deze direct weer verdwijnt en dan de juiste laag wordt getoond. Dit geldt voor alle keren dat ik een laag uitzet en een andere laag aanzet. Het lijkt erop dat ie eerst het oude beeld uit het geheugen oproept om vervolgens de aanpassingen te maken door de nieuwe laag in beeld te brengen.
> ander punt van aandacht dat nog niet is opgelost: Onder transacties staat aankopen en verkopen. Ik kan deze aanvinken en krijg dan het bijbehorende beeld. Echter de hoofdlaag Transacties staat niet aan. Beeld zou dus eigenlijk leeg moeten blijven.
![capture2](https://cloud.githubusercontent.com/assets/10415606/5660579/1ba8c770-9722-11e4-87ed-f713679f4451.JPG)

**Comment by LimburgsLandschapHarry** [comment]
nog een voorbeeld: in het tabblad objecten selectie van perceel Acn a 5672. Verschijnt netjes in beeld. Als ik alle lagen uitzet, blijt er een laag in beeld. Dit is niet de afdelingen laag en ook niet de kad laag. Zie printscr.
![capture](https://cloud.githubusercontent.com/assets/10415606/5660772/62dd47ae-9724-11e4-8d77-ce676d93fe9f.JPG)

**Comment by LimburgsLandschapHarry** [comment]
Ik ben erachter. Het is de transactielaag waar onder de uitgevinkte hoofdmap de submappen nog wel aanstaan. Probleem zal zich dus oplossen als eerstgenoemde lagen probleem is opgelost.

**Comment by LindaVels** [comment]
De legenda werkt nu nog niet logisch: uit- of aanvinken op een hoger niveau zou moeten resulteren in het aan-/uitvinken op een lager niveau in de legenda. Dit zal worden verbeterd in toekomstige versies van de viewer.
