### ISSUE TITLE
koppelen van afdelingen aan contracten

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#160]
Bij het koppelen van meerdere afdelingen die verspreid liggen over een grote oppervlakte werkt het koppelen van afdelingen aan het contract absoluut niet prettig of handig.  Onhandigheden zijn: Als ik op 1 object percelen koppel gaat het de eerste keer prima. Als ik vervolgens percelen van een ander object wil koppelen zoomt de kaart eerst in naar de reeds gekoppelde percelen. Ik moet dan uitzoomen of pannen naar de volgende percelen die ik wil koppelen. Vervolgens moet ik de select punt weer actief maken. Als ik dan percelen wil toevoegen druk ik [shift] in en selecteer de volgende percelen. Echter dan zijn de reeds geselecteerde percelen toch niet standaard geselecteerd en moet ik voor elk reeds geselecteerd perceel aangeven of ik het wel of niet wil houden in het contract. Daarna (als voorgaande al is gelukt) wil ik nog meer percelen koppelen. Moet ik echter op bewaren drukken, wat heel snel vergeten wordt. Kortom, geen handige makkelijk werkende workflow.

**Comment by ejmeulenkamp** [comment]
Welke versie van de viewer heb je? Je kunt het versienummer oproepen via het meest rechtse knop in de knoppenbalk van de viewer.

**Comment by LimburgsLandschapHarry** [comment]
versie: 1.0.1

**Comment by LindaVels** [comment]
Dit is inderdaad nog een oudere versie waarin dit probleem nog niet opgelost is.

**Comment by LimburgsLandschapHarry** [comment]
kunnen jullie op afstand de versie updaten? Ik ben namelijk met een contract van 1200 ha bezig en dat werkt nu niet erg soepel.
