### ISSUE TITLE
crs-live-contracten

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#164]
Bij het koppelen van afdelingen aan een contract krijg ik een verkeerd geselecteerd perceel niet gedeselecteerd. Gevolg is dat ik het proces moet afbreken. Wat ook niet echt makkelijk gaat.
 
Verder valt me op dat het infoschermpje niet meer verschijnt. Bewuste keuze? Wat ontbreekt is de aanwijzing hoe je percelen kunt toevoegen / verwijderen met de shift of control toets.

**Comment by ejmeulenkamp** [comment]
Als je versie 1.0.4 of hoger van de viewer hebt, dan zou het koppelen van afdelingen aan een contract soepel moeten verlopen. Welke versie van de viewer heb je?

Het weglaten van het infovenstertje is een proefje. Er kwamen wel heel veel meldingen voordat je iets kon gaan koppelen. Ik kan het wel weer inschakelen of inschakelbaar maken via de opties. Heb je een voorkeur?

**Comment by LimburgsLandschapHarry** [comment]
het koppelen werkt inderdaad beter. Echter als ik meerdere percelen achter elkaar koppel in 1 sessie, en ik klik per ongeluk een verkeerd perceel aan, dan krijg ik in die sessie het verkeerd geselecteerde perceel niet meer ongedaan gemaakt. Ik moet dan dus of het perceel eerst toevoegen en later weer verwijderen, of de toevoegsessie afbreken door rechtsonder op sluiten te drukken. Normalerwijze is het één keer klikken is selecteren, nog een keer klikken is de-selecteren.

Wat betreft het infovenster: inderdaad veel info, en extra klikken. Enerzijds handig om te weten welke functies er in zitten, anderzijds irritant als je veel moet klikken en steeds dezelfde mededeling krijgt. Weglaten lijkt me dan toch beter. Staat de instructie wel onder de help knop?

**Comment by ejmeulenkamp** [comment]
Ja, de instructie staat in de help-functie.

**Comment by LimburgsLandschapHarry** [comment]
instructie onder de help. 
De-selecteer probleem staat ook in een nog openstaande issue.
Daarom: over en sluiten voor deze melding.
