### ISSUE TITLE
opdracht kaartbeeld SLL: PDOK laag kadastrale percelen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#167]
De pdok laag die is ingevoegd bevat wel de percelen, maar niet de nummers. ER zijn twee lagen kadastrale percelen.
![image](https://cloud.githubusercontent.com/assets/10415606/15388907/901e2a86-1db4-11e6-8b81-9b68ee16807a.png)
 in dit geval is de bovenste geselecteerd, terwijl de onderste de perceelsnummers er bij staan. Graag aanpassen.

**Comment by LindaVels** [comment]
gewijzigd
@LimburgsLandschapHarry : graag testen

**Comment by LimburgsLandschapHarry** [comment]
kaartlaag is goed. Ik neem aan dat de instelling wanneer de labels zichtbaar worden geregeld is in de PDOK feed, en niet door jou zijn ingesteld?
