### ISSUE TITLE
opdracht kaartbeeld SLL: lagen aan en uit

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#169]
In mijn overzicht heb ik aangegeven dat in het tabblad afdelingen de lagen puntelementen, lijnelementen en afdelingen standaard aangezet konden worden.
Bij nader inzien graag punten en lijnen standaard uit zettten.
Bij het tabblad elementen wel aan laten staan.

**Comment by LindaVels** [comment]
gewijzigd
@LimburgsLandschapHarry : graag testen

**Comment by LimburgsLandschapHarry** [comment]
bijna prima. Viel me op dat de kadasterlaag er onder aan staat, dat was niet de bedoeling. Die mag uit. Alleen afdelingen aan.

**Comment by LindaVels** [comment]
Percelen ook uit
@LimburgsLandschapHarry : testen

**Comment by LimburgsLandschapHarry** [comment]
prima
