### ISSUE TITLE
niet werkende Admin functies 

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#17]
Inlog historie geeft niet weer dat ik vandaag verschillende keren ingelogd blijft.
Nu ingelogd> melding: Het gevraagde formulier kan niet geladen worden.

**Comment by ejmeulenkamp** [comment]
Ik heb iets aangepast waardoor de inloghistorie nu wel werkt.
Aan het onderdeel "Nu ingelogd" wordt nog gewerkt.

**Comment by LimburgsLandschapHarry** [comment]
Inloghistorie wordt nu opgeslagen, echter toont pas als ik op de knop verversen heb gedrukt. Als ik het scherm inloghistorie opvraag is die in eerste instantie leeg. Zou de historie van dat moment moeten bevatten.

**Comment by ejmeulenkamp** [comment]
Dit heeft altijd al zo gewerkt. De reden is dat gegevens ophalen zoveel mogelijk beperkt wordt, omdat dit ten koste kan gaan van de snelheid ook in andere vensters.

**Comment by LimburgsLandschapHarry** [comment]
ok, gewoon houden zo dus. kun je meteen zien hoe vaak ik die functie gebruik als ik niet aan het testen ben.

**Comment by ejmeulenkamp** [comment]
Volgens mij werkt het venster 'Nu ingelogd' nu ook. Kan iemand dit nog eens testen?

**Comment by LimburgsLandschapHarry** [comment]
Hoi Evert Jan,
net getest. Ik krijg 0 ingelogde gebruikers en geen naam in het scherm.

**Comment by ejmeulenkamp** [comment]
Hoi Harry,

Ik heb per ongeluk Milestone 1.06.07 gekoppeld aan dit issue. De oplossing van dit issue zal pas vanaf milestone (=versie) 1.06.08 werken. Wil je het dan nog een keertje weer proberen?

**Comment by LimburgsLandschapHarry** [comment]
net getest in 1.06.08, nog steeds geen info bij [nu ingelogd]

**Comment by ejmeulenkamp** [comment]
Nu ingelogd geeft nu het aantal ingelogde gebruikers.
