### ISSUE TITLE
opdracht kaartbeeld SLL: pdok kaartlagen recreatie

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#170]
De pdok lagen zijn onderverdeeld in topografie en recreatie.
Onder deze hoofdindeling kun je diverse lagen aan of uit zetten. De hoofdindeling Topografie staat standaard aan met BRT kaart aan. De Recreatielaag staat standaard uit. Graag de hoofdindeling recreatie standaard aan zetten. De sublagen standaard uit laten staan. Als je dan vervolgens kiest voor  een recreatielaag aanzetten krijg je hem tenminste ook in één klik in beeld. In plaats dat je en de laag en de hoofdindeling aan moet zetten.

**Comment by LindaVels** [comment]
gewijzigd

@LimburgsLandschapHarry : graag testen

**Comment by LimburgsLandschapHarry** [comment]
prima.
