### ISSUE TITLE
opdracht kaartbeeld SLL: labels

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#171]
De labels zijn niet altijd even goed leesbaar. In afdelingen wordt op de roze ondergrond een label geplaatst van het afdelingsnummer. Afhankelijk van de schaal is het label groter, maar korrelig. Of bij een gedetailleerdere schaal klein en scherp, maar doordat ie te klein is bijna onleesbaar. 
Ik denk dat hier enig ge-experimenteer van jou noodzakelijk is om een juiste labelgrootte te vinden bij gekozen kaartschaal. Eventueel leesbaar gemaakt door een ander lettertype of vet te gebruiken.

**Comment by LindaVels** [comment]
@LimburgsLandschapHarry : graag testen

**Comment by LimburgsLandschapHarry** [comment]
labels zijn duidelijk. Het viel me bij verder testen op dat de labels van de andere lagen er wel duidelijk uit zien. Die zijn echter niet aangepast. Had je daar een andere lettergrootte of -type gehanteerd. Als dat zo is zou je dat lettertype/grootte ook mogen gebruiken voor de afdelingen. Laat maar weten.

**Comment by LindaVels** [comment]
Het enige verschil met de labels van andere lagen was de kleur: grijs voor afdelingen en zwart voor de overige lagen. Ik heb de afdelingen label configuratie exact gelijk gemaakt aan de andere label configuraties.
@LimburgsLandschapHarry : testen

**Comment by LimburgsLandschapHarry** [comment]
prima zo, komt allemaal duidelijk over.
