### ISSUE TITLE
opdracht kaartbeeld SLL: print

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#172]
Print van kaart is bijna goed. Is het mogelijk om de schaalbalk, notities, en kader met stempel en tekst nog iets lager op de pagina te zetten. Nu heb ik bij het uitprinten boven en rechts 10mm marge. links heb ik 11mm marge. Onder heb ik echter 25 mm marge. Kun je kijken hoever dit minder kan.

**Comment by LindaVels** [comment]
Ik heb bij de template A4-staand het stempel iets lager geplaatst. Het is echter lastig om de marges precies gelijk te krijgen. Het maakt bijvoorbeeld uit of je niet of wel een titel invult. Ik wil in elk geval voorkomen dat dingen van de pagina "vallen".

**Comment by LindaVels** [comment]
@LimburgsLandschapHarry: graag testen

**Comment by LimburgsLandschapHarry** [comment]
Marges zijn prima zo. Dank.
