### ISSUE TITLE
opdracht kaartbeeld SLL: print logo

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#173]
Het logo van SLL (vogeltje en tekst) is nu erg korrelig. Wat moet ik aanleveren om dat strak te krijgen?

**Comment by LindaVels** [comment]
Kun je me een png aanleveren. De afmetingen maakt niet zoveel uit, maar liever groter dan de uiteindelijke afmeting op de print zodat je niet de pixels te zien krijgt.

**Comment by LindaVels** [comment]
Aanleveren hoeft niet meer, probleem bleek veroorzaakt doordat er een resize van het logo plaatje werd gedaan omdat ik niet precies de juiste breedte en hoogte had gedfinieerd.

@LimburgsLandschapHarry : graag testen

**Comment by LimburgsLandschapHarry** [comment]
net een mailtje gestuurd met enkele formaten logo. print was nog steeds niet scherp.

**Comment by LindaVels** [comment]
Nieuwe logo (formaat jpg) gebruikt, zie acc omgeving
@LimburgsLandschapHarry : graag hertesten

**Comment by LimburgsLandschapHarry** [comment]
prima; logo is scherp. Zou je hem ook nog met de tekst kunnen uitlijnen aan de bovenzijde. Bovenzijde begint steeds op zelfde punt, ongeacht of er een object is geselecteerd (en er dus een objectnaam verschijnt) of een ondertitel is ingevuld.

**Comment by LindaVels** [comment]
logo nog iets naar boven geplaatst en plaatje van de bovenkant "getrimd" zodat het logo beter uitlijnt met de tekst.

**Comment by LimburgsLandschapHarry** [comment]
ik heb nog een testprintje gemaakt. Het logo ligt nog steeds erg laag ten opzichte van de Objectnaam. Als je geen selectie hebt, is er geen objectnaam en is het logo wel bovenaan uitgelijnd. Ik neem aan dat het logo ook met objectnaam bovenaan uitgelijnd kan worden?
![image](https://cloud.githubusercontent.com/assets/10415606/15571713/b8477e1c-233c-11e6-878c-e5ac92db7586.png)

**Comment by LindaVels** [comment]
@LimburgsLandschapHarry : En nu?

**Comment by LimburgsLandschapHarry** [comment]
niets meer aan doen ;).
