### ISSUE TITLE
opdracht kaartbeeld SLL: legenda

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#176]
De kaartlaag percelen staat in de legenda zowel bovenaan als onderaan de legenda genoemd. Graag aan de onderkant verwijderen.

![capture](https://cloud.githubusercontent.com/assets/10415606/15391131/c478c4d4-1dbf-11e6-879f-88ba709f1ee7.JPG)

**Comment by LindaVels** [comment]
bug in geoide

**Comment by LimburgsLandschapHarry** [comment]
opgelost
