### ISSUE TITLE
opdracht kaartbeeld SLL: gemeenten

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#177]
Voor het in beeld brengen van gemeenten heb ik aangegeven dat het zichtbaar maken eventueel via  de PDOK service kan. Voor deze oplossing is gekozen Echter ik zie dat daar geen gemeentenaam zichtbaar wordt. Volgens mij is er ook een gemeentelaag zichtbaar te maken vanuit de CRS lagen. Klopt dat? En kan dat wel met de gemeentenaam erbij? Dan graag in voldoende lettergrootte (voorstel in opdracht was ergens tussen 28 en 34.

**Comment by LindaVels** [comment]
Nadeel van gebruik van de gemeente CRS laag is dat deze niet automatisch up-to-date wordt gehouden. Voordeel is inderdaad dat er een gemeentenaam kan worden getoond. Moet de gemeentenaam altijd zichtbaar zijn?

**Comment by LimburgsLandschapHarry** [comment]
denk dat het toch handiger is de pdok te gebruiken, zonder gemeentenaam. Dus laten zoals het is.
