### ISSUE TITLE
CRS2 Live versie 2.00.08: kaart

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#178]
De kaart wordt nu geprint met logo van ID gis.  
Het logo IDGis wordt op een tweede pagina geprint. Graag logo SLL weer terug zetten, passend op 1 pagina. Zie verder ook mijn eerdere opmerking vandaag over de marges in de print (grote ondermarge).

**Comment by LindaVels** [comment]
Zodra de nieuwe configuratie op de server in Limburg staat is dit opgelost

**Comment by LimburgsLandschapHarry** [comment]
opgelost.
