### ISSUE TITLE
opdracht kaartbeeld SLL: print stempel

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#179]
als er een selectie van een object wordt gemaakt staat keurig het object in de titel in de stempel. Als er een selectie van bv NSW = J wordt gemaakt. verwacht ik als titel NSW landgoed (of iets dergelijks). Echter ook dan is de titel in de stempel een Objectnaam. En wel het eerste object dat in de lijst op het linker deel van het scherm staat (bij selectie NSW = J, is dat Rode Hoek). Het kaartbeeld geeft dan echter heel Limburg met diverse NSW landgoederen. Kan de titel aangepast worden naar de uitgevoerde selectie.

**Comment by LindaVels** [comment]
De titel variabele wordt door CRS2 gevuld niet door Geoide. Dit is dan ook een issue voor @ejmeulenkamp

**Comment by ejmeulenkamp** [comment]
De titel wordt standaard gevuld met de naam van één van de geselecteerde objecten of (in de laatste versie van CRS2) met de namen van alle geselecteerde objecten. Als je iets anders wilt vermelden in het stempel, dan kun je de door het CRS ingevulde gegevens overschrijven met eigen tekst vlak voordat je het kaartje gaat afdrukken. Kun je hier mee verder?

**Comment by LimburgsLandschapHarry** [comment]
voorlopig kan ik hier mee verder. Kan de titel ook bestaan uit de naam van de selectie?

**Comment by ejmeulenkamp** [comment]
Bij opnieuw lezen van mijn vorige antwoord zie ik dat ik eigenlijk niet helemaal goed geantwoord heb. De titel is een veld dat je altijd zelf in moet/mag vullen. In het veld 'Objectnaam' worden de objectgegevens (zoals in mijn eerdere antwoord vermeld) door CRS ingevuld. 
Wat bedoel je met 'de naam van de selectie'?

**Comment by LimburgsLandschapHarry** [comment]
Ik zie bij het maken van de print dat in het invulschermpje inderdaad achter de variabele 'objectnaam' het object wordt ingevuld. Logisch dus, als je het invulschermpje er bij hebt. Op de print staan de namen van de variabelen / velden er niet meer op, maar alleen hetgeen is ingevuld. In dit geval dus objectnaam. 
Wat ik echter heb gedaan is een selectie gemaakt van een beheertype [kruiden en faunarijk grasland]. Dan krijg je een overzichtskaart waar dit beheertype ligt in diverse objecten. Vervolgens staat er op de overzichtskaart als zijnde de titel van de kaart [rode hoek] vetgedrukt. M.i. zou daar dan het [beheertype] als titel van de kaart moeten staan. 
Ik realiseer me dat het stempel er niet fraaier op wordt. Als je bijvoorbeeld 'rode hoek' selecteert krijg je selectie = rode hoek; object = rode hoek. Ziet er ook niet logisch uit.
Dus weer terug naar de oorsprong: objectnaam / namen vet. In het invulscherm zelf achter titel invullen 'selectie is kruiden en faunarijk grasland'.
