### ISSUE TITLE
gebruikte internetsnelheid server

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#18]
De Gis Viewer in deze CRS versie is volledig webbased. Ik ga er van uit dat er dus (heel wat) info over het internet verzonden moet worden om CRS te draaien. 
De op de server gebruikte snelheid is erg hoog. Functioneert e.e.a. ook als CRS lokaal staat en door een tragere internetverbinding de data of viewer opgehaald moet worden.

**Comment by HermanAssink** [comment]
Hoewel de viewer web-based is, is al het verkeer intern op de server. Alleen de verbinding voor het extern bureaublad / terminal server (TS) loopt via het internet. Of dezelfde snelheid straks ook met de servers van de CRS2 organisaties ervaren wordt, hangt in hoofdlijnen af van twee factoren, namelijk de verbindingssnelheid tussen de TS client en TS server en de snelheid / capaciteit van de server(s). De testserver die alleen voor de CRS2 test wordt gebruikt, heeft de volgende specificaties: Intel i7-4770 Quad-Core CPU, 32 GB RAM en SATA schijven. Deze server is met een gegarandeerde bandbreedte van 200 MBit/s op het internet aangesloten.

**Comment by LimburgsLandschapHarry** [comment]
Ik weet niet wat onze server kan, maar de snelheden / specificaties die omschreven worden zal onze server ook wel halen (wordt nagevraagd bij netwerkbeheerder). Als ik het goed begrijp is het wederom alleen maar de beeldschermopbouw, toetsenbordaanslagen en muisbewegingen die over het internet heen moet. De rest loopt intern. Klopt dat?

Ik heb nog wel vragen bij het kaartmateriaal dat van internet gehaald wordt. De opbouw daarvan zal wel afhankelijk zijn van de internetsnelheid neem ik aan?
