### ISSUE TITLE
Afdelingen kaart niet meer zichtbaar in CRS

### ISSUE THREAD

**Issue by MirellW** [IDgis/CRS2#182]
CRS heeft momenteel geen koppeling meer met de afdelingenkaart. Kan dat kloppen=

**Comment by LindaVels** [comment]
Mirella: kan er iets zijn met de database?

**Comment by MirellW** [comment]
Volgens mij is er niets mis met de database, ook de ArcGIS plugin werkt naar behoren.

**Comment by LindaVels** [comment]
Mirella: kun je de crs-geoide service herstarten en mij de log files uit het mapje geoide-crs\crs-geoide-x.x.x\logs kunnen sturen?

**Comment by MirellW** [comment]
Heb service herstart en logs opgestuurd.
Probleem is opgelost
