### ISSUE TITLE
kaartopdracht sll: volgorde lagen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#183]
Viel me op dat de volgorde van de PDOK kaarten is aangepast. Graag weer in volgorde zetten zoals in opdracht omschreven.

**Comment by LindaVels** [comment]
Er zit een bug in Geoide waardoor de volgorde binnen groepslagen (dus niet op het hoofdniveau maar daaronder) omgekeerd in de legenda worden getoond. De volgorde in de kaart is (neem ik aan) wel goed. Probleem is al wel onderkend en opgelost, alleen er is nog geen nieuwe versie van de programmatuur uitgerold. 
@LimburgsLandschapHarry : zou je kunnen kijken of de volgorde in de kaart (de stapeling) inderdaad goed is?

**Comment by LimburgsLandschapHarry** [comment]
in de kaart is de volgorde inderdaad goed. Ik laat deze nog even open staan tot een volgende versie is geïnstalleerd.

**Comment by LindaVels** [comment]
OP de acceptatie omgeving staat een nu een versie waarbij ook de volgorde in de legenda juist is.
@LimburgsLandschapHarry: testen graag

**Comment by LimburgsLandschapHarry** [comment]
legenda en volgorde in kaart stemmen met elkaar overeen. Prima.
