### ISSUE TITLE
opdracht kaartbeeld SLL: print verschuiving

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#184]
Bij een selectie wordt keurig ingezoomd op de geselecteerde percelen. Echter als ik daar een print van maak verschuiven de percelen ten opzichte van de topografische ondergrond. Ook is de schaal van ondergrond en percelen afwijkend. Dit is me niet eerder opgevallen. Bij een oude print van vanmorgen was dat niet het geval. Bij de nieuwere prints wel. Wellicht heeft het wat te maken met de schaalvastheid, want alle prints met een niet afgeronde schaal liggen topografie en percelen niet correct.

**Comment by LindaVels** [comment]
De functionaliteit voor het niet schaalvast printen blijkt nog niet te werken. Dit is ook niet snel te realiseren. Ik wil deze issue dan ook als wens behandelen.
Wel is het mogelijk door het "spelen" met de schaal en de grootte van het scherm het printgebied te beïnvloeden.

**Comment by LimburgsLandschapHarry** [comment]
Hiervoor geldt het zelfde als voor #181. Dit zou moeten werken en is geen wens maar tzt op te lossen.

**Comment by LindaVels** [comment]
Na onderzoek (door Evert-Jan) blijkt dat dit ook nooit zo heeft gewerkt in de "oude" viewer

**Comment by LimburgsLandschapHarry** [comment]
Akkoord. schaalvast printen opnemen als wens. 
Blijft staan de eerste opmerking van deze issue. 
Bij inzoomen op de kaart liggen de CRS lagen keurig op de onderliggende topo ondergrond. Echter als ik daar een print van maak verschuiven de percelen ten opzichte van de topografische ondergrond. Graag oplossen.

**Comment by LindaVels** [comment]
@LimburgsLandschapHarry De viewer werkt met schaalvast printen. Dit was ook het geval met de oude viewer. Bij het schaalvast printen verschuiven de lagen in de viewer niet tov elkaar.
