### ISSUE TITLE
opdracht kaartbeeld SLL: print stempel onvolledige tekst

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#185]
als ik het stempel invul bij de variabele 'titel' valt soms een deel van de tekst weg. Bij invulling:
[selectie = droge hei] blijft alleen de tekst [selectie] staan. Alles achter [=] valt weg.
Ik heb dit ook nog geprobeerd met +, -, \, :. Die gaan allemaal goed. Alleen = vreet ie niet.

**Comment by LindaVels** [comment]
Kennelijk wordt er iets met "=" gedaan in de programmatuur. @LimburgsLandschapHarry : Is het een groot bezwaar om de = niet te kunnen gebruiken?

**Comment by LimburgsLandschapHarry** [comment]
Nee, moeten we ook zo mee verder kunnen. Wel een onhebbelijkheidje.
