### ISSUE TITLE
BRK test

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#186]
Ik wil de werking van BRK gaan testen. Dit dient uitgevoerd te worden op de lokale testomgeving.
Het eerste dat ik opzoek bij de module Kad.Objecten is welke belemmeringen er op een perceel kunnen rusten. Daartoe kan geselecteerd worden op Subject, Recht, Rechtbelem. en ObjectBelem. In Subject krijg ik een redelijke lijst van andere personen die bij een perceel betrokken zijn. Sommige staan er meerdere keren in. Klopt dat?
In Subject verwacht ik onder andere Waterleidingmaatschappij Limburg en De Staat Defensie. Deze staan er niet in.
Onder Recht, staat alleen recht van eigendom. Moet daar ook niet erfpacht bij staan?
Onder RechtBelemmering staan maar 3 mogelijkheden.
Onder ObjectBelemmering staan 11 mogelijkheden.
Ik heb het idee dat de lijst niet volledig is.

Graag contact (donderdag, reeds telefonisch doorgegeven) hierover.

**Comment by HermanAssink** [comment]
@LimburgsLandschapHarry Over welk perceel gaat het, wie heeft volgens jou welke rechten en welke object- en rechtbelemmeringen gelden er volgens jou op dit perceel? Zonder deze informatie is jouw melding door ons niet na te trekken. @ejmeulenkamp Heb jij nog andere suggesties?

**Comment by ejmeulenkamp** [comment]
Ik zal (eventueel samen met Mart) onderzoeken of er iets niet goed gaat in CRS2, in de BRK-views of dat er daadwerkelijk te weinig gegevens (bijvoorbeeld zakelijke rechten) in de BRK-database zitten.

**Comment by NijzinkM** [comment]
BRK2DB is geüpdate en de problemen met rechten en rechtbelemmeringen zouden nu opgelost moeten zijn.

**Comment by LimburgsLandschapHarry** [comment]
Dank voor de update. De gegevens lijken volledig. Nog wel enkele puntjes.
1. Na wat testen komt de kadastrale kaart niet meer in beeld. Afsluiten en opnieuw opstarten van de testversie werkt niet om kaart weer in beeld te brengen. ER komt überhaupt niets anders in beeld dan alleen de ondergrond. Geen andere lagen.
2. bij selectie op Subject zijn er diverse namen die na dubbelklikken de melding geven <geen gegevens gevonden die overeenkomen met de gestelde criteria>. Vreemd. Waarom staan ze er dan wel in?

Als de kaarten weer werken kan ik verder met testen.

**Comment by HermanAssink** [comment]
Harry, de service is herstart waardoor de kaarten weer werken. We zullen de achterliggende oorzaak nagaan.

**Comment by LimburgsLandschapHarry** [comment]
In vorig bericht is deze melding niet goed doorgekomen, nu de volledige zin:
2. bij selectie op Subject zijn er diverse namen die na dubbelklikken de melding geven [geen gegevens gevonden die overeenkomen met de gestelde criteria]. Vreemd. Waarom staan ze er dan wel in?

**Comment by LimburgsLandschapHarry** [comment]
selectie ObjectBelem. Besluit op basis van Monumentenwet 1988. Perceel Arcen en Velden A 01372. Is eigendom volgens tabblad details. Echter met Select Huidige wordt niet ingezoomd op het perceel. Melding dat perceel niet is gevonden (wellicht zelfde als hierboven, niet te achterhalen nu want de kaart is weer gecrasht.) Melding kwam voor de crash. Daarna lijkt ie het niet meer te doen.

Graag kaart weer resetten.

**Comment by LindaVels** [comment]
Er was een probleem met de locatie van de plaatjes voor de legenda, dit gaf veel foutmeldingen in de log. Ik heb dit opgelost en vervolgens de service herstart. Ik houd in de gaten of de service nu stabiel blijft.

**Comment by LimburgsLandschapHarry** [comment]
Er staan in de pull down menus van de 4 BRK selectievelden diverse namen / categorien die vervolgens niet in de percelen voor blijken te komen met de melding  [geen gegevens gevonden die overeenkomen met de gestelde criteria]. Dit lijkt me niet logisch. Is daar een verklaring voor?

**Comment by LimburgsLandschapHarry** [comment]
bij REchtBelemmering kies ik voor Koop of Voorovereenkomst. Hier zitten 5 percelen in. als ik 1 van die percelen aanklik en Select Huidige klik, wordt keurig ingezoomd op het betreffende perceel. Bij Select Alle verwacht ik dat ingezoomd wordt op alle percelen. Dat werkt niet. De kaart bouwt zelfs niet meer op. Lijkt erop dat dit een oorzaak is dat de service herstart moet worden.
Dit was even mijn laatste post, ben nu een weekje met vakantie. Succes met alles.

**Comment by ejmeulenkamp** [comment]
@LindaVels 
Werkt de testversie van Limburg met de legendaveld-uitbreiding? In dat geval moet het bestandje "MetLegenda.txt" in de map |Meulenkamp\CRS2SqlTest aanwezig zijn.
Ik heb het er nu even ingezet. Als de versie zonder legendaveld-uitbreiding werkt, dan moet het tekstbestandje weggehaald worden.
Kan dat de oorzaak zijn van de problemen?

**Comment by ejmeulenkamp** [comment]
@LimburgsLandschapHarry 
Ik heb voor je vraag:
_Er staan in de pull down menus van de 4 BRK selectievelden diverse namen / categorien die vervolgens niet in de percelen voor blijken te komen met de melding [geen gegevens gevonden die overeenkomen met de gestelde criteria]. Dit lijkt me niet logisch. Is daar een verklaring voor?_
een nieuw issue aangemaakt.

**Comment by LindaVels** [comment]
Vandaag de nieuwe versie (1.0.7 gelijk aan die op de acc omgeving op test.crs2.nl) en de nieuwe configuratie op de test omgeving bij Limburg geïnstalleerd. Ik heb een aantal keren achter elkaar selecties gemaakt in de module Kad objecten. De applicatie bleef in de lucht.
@LimburgsLandschapHarry: Zou jij nog eens kunnen testen?

**Comment by LimburgsLandschapHarry** [comment]
Linda,

ik heb op de lokale testomgeving versie V2.01.01. Ik heb in de externe testomgeving V2.01.00.
Jouw vorige post over versie 1.0.7 kan ik dus niet plaatsen.

**Comment by LimburgsLandschapHarry** [comment]
bij selectie op Subject zijn er diverse namen die na dubbelklikken de melding geven [geen gegevens gevonden die overeenkomen met de gestelde criteria]. Vreemd. Waarom staan ze er dan wel in?
De eerste naam onder Subject die ik vind is: Achten, Hendrina. Als ik deze selecteer en vervolgens Toon Selectie kies, krijg is de bovenstaande melding tussen [ ]. Wat is hier de reden voor.

**Comment by LimburgsLandschapHarry** [comment]
sorry, vorige naar nieuwe issue door Evert Jan aangemaakt.

**Comment by LimburgsLandschapHarry** [comment]
bij REchtBelemmering kies ik voor Koop of Voorovereenkomst. Hier zitten 5 percelen in. als ik 1 van die percelen aanklik en Select Huidige klik, wordt keurig ingezoomd op het betreffende perceel. Bij Select Alle verwacht ik dat ingezoomd wordt op alle percelen. Dat werkt niet. De kaart bouwt zelfs niet meer op. Lijkt erop dat dit een oorzaak is dat de service herstart moet worden.

Dit is gelijk aan mijn eerdere melding. Fout blijft bestaan.

**Comment by LindaVels** [comment]
@LimburgsLandschapHarry Het eerder genoemde versie nummer (1.0.7) slaat op het versie nummer van de viewer en niet op de versie van CRS2. Het versie nummer van de viewer kun je oproepen mbv het groen "IDgis-knopje".

**Comment by ejmeulenkamp** [comment]
Ik heb onderzocht wat er gebeurt als er kad.objecten geselecteerd worden via de selectie op Rechtbelemmering. De select-statements met een kort verhaaltje zal ik in een separaat mailtje toesturen naar Linda.

In het kort komt het er op neer dat bij een 'gewone selectie' (via gemeente of sectie of contract, etc) de objecten op de kaart wel geselecteerd worden maar na een selectie via rechtbelemmering niet. Alle kad.objecten verdwijnen dan zelfs van de kaart! 
Echter de service is niet onderuit, want na een klik op de knop [Select Huidige] verschijnen de kad.objecten weer op de kaart en wordt naar het juiste (geselecteerde) kad.object ingezoomd. Je kunt afwisselend klikken op [Select Alle] en [Select Huidige] om dit gedrag te herhalen.

Ik hoop dat de select-statements in de bijlage van mijn mailtje het begin zijn van de oplossing?
