### ISSUE TITLE
printwijze vergelijking akr-crs databases

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#19]
functie AKR-LKI / vergelijken AKR-CRS uitgevoerd.
blaadjes printen netjes, kon helaas niet de lokaal geïnstalleerde pdf printer vinden. 
De bladen [kad.objecten die wel in crs voorkomen maar niet in akr] en [kad.objecten met verschil in oppervlakte crs-akr] tonen de kad gemeente Arcen en Velden. 
Het blad [kad.objecten die wel in akr voorkomen maar niet in crs] toont de kad gemeente Arcen En Velden. Met hoodletter dus. Vreemd...
Verder laat dit laatste vel na de 6de regel steeds een regel blank, waar de andere overzichten dit niet doen.

**Comment by ejmeulenkamp** [comment]
Voor het selecteren van PDF-Creator zie issue #26
In alle drie de overzichten wordt de gemeentenaam nu met hoofdletters afgedrukt.
Waarom er lege regels verschijnen wordt momenteel nog onderzocht.

**Comment by ejmeulenkamp** [comment]
De lege regels zijn nu ook weggehaald uit de tweede lijst. Werkt het nu zoals verwacht?

**Comment by LimburgsLandschapHarry** [comment]
Genoemde problemen zijn opgelost. Over en sluiten.
