### ISSUE TITLE
BRK test: perceel met veel belemmeringen testcase

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#193]
Een perceel met veel belemmeringen die prima als testcase gebruikt kan worden is:
Venlo E 559. Dit perceel is eigendom van de gemeente Venlo, in erfpacht uitgegeven aan Limburgs Landschap. Hier liggen diverse beperkingen op:
Zie hiervoor het tabblad koppelingen bij dit perceel. Diverse zakelijke rechten. Die ik in de BRK niet terug zie.

**Comment by LimburgsLandschapHarry** [comment]
ik zie in het BRK tabblad alleen relaties met de Solvay  / Solvic. In het tabblad koppelingen komt ook de dienst vastgoed defensie voor, de gemeente met een opstalrecht, en de WML met een zakelijk recht. Deze zie ik niet in het tabblad BRK. Hoe kan dat?

**Comment by NijzinkM** [comment]
Is deze issue nog actueel of is deze met de BRK-update van 15 juni verholpen?

**Comment by LimburgsLandschapHarry** [comment]
op dit moment zie ik helemaal geen beperkingen meer in het tabblad BRK. probleem is dus nog niet opgelost. Via Gwen Royakkers van Kragten is vorige week ook een mail naar Herman en Evert jan uitgegaan over een probleem dat niet alle BRK percelen beschikbaar waren om zichtbaar te maken in CRS. Als dat probleem is verholpen, draai ik de tool van Kragten opnieuw en als alle percelen er in zitten zal ik opnieuw testen of de belemmeringen op dit perceel er in staan.

**Comment by NijzinkM** [comment]
Hallo @LimburgsLandschapHarry 
Ik heb een aanpassing in de BRK-database gemaakt en volgens mij zitten alle percelen er nu in, aangezien de percelen nu het volledige bestelgebied van Limburgs Landschap dekken. Betreffende de issue met perceel Venlo E 559: in de BRK-database kan geen belemmeringen hierbij vinden, op een einddatum van een recht na. Ik kan wel de volgende rechten bij dit perceel vinden:
```
Opstalrecht Nutsvoorzieningen     N.V. Solvay
Erfpacht (recht van)              Stichting Het Limburgs Landschap
Eigendom (recht van)              Gemeente Venlo
Opstalrecht Nutsvoorzieningen     Nv Solvic
```
Ik ben benieuwd welke belemmeringen je had verwacht bij dit perceel.

**Comment by LimburgsLandschapHarry** [comment]
Hallo Mart,
het resultaat is al een stuk beter, maar nog niet compleet. Bij het draaien van de tool van Kragten worden er nu 4688 overeenkomstige percelen gevonden tussen CRS en BRK. In CRS staan 6826 unieke percelen en vóór het draaien van de tool in de FGDB 4555. Ik heb de tool gedraaid. In het beeld mis ik vervolgens toch nog enkele percelen. Twee grote zijn:
BER 01 A 3936 (deze staat in CRS2 wel als perceel in de administratieve kant ter grootte van 65.8545ha)
GNP 00 H 1261 (deze staat in CRS2 wel als perceel in de administratieve kant ter grootte van 13.5135ha).
Ik hoop dat je op basis van deze info weer verder kunt.

**Comment by NijzinkM** [comment]
Bedankt voor de gegevens. Ik ga ermee aan de slag.

**Comment by NijzinkM** [comment]
De ontbrekende percelen werden gefilterd bij het selecteren van de actuele stand van de percelen. Dit is nu opgelost en er zijn nu 120 percelen meer beschikbaar. De percelen die je hebt genoemd zijn nu ook te vinden. Missen er nog steeds percelen in het beeld?

**Comment by LimburgsLandschapHarry** [comment]
Mart,
Er ontbreken nog wel percelen, maar bij nader inzien zijn die op kaart allemaal hernummerd, of bij ons uit de administratieve kant verdwenen. Alle percelen die bij ons administratief bekend zijn staan er nu dus in. Toppie!
Ik ga er van uit dat het nu zo geprogrameerd is dat er bij een volgende update niet weer percelen verdwijnen.
Ik ga nu verder met het controleren van enkele percelen met belemmeringen (om weer terug te komen op het oorspronkelijke onderwerp van dit issue.

**Comment by LimburgsLandschapHarry** [comment]
De belemmeringen getest. De rechten die jij noemde in je post van gisteren staan er in en dat zijn ook de belemmeringen die ik verwachte.
Op enkele andere percelen staat geen belemmering.
ACN00 A 5542, terwijl op de aanliggende percelen ACN00 A 5480 / 5482, waar dezelfde leiding onder door loopt, wel een belemmering ligt. Het kan zijn dat 5542 een hernummering is waarbij het recht niet mee overgekomen is?

Daarnaast duurt het wel lang als ik in de kaart met de info button klik voordat het perceel is geselecteerd en ingezoomd en de linker zijde van het scherm het juiste perceel toont (de ene keer 10 tellen, de tweede keer 16 tellen). Klik ik vervolgens in het administratieve deel op het tabblad BRK dan ben ik weer 4 tot 5 tellen verder.

**Comment by LimburgsLandschapHarry** [comment]
Mart,
net Arcen A 5542 opgezocht bij kadaster. Ook daar geen belemmering te vinden. ligt dus niet aan inleesprogramma. Aangezien nu alle percelen ingelezen en getoond worden en de belemmeringen aanwezig zijn is dit onderdeel (mits bij de updates alle info aanwezig blijft) gereed. 
Graag even terugkoppeling over implementatie van dit onderdeel, zodat het ook gaat werken in de productieomgeving. Ik ben aanwezig t/m donderdag.

**Comment by LimburgsLandschapHarry** [comment]
Vanmorgen de productieomgeving in gebruik genomen. Zo te zien werkt alles. Dit punt dus over en sluiten.
