### ISSUE TITLE
Labels afdeling en kadastraal perceel vallen samen

### ISSUE THREAD

**Issue by gelderland** [IDgis/CRS2#194]
Bij het maken van een kaart bij een contract vallen de labels van een afdeling soms samen met labels van het kadastrale perceel. 
Dir gebeurt wanneer een afdeling exact samenvalt met het onderliggende kadastrale perceel. Gevolg is uiteraard dat de labels onleesbaar worden.
[16206 labels vallen samen.pdf](https://github.com/IDgis/CRS2/files/286164/16206.labels.vallen.samen.pdf)

**Comment by gelderland** [comment]
Als aanvulling op mijn vorige opmerking/verzoek: wanneer gekozen wordt voor het labelen van afdelingen in de module contracten, kan via het filter "toon alleen geselecteerde objecten" gekozen worden om alle afdelingen of slechts de aan het contract gekoppelde afdelingen te laten zien (en afdrukken) op scherm (of print).
Wanneer ook de kadastrale laag wordt gekozen om te labelen werkt dit filter niet en worden alle in het kaartbeeld getoonde kadastrale percelen gelabeld, wat een onrustig kaartbeeld oplevert. Is het mogelijk om dit filter "toon alleen geselecteerde objecten" ook toe te passen zodat alleen de labels van kadastrale percelen die onder de aan een contract gekoppelde afdelingen liggen, worden getoond?

**Comment by LindaVels** [comment]
Op de acceptatie omgeving (test.crs2.nl) is een configuratie wijziging doorgevoerd (verschuiving) waardoor de labels van de afdelingen en percelen minder vaak over elkaar worden getekend. Dit is het beste wat we ervan kunnen maken. Door met de kaart te schuiven of in- uit- te zoomen kan de plaatsing van de labels ook beïnvloed worden.

**Comment by LindaVels** [comment]
@gelderland: graag testen op acceptatie

**Comment by gelderland** [comment]
Ik heb enkele percelen waar de kadastrale grenzen en afdelingen samenvallen bekeken: de verschuiving die je hebt aangebracht lijkt redelijk te werken. Wat me wel opvalt is dat de geselecteerde gelabelde afdeling 2x wordt gelabeld. Ik heb geprobeerd een voorbeeld bij te voegen. Lijkt niet helemaal te lukken, maar dit is het pad en de naam waar je het voorbeeld kunt vinden.
C:\Users\gelderland\Documents\DubbeleAfdelingLabels.pdf Kun je overigens de weergavekleur van de afdelinglabels iets donkerder maken zodat deze meer afsteken tegen de selectiekleur?

**Comment by gelderland** [comment]
Bij het bekijken van een kaart bij een contract valt me op dat er twee afdelingslabels in 1 afdeling worden weergegeven. In dit kaartbeeld zijn er twee voorbeelden, linksboven HAA03A en HAA03M en met het label erbij: HAA03N en HAA03P.
Is dit op te lossen?

[Meer afdelingslabels in vlak.pdf](https://github.com/IDgis/CRS2/files/302275/Meer.afdelingslabels.in.vlak.pdf)

**Comment by LindaVels** [comment]
Heb jouw voorbeelden bekeken en kom tot de conclusie dat de labels niet bij het vlak horen waar ze in staan, maar bij het vlak waar ze "naast" staan. Dit komt omdat labels in het zwaartepunt van het polygoon worden getekend en dat kan bij U-vormige vlakken soms niet in het vlak zijn. Ik heb hier verder geen invloed op.

**Comment by LindaVels** [comment]
Kan wel de kleur van de labels iets donkerder maken.

**Comment by gelderland** [comment]
Mooi dat het donkerder kan. 
[DubbeleAfdelingLabels 2.pdf](https://github.com/IDgis/CRS2/files/304301/DubbeleAfdelingLabels.2.pdf)
En de dubbele labels van geselecteerde afdelingen? Een afdeling wordt nu twee keer gelabeld. Zie voorbeeld Aar01M01AAR01M01

**Comment by LindaVels** [comment]
Dat is vreemd, ik ga het onderzoeken.
Verder heb ik getest met een donkerder kleur, dit resulteert echter niet in het beter zichtbaar zijn van de labels. Ik stel voor om een halo te gebruiken -> zie acceptatie server.

**Comment by LindaVels** [comment]
De Afdelingen worden als ze geselecteerd worden "dubbel" getekend, bij het optimaliseren van de labeling worden de dubbele labels  nu naast elkaar geplaatst ipv precies bovenop elkaar. Er is een programmatuur wijziging nodig om de labels in de selectie-laag niet te tekenen. Voorlopig heb ik de optimalisatie van de labeling weer teruggedraaid op de acceptatie omgeving. De labels van afdelingen en percelen worden nog wel onderling verschoven, zodat ze minder vaak over elkaar vallen.

**Comment by gelderland** [comment]
Het gebruik van een halo maakt de labels veel duidelijker. Lijkt me een prima oplossing. Het terugdraaien van de optimalisatie van de labeling om te voorkomen dat geselecteerde afdelingen dubbel gelabeld lijken te worden is akkoord wat mij betreft.

**Comment by gelderland** [comment]
Sorry, verkeerde knop gebruikt. Ik constateerde zojuist dat bij de CRS2 module kadastrale percelen de labels per kadastraal perceel meerdere keren worden getoond. Moet hier ook nog iets worden teruggedraaid?

**Comment by LindaVels** [comment]
De labeling voor kadastrale percelen was nog niet aangepast op de acceptatie omgeving, nu inmiddels wel. Zou je nogmaals willen testen. Bij akkoord zouden we graag de productie omgeving bij Gelderland willen inrichten.

**Comment by gelderland** [comment]
De labeling van kadastrale percelen ziet er nu goed uit en is akkoord. 
Ik krijg overigens in de acceptatie omgeving geen kaartbeeld bij transacties. De melding die ik krijg is "grondnummers niet gevonden op de kaart". In de live-omgeving krijg ik wel een kaartbeeld. Ik ga er van uit dat het huidige kaartbeeld in de live-omgeving bij het onderdeel transacties na het inrichten van de productieomgeving wel zichtbaar blijft. Wat ons betreft kan de productie (uiteraard met voorgaand voorbehoud) in gang worden gezet.
