### ISSUE TITLE
Berekenen contractopbrengsten werkt niet

### ISSUE THREAD

**Issue by gelderland** [IDgis/CRS2#196]
Via erven, tabblad details, gebouwen, gebouw raadplegen/wijzigen, jaargegevens gebouw raadplegen/wijzigen is het mogelijk om te kiezen voor de knop opnieuw berekenen van de contractopbrengst.

Dat kan nog steeds maar levert nu als resultaat een jaarbedrag van € 0,00 op. Wordt deze functie niet langer ondersteund waardoor de uitkomst, ondanks gekoppelde contracten, een bedrag van € 0,00 oplevert?

**Comment by ejmeulenkamp** [comment]
Hallo Paul, 
Heb je de jaaropbrengst gecontroleerd bij een gebouw dat in het geselecteerde jaar nog aan een lopend contract gekoppeld was? Als het contract niet meer loopt in het gebouwjaar, dan kan de opbrengst ook nul zijn.
Kun je me een voorbeeld van een gebouw geven waarbij je een opbrengst verwacht?

**Comment by gelderland** [comment]
Dag Evert Jan,
Eerlijk gezegd weet ik niet meer bij welk gebouw ik dit gisteren tegen ben gekomen. Maar een voorbeeld van een gebouw dat 100% zeker gekoppeld is aan een lopende huurovereenkomst is 541-007, contract 10855.

**Comment by ejmeulenkamp** [comment]
Hallo Paul,
Werkt de knop 'Jaaropbrengst berekenen' in het venster Erven nu weer zoals het hoort?

**Comment by gelderland** [comment]
Dag Evert Jan,

De knop "Jaaropbrengst berekenen" in het venster Erven werkt weer zoals het hoort, in ieder geval wat betreft de huuropbrengsten.  De velden "onderhoud" "afschrijving" "Gebr. deel" "Verz. waarde" "Gebr. deel" en "promillage" gebruiken we niet.
[Berekening gebouwopbrengst CRS2 2.01.06.docx](https://github.com/IDgis/CRS2/files/507984/Berekening.gebouwopbrengst.CRS2.2.01.06.docx)

Overigens viel het me op dat de gegevens in de testomgeving nog de oude gegevens zijn. Hierdoor was bijvoorbeeld bij het gebouw dat ik nu heb gebruikt om te bekijken of het berekenen van de jaaropbrengst weer werkt de taxatiewaarde niet ingevuld en uiteraard de huurbedragen vanaf 2013 tot en met 2016 waren ook nog niet gevuld. 

Mij staat bij dat je bij het vrijgeven van CRS2 2.01.06 eerst de database van de live-versie zou overzetten naar de testversie voordat je de nieuwe versie in de test-omgeving zou plaatsen. 

Overigens zie ik bij contract 10855 ook vreemde gebouwnummers in de kaartlaag verschijnen, namelijk 541-013 en 542-004. In de test database horen bij dit erf de gebouwnummers 542-009 en 542-004. Kaarlaag en inhoud van de database corresponderen niet met elkaar. Het is voor mij niet te verklaren waardoor het nummer 541-013 in de kaartlaag verschijnt na het kiezen voor labelen. Kijken we niet naar dezelfde kaartlaag in de test-versie en live-versie?
