### ISSUE TITLE
waarschuwing internet

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#197]
![capture](https://cloud.githubusercontent.com/assets/10415606/15650729/04cc616c-267b-11e6-8774-40c3b63976b7.JPG)

**Comment by ejmeulenkamp** [comment]
Ik heb Limburg rechten gegeven om hun versie van CRS2 op te starten. Als Harry echter een kaartvenster opent, dan krijgt hij telkens bovenstaande melding. Weet jij wat er gebeuren moet om deze melding niet meer te krijgen voor iemand die geen administrator rechten heeft. Ik krijg de melding namelijk niet.
Wat ik wel in IE heb gezien is dat het vinkje "Display Intranet sites in compatibility mode" aan stond. Dat heb ik uitgezet, maar de melding van IE blijft komen. Moet er iets toegevoegd worden in de vertrouwde websites?

**Comment by ejmeulenkamp** [comment]
Ik heb zojuist iedere organisatie toegangsrechten gegeven tot hun eigen versie van CRS2 op de acceptatieserver. Ook heb ik hen rechten toegekend om GitHub op te starten vanaf de server.
Ik vind het heel vreemd dat dit nu nodig is, terwijl het voorheen altijd gewerkt heeft.
