### ISSUE TITLE
Afdelingen worden niet getoond in Live-versie Kroondomein

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#199]
Ik ben zojuist gebeld door Bert Kraan. In CRS2 worden geen afdelingen getoond.
Gebeurt op diverse werkstations. Topografie en/of luchtfoto worden wel getoond.
Ik heb aangegeven dat waarschijnlijk de service op de applicatieserver gestopt is en dat ik aan jullie zal vragen om dit op te lossen. Er kan natuurlijk ook iets anders aan de hand zijn.

Bert Kraan zou graag vooraf op de hoogte gebracht willen worden van hoe dit opgelost gaat worden. Hij gaf aan dat eventueel tijdelijk de RDP-toegang weer mogelijk gemaakt kan worden.

Zou jij contact op willen nemen met Bert?

**Comment by LindaVels** [comment]
Wanneer de luchtfoto's en de topografie het wel doen dan is de misschien de server (dus ook de geoide service) herstart op een moment dat de database niet beschikbaar was.

**Comment by ejmeulenkamp** [comment]
Dat had ik ook al gedacht. Ik heb echter geen toegang tot de applicatieserver. Kun jij er voor zorgen dat ze weer afdelingen gaan zien in de viewer? 
Weten ze in welke volgorde ze op moeten starten?

**Comment by LindaVels** [comment]
Na telefonische contact met Bert (door Herman) gaat Bert zelf de service herstarten en ons de logfiles toesturen

**Comment by ejmeulenkamp** [comment]
Oké, bedankt voor de info. Het lijkt me goed dat ik Bert nog eens vraag om in het vervolg een issue direct in GitHub te plaatsen. Dat scheelt ons veel heen en weer getyp en gebel...
