### ISSUE TITLE
kad.objecten met verschil in oppervlakte crs-akr

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#20]
de percelen die geprint worden (ik heb 1 pagina test geprint) om verschil aan te geven hebben steeds de weergave xx / yy. Voor de streep is het getal steeds hetzelfde als na de streep. Met als verschil dat de komma een plaats is opgeschoven.
Voorbeeld: 
Amby A 297 0,6100  /  0.0610
Dit geldt voor de hele geprinte blz. 
Is dit een foutje in de database of in de berekening. Dezelfde actie heb ik ook uitgevoerd in het huidige crs. Daar bleek geen perceel een afwijkende oppervlakte te hebben.

**Comment by ejmeulenkamp** [comment]
Harry, bedankt voor deze constatering. Het blijkt een foutje te zijn in de database dat tijdens de conversie is ontstaan. Het conversieprogramma is aangepast, maar de databases zullen pas opnieuw geconverteerd worden op het moment dat we overstappen van centraal testen naar testen op jullie eigen servers.

**Comment by LimburgsLandschapHarry** [comment]
prima, houden we het issue nog even open tot we het dan kunnen testen

**Comment by LimburgsLandschapHarry** [comment]
overzicht klopt op testserver. Althans er zijn nog maar een paar percelen over
