### ISSUE TITLE
Klopt het dat dat de webviever momenteel niet beschikbaar is?

### ISSUE THREAD

**Issue by MirellW** [IDgis/CRS2#201]

**Comment by LimburgsLandschapHarry** [comment]
bij ons gewoon kaartmateriaal aanwezig. Dit hebben we eerder gehad. Moet je denk ik Linda vragen om wat te herstarten. Is overigens wel een zwak punt, als dat vaker terug komt.

**Comment by MirellW** [comment]
Service heb ik al herstart, maar levert niet gewenste resultaat op

**Comment by LindaVels** [comment]
Probleem met herstarten werd veroorzaakt door kopieën van configuratie bestanden in de configuratie map die daar niet thuishoren.

**Comment by MirellW** [comment]
Ah was dat de reden, dat waren de kopietjes voor het toevoegen van nieuwe kaartlagen, die kan ik dus beter in een apart mapje zetten begrijp ik.
Maar wel gek dat dit nu pas problemen oplevert, bestanden staan er al een tijdje in en volgens mij heb ik de service daarna ook al een keer herstart.

Groet Mirella
