### ISSUE TITLE
Selectie op eigenaar geeft melding 'niets gevonden'

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#202]
@LimburgsLandschapHarry 
Ik heb deze vraag even als apart issue opgenomen, anders wordt het verwarrend.

Er staan in de pull down menus van de 4 BRK selectievelden diverse namen / categorien die vervolgens niet in de percelen voor blijken te komen met de melding [geen gegevens gevonden die overeenkomen met de gestelde criteria]. Dit lijkt me niet logisch. Is daar een verklaring voor?

**Comment by ejmeulenkamp** [comment]
@LimburgsLandschapHarry 
Ik kan alleen subjecten tonen in het selectielijstje die "Eigendomsrechten" hebben. Dan krijg je wel altijd resultaat, maar ik weet niet of je dat verwacht als je een subject selecteert?

**Comment by LimburgsLandschapHarry** [comment]
Beginnend bij een lege selectie kan ik bij Subject het pull down menu uitklappen. De eerste naam die hier verschijnt is Achten, Hendrina Maria. Als ik die aanklik en vervolgens op Toon Selectie druk verwacht ik nadere informatie. Er volgt echter de melding  [geen gegevens gevonden die overeenkomen met de gestelde criteria]. Zoals eerder opgemerkt verwacht ik nadere info als ik deze naam kan selecteren. Bijvoorbeeld aan welk perceel deze naam hangt en hoe dit in relatie staat tot het Limburgs Landschap. Bijvoorbeeld mede eigenaar of anderszins.

**Comment by ejmeulenkamp** [comment]
Ik heb onderzocht wat er aan de hand was. Gebleken is dat er in de subjectentabel van de BRK subjecten staan die geen zakelijk recht hebben en ook geen aantekening op een zakelijk recht. Waarom ze er in staan weet ik niet, daar zal wel een logische reden voor zijn. Ik was er echter van uitgegaan dat ieder subject wel een zakelijk recht of een aantekening daarop had.
Ik heb nu de zoekopdracht aangepast die het keuzelijstje met subjecten samenstelt. Voortaan worden alleen subjecten getoond die een zakelijk recht hebben of een aantekening op een zakelijk recht.

Vanaf CRS2 versie 2.01.03 lijkt me dit issue dan ook opgelost.

@LindaVels  en @NijzinkM : Even jullie namen erbij om je hierover te informeren.

**Comment by LimburgsLandschapHarry** [comment]
Ik wil graag testen, kan 2.01.03 geïnstalleerd worden?

**Comment by ejmeulenkamp** [comment]
Hallo Harry,
Sorry, ik had je even moeten berichten. Het volgende speelt:
Ik heb tot mijn verbazing ontdekt dat de nieuwe manier van opvragen van het lijstje wel bij mij werkt (dan verschijnen wel alleen de subjecten die een recht of aantekening op een recht hebben), maar bij jullie niet. Er verschijnen dus nog steeds namen in het lijstje die er niet in horen. Ik heb dit probleem aan Herman voorgelegd. Morgen is Mart weer op kantoor. Ik zal hem dan bellen om te kijken of we de oorzaak kunnen vinden. Zodra we de oplossing hebben zal ik versie 2.01.03 installeren en contact met je opnemen.

**Comment by ejmeulenkamp** [comment]
Versie 2.01.03 van CRS2 is geïnstalleerd. De BRK-onderdelen in CRS2 kunnen nu weer verder getest worden. Ik krijg graag een seintje zodra het onderdeel BRK in CRS2 goedgekeurd is.

**Comment by ejmeulenkamp** [comment]
Is dit issue nog actueel?

**Comment by LimburgsLandschapHarry** [comment]
Nee,

nog ff getest en alles wat ik opvraag geeft logische resultaten.
