### ISSUE TITLE
agenda in contracten (acties)

### ISSUE THREAD

**Issue by HZLWannes** [IDgis/CRS2#203]
Als je aan een actiepunt in de module contracten een datum van afgevinkt wil koppelen, zou het heel handig dat je dat ook met de sneltoetsen 'T' en dergelijk zou kunnen doen. Ik denk ook dat dit de bedoeling is, maar momenteel lukt dit niet. Pas nadat je een datum hebt ingevuld verschijnt ook het kalendertje achter het datum invulveld. zie onderstaande printscreen.

![printscreen crs contracten](https://cloud.githubusercontent.com/assets/10400913/16414833/4594a288-3d3a-11e6-9917-453e1dbf8388.jpg)

**Comment by ejmeulenkamp** [comment]
Ik heb dit ook gezien. Als je twee keer op de letter 'T' drukt terwijl je in het veld staat, lukt het dan wel?

**Comment by HZLWannes** [comment]
Heb ik geprobeerd, dan werkt het ook niet. Ook drie en vier keer. Wat er gebeurt is dat de tussen streepjes verschijnen, maar geen datum zelf. Op andere plekken werkt dit dubbelklikken of typen wel.

Wat wel werkt is eerst de datum in typen. Dan wordt het veld wel een 'echt' datum veld, en activeren de sneltoetsen.

**Comment by ejmeulenkamp** [comment]
Zou je Martine eens kunnen vragen wat de reden is waarom ze de knop [Afvinken] niet gebruikt die onder de tabel met actiepunten staat? Dat levert namelijk hetzelfde resultaat op maar gaat wel veel sneller.

**Comment by HZLWannes** [comment]
Het werkt en is voor ons prima werkbaar. De reden dat ze het zo deed is dat ze er meestal ook aantekeningen bij maakt. Maar deze manier werkt natuurlijk prima.

Hartelijk dank!
