### ISSUE TITLE
oppervlaktes afdelingen kloppen niet na geomutaties verwerken

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#204]
Hallo Gwen,

ik heb net (in de productieomgeving, dus niet op basis van BRK kadasterfile) geomutaties gedraaid. Het controlerapport geeft aan dat er diverse afdelingsoppervlaktes zijn veranderd. Meestal met 0.001 ha of zo. Echter er zitten er ook bij die 1 of bijna 2 ha kleiner zijn geworden. Ik heb er twee gecontroleerd. Die blijken beide er geen kadastraal nummer / perceel onder te hebben liggen. Dit zijn percelen die we in beheer hebben.  Waarschijnlijk wordt de k factor dan bepaald op basis van dit niet aanwezige perceel en de oppervlakte flink verkleind. Lost dit probleem zich vanzelf op als het kadastrale perceel er weer onder ligt? In de BRK zijn de kadastrale percelen wel aanwezig. Klopt mijn inschatting?

**Comment by gwenroyakkers** [comment]
Hoi Harry,
De K-factor is niets anders als de "kadastrale_oppervlakte / werkelijke_oppervlakte_geometrie"
Indien het perceel geen kadastrale oppervlakte heeft wordt als K-factor de waarde 1 gebruikt, waardoor de echte oppervlakte wordt gebruikt bij een verknipt perceel.

De missende oppervlaktes lossen zichzelf op als het perceel weer aanwezig is.
De kleine afwijkingen kunnen ook veroorzaakt worden door afdelingen die slivers hebben met de nieuwe percelen. Dit Wordt meestal veroorzaakt door imports/exports van shapefiles, of als het nieuwe perceel werkelijk verschillend is van vorm.

In principe wordt overal waar er geen K-factor kan worden berekend de oppervlakte van de geometrie overgenomen. Je zou eens met GIS kunnen kijken of dit ook het geval is. (oppervlakte van geometrie staat in kolom Shape_Area van de GDB).

Indien het probleem aanhoud in productie moeten we kijken of de BRK de correcte oppervlaktes en geometrie bevat voor deze percelen, en of de afdelingen waarover het gaat hier nog correct op aansluiten.

**Comment by LimburgsLandschapHarry** [comment]
Alle BRK percelen worden nu ingelezen op de testomgeving alhier. Bij het opnieuw berekenen van de oppervlaktes worden deze weer opnieuw berekend en zijn nu wel juist.
