### ISSUE TITLE
vraag over kad-percelen in beeld

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#205]
Hoe gaat het werken als de BRK draait en er nieuwe aankopen zijn. In de administratieve kant worden deze ingevoerd. Tot nu toe verschenen ze dan op kaart als In Aankoop nadat ze administratief waren ingevoerd. Nu gebeurt dat niet meer. Het overzicht ontbreekt vervolgens waar de 'In Aankoop' gebieden ligt.

**Comment by HermanAssink** [comment]
Dit lijkt me een vraag voor Evert Jan. BRK2DB verwerkt de mutaties zoals door het Kadaster geleverd.

**Comment by ejmeulenkamp** [comment]
Hallo Gwen en Tom,
Kunnen jullie misschien antwoord geven op bovenstaande vraag? Limburg krijgt waarschijnlijk alleen de eigen percelen geleverd via de BRK. Kunnen ze de percelen die ze aan (willen) kopen in CRS2 zichtbaar maken door ze te downloaden van PDOK? En is daar een instructie voor?
Hoe kunnen ze de percelen als grondnummer koppelen aan een aankoop?

**Comment by ejmeulenkamp** [comment]
@gwenroyakkers 
Hallo Gwen en Tom. Zouden jullie kunnen reageren op dit issue? Komt er ook voor de CRS2-gebruikers een nieuwe knop in de extensie beschikbaar?

**Comment by LimburgsLandschapHarry** [comment]
ik heb het hier met Tom over gehad. De aanpassing is klaar en werkt vanaf versie 10.4 ArcGis. Kragten moet nog wel ff kortsluiten met de overige gebruikers en prijs afgeven. Wat SLL betreft is hetgeen Tom heeft aangegeven akkoord.

**Comment by gwenroyakkers** [comment]
Dit is inderdaad opgelost met de tool die beschreven wordt in de mail van Tom (08-11-2016)
