### ISSUE TITLE
foutmelding in productie omgeving bij aanmaken nieuwe gebruiker

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#206]
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET LIMBURGS LANDSCHAP

Datum / Tijd:    09-08-2016 11:58:50
Gebruiker:       Bussink, Harry                          
Programmaversie: 2.00.08
Foutnummer:      13   
Programmaregel:  13   

Foutboodschap:
    Alias '' is not found.

Methode/Programma:
    FRMICUSERPROPERTIES.ADDAFTERAPPENDBLANK                                                                                 

Code:
    ASTACKINFO(laStackInfo)

Inhoud AERROR():
    13
    Alias 'GNERRORNUMBER' is not found.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    M:\CRS2SQL\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS M:\VMP2005\XLIB\XXFW.VCT
    PROCEDURE FRMC2RIGHTSADMIN.CMDNEWUSER.CLICK M:\VMP2005\XLIB\XXFWSEC.VCT
    PROCEDURE FRMC2RIGHTSADMIN.CALLUSERSDIALOG M:\VMP2005\XLIB\XXFWSEC.VCT
    X8WRPFRM.FXP
    PROCEDURE FRMICUSERPROPERTIES.ACTIVATE M:\VMP2005\XLIB\XXFW.VCT
    PROCEDURE FRMBASE.ACTIVATE M:\VMP2005\XLIB\XXFW.VCT
    PROCEDURE FRMICUSERPROPERTIES.INITIALSETFOCUS M:\VMP2005\XLIB\XXFWSEC.VCT
    PROCEDURE FRMDATA.INITIALSETFOCUS M:\VMP2005\XLIB\XXFW.VCT
    PROCEDURE FRMICUSERPROPERTIES.CMDADD.CLICK M:\VMP2005\XLIB\XXFWCTRL.VCT
    PROCEDURE FRMICUSERPROPERTIES.ADDACTION M:\VMP2005\XLIB\XXFWSEC.VCT
    PROCEDURE FRMDATA.ADDACTION M:\VMP2005\XLIB\XXFW.VCT
    PROCEDURE FRMICUSERPROPERTIES.ADDAFTERAPPENDBLANK M:\VMP2005\XLIB\XXFW.VCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (FRMICUSERPROPERTIES.ADDAFTERAPPENDBLANK)

Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    aanmaak nieuwe gebruiker bij Onderhoud-Toevoegen Gebruiker.

**Comment by ejmeulenkamp** [comment]
Deze fout is ook door andere gebruikers gemeld en inmiddels opgelost in de meest recente versie, welke binnenkort (in overleg) geïnstalleerd zal worden. Ik zal contact opnemen voor het installeren van de update.
