### ISSUE TITLE
Acceptatieserver: Kaartlaag Gemeenten niet aanwezig in versie Limburg

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#208]
Op de acceptatieserver is de kaartlaag Gemeenten niet aanwezig. Deze laag zou wel aanwezig moeten zijn, omdat via die laag vastgesteld wordt in welke pachtregio een contract ligt.
Als dit niet vastgesteld kan worden, dan werkt de ondersteuning bij het berekenen van de maximaal toegestane pachtprijs niet.

**Comment by robstek** [comment]
wordt behandeld in geoide-commons project #270
