### ISSUE TITLE
Acceptatieserver: Veranderen schaal via schaalkiezer verstoort identify results

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#209]
Als ik via de schaalkiezer in de viewer een andere schaal kies, nadat ik Identify Results (IR) een keer heb gebruikt, dan gebeurt er soms niets. Nadat ik even een andere functie (bijvoorbeeld de Zoom-knop) heb gekozen en daarna opnieuw de schaal probeer aan te passen verandert de schaal wel. Als ik daarna met IR op een afdeling klik blijft het venster leeg.
Na een paar keren klikken op diverse afdelingen verscheen opeens het volgende in het venster IR:
![image](https://cloud.githubusercontent.com/assets/10232554/19037034/5a76c2c2-8974-11e6-8009-192f9cb4f1cc.png)

**Comment by ejmeulenkamp** [comment]
Aanvulling:
Blijkbaar duurt het ophalen van de informatie soms iets langer en dacht ik daarom dat het venster IR leeg bleef. Als ik het nu weer probeer en een beetje langer wacht, dan verschijnt er wel info in het venster IR. Kan er misschien een zandlopertje getoond worden? Dat voorkomt helpdeskvragen.

**Comment by robstek** [comment]
wordt behandeld in geoide-commons project #269
