### ISSUE TITLE
Vergelijken CRS - LKI

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#21]
Ik krijg de melding [Het BOGisKad business object kon niet geladen worden om gegevens op te halen]. 
Na op OK klikken kan werk vervolgd worden.

**Comment by ejmeulenkamp** [comment]
Werkt de vergelijking LKI-CRS nu wel?

**Comment by LimburgsLandschapHarry** [comment]
functie werkt!
