### ISSUE TITLE
Acceptatieserver: Oppervlakte van kaartobject meten onduidelijk

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#210]
Als ik met de functie "Oppervlakte van kaartobject meten" ergens in de viewer klik waar geen kaartobject ligt in de actieve laag, dan blijft de oppervlakte van het laatst gemeten object staan. Er komt geen melding dat er geen kaartobject ligt op de plek waar geklikt is. Zou dit niet beter zijn?

**Comment by robstek** [comment]
wordt behandeld in geoide-commons project #268
