### ISSUE TITLE
Acceptatieserver: Functie 'Toon alleen geselecteerde objecten' lijkt niet altijd te werken

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#211]
Als ik een selectie heb gemaakt en ik klik daarna op de knop 'Toon alleen geselecteerde objecten', dan blijven daarna toch nog niet geselecteerde objecten in beeld:
![image](https://cloud.githubusercontent.com/assets/10232554/19037638/9454b636-8977-11e6-8b64-aeb93c7cc7c8.png)

**Comment by ejmeulenkamp** [comment]
Soms ook wel. Heeft het misschien met het aantal geselecteerde objecten te maken?
![image](https://cloud.githubusercontent.com/assets/10232554/19037695/db67345e-8977-11e6-802e-b7f7279c3f5d.png)

**Comment by robstek** [comment]
wordt behandeld in geoide-commons project #267
