### ISSUE TITLE
Acceptatieserver: Digitaliseer punt kan niet 'uitgezet' worden

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#212]
De volgende knoppen (die naast elkaar staan) kunnen 'uitgezet' worden door er opnieuw op te klikken:
- Versie Geoide5
- Toon labels
- Toon alleen geselecteerde objecten

De knop 'Digitaliseer punt' staat in hetzelfde rijtje, heeft dezelfde vorm, maar kan niet 'uitgezet' worden door er opnieuw op te klikken. Is het eenvoudig om dit te veranderen?

**Comment by ejmeulenkamp** [comment]
De knop 'Zoeken' kan ook aan en uitgezet worden, de knoppen ernaast niet. Het zou volgens mij beter zijn dat een gebruiker dit kan herkennen aan de knop. 
Geen halszaak :-)

**Comment by LindaVels** [comment]
Het verschil zit m erin dat de knoppen die niet aan of uit gezet kunnen worden de kaart modus veranderen (zoomin, zoomuit, digitaliseer etc). De kaartmodus regelt hoe de viewer reageert op een muisklik in de kaart. Door op een andere kaartmodus knop te klikken gaat de "huidige" knop uit. Je zou het zo kunnen maken dat een klik op een actieve kaartmodus knop de default kaart modus activeert (gelijk aan die bij opstarten).

**Comment by robstek** [comment]
wordt behandeld in geoide-commons project #266
