### ISSUE TITLE
Acceptatieserver: Er wordt soms te ver ingezoomed op een selectie

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#213]
Ik selecteer via een administratieve selectie of via de zoekknop in de viewer en daarna een select-punt een object op de kaart. Daarna klik ik op full-extend en daarna weer op 'Zoom-to-selectie'. Dan wordt er te ver op de selectie ingezoomed:
![image](https://cloud.githubusercontent.com/assets/10232554/19038251/07ba084e-897b-11e6-8e19-441a37477216.png)

**Comment by LindaVels** [comment]
Bedoel je verder dan de ingestelde min zoom schaal?

**Comment by robstek** [comment]
wordt behandeld in geoide-commons project #265
