### ISSUE TITLE
Acceptatieserver: Openen van website IDgis levert foutmelding op

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#214]
Als ik via de knop 'Over Geoide5' op de link van IDgis klik, dan wordt de website van IDgis geopend in de viewer. Dit levert een foutmelding op:
![image](https://cloud.githubusercontent.com/assets/10232554/19038421/b44c3988-897b-11e6-8a4c-8ff41046a304.png)

Je kunt vervolgens niet de website sluiten.
Als je dan doorgaat en in CRS2 een administratieve selectie maakt, verschijnt er een fatale foutmelding en klap je uit CRS2:
![image](https://cloud.githubusercontent.com/assets/10232554/19038461/e2397306-897b-11e6-8fc8-e83d374f0d3a.png)

**Comment by robstek** [comment]
wordt behandeld in geoide-commons project #264
