### ISSUE TITLE
Acceptatieserver: Tekstlabels op de print hebben andere achtergrondkleur dan in de viewer

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#215]
Als ik een tekstlabel toevoeg in de viewer, dan wordt de tekst in de viewer getoond op een heldere achtergrond. Op het kaartje is het een donkergroene kleur, waardoor ik de tekst niet meer goed leesbaar vind. Is dit de bedoeling?
Het kan zijn dat Limburg dit zo besteld heeft?

**Comment by ejmeulenkamp** [comment]
Een voorbeeldje:
![image](https://cloud.githubusercontent.com/assets/10232554/19038772/56aae8c2-897d-11e6-8d3c-a7835d0e4217.png)

**Comment by robstek** [comment]
wordt behandeld in geoide-commons project #263
