### ISSUE TITLE
achtergrond kaart bouwt niet goed op

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#216]
in afdelingen: opbouw onderliggende kaartlaag werkt niet goed. 
Afhankelijk van de plek in de provincie bouwt de kaart op schaalnivo 1:1000 traag op, of maar gedeeltelijk.
ligt dit weer bij PDOK?

**Comment by HermanAssink** [comment]
Inderdaad, PDOK is de laatste dagen soms off-line of erg traag. Dat was vanmorgen ook een tijdje het geval.
