### ISSUE TITLE
projecten - subsidies

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#217]
In projecten, tabblad subsidies heeft Lia geprobeerd om een relatie toe te voegen. Lia werkt op de server. De lijst met relaties waar uit gekozen kan worden heeft op mijn compi het juiste beeld, met schuifbalk rechts. Bij Lia echter niet. Zie bijgevoegde plaatje. Waarschijnlijk klopt er iets niet als het via de server uitgevoerd wordt.
![crs](https://cloud.githubusercontent.com/assets/10415606/19266440/d0151106-8fa9-11e6-950b-49f6899c1bb2.jpg)

**Comment by ejmeulenkamp** [comment]
Dit wordt blijkbaar veroorzaakt doordat de kolommen 'e-mailadres' en 'bedrijfnaam' toegevoegd zijn. Je kunt de lijst weer normaliseren door de optie 'Extra > Gebruikersvoorkeuren wissen' uit te voeren.
Hierdoor worden kolomvolgordes en vensterposities en -groottes gereset. Alle gegevens van CRS2 blijven uiteraard behouden. Iedereen zal een keer opnieuw zijn voorkeuren (al werkend) in moeten stellen.

**Comment by LimburgsLandschapHarry** [comment]
Hoi,
ingelogd als Harry kan ik dit wel. Ingelogd als Lia kan ik niet bij extra-gebruikersvoorkeuren wissen. Hoe kom ik daar wel bij?

**Comment by ejmeulenkamp** [comment]
Gebleken is dat het probleem niet opgelost wordt door het wissen van de gebruikersvoorkeuren. De lijst was gewoon te breed om op bepaalde beeldschermen weer te geven. Ik heb de lijst nu smaller gemaakt. 
Als het probleem nog speelt, dan kan ik een update plaatsen. Speelt het probleem nog?

**Comment by LimburgsLandschapHarry** [comment]
Lia krijgt de lijst nu goed in beeld. Wellicht al in een vorige update meegenomen?
