### ISSUE TITLE
lagen in viewer gaan niet uit

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#218]
ik heb crs aan staan. venster kad.objecten. Dar wil ik in de legenda de laag kadastrale percelen uitzetten en de laag afdelingen aan. Dit lukt niet. Wellicht herstart viewer?

**Comment by LimburgsLandschapHarry** [comment]
probleem heeft zich al opgelost. Het werkt weer.

**Comment by LimburgsLandschapHarry** [comment]
geen idee waarom. Eerdere herstart crs werkte niet.

**Comment by LindaVels** [comment]
Kan het zijn dat de ondergrond haperde. Ik heb al eerder gemerkt dat dat ook "vertragingen" in de viewer kan opleveren.

**Comment by LimburgsLandschapHarry** [comment]
klopt, de pdok laadt niet goed in, je ziet verschillen in scherpte van de verschillende tiles die ingeladen worden. lijkt er inderdaad op dat daardoor ook andere delen in de viewer niet reageren. Ik heb daarna voor de snelheid (en om niet te gefrustreerd te raken;)) de pdok onderlaag ook uitgezet.
