### ISSUE TITLE
Module waarnemingen: Digitaliseerstip markering kan zich vermenigvuldigen

### ISSUE THREAD

**Issue by HZLWannes** [IDgis/CRS2#22]
Voorheen werkte het zo dat je de digitaliseerstip ergens achter liet. Nu vind ik het opzich best prettig dat je de stip echt meeneemt, daardoor kun je beter sturen en precies zien waar je hem achterlaat. Maar wat ik minder prettig vindt is dat hij al mijn markeringen achter laat ook als ik ze niet opsla. 
Dit is wat lastig uitleggen, je klikt ergens en ziet de stip staan, dat coordinaat vult hij netjes links in, vervolgens denk je, nee moet iets meer naar rechts... dan klik je daar en staan er twee markeringen terwijl de meest rechtse alleen correspondeerd met het nieuw ingevulde coordinaat. Ik wil alleen de markering zien die correspondeerd met het ingevulde coordinaat.

**Comment by LindaVels** [comment]
Nu wordt de stip na tekenen gelijk weer weggehaald met het idee dat deze pas weer verschijnt na het wegschrijven in de database (mbv een refresh van de viewer). Ik denk echter dat dit ook niet het gewenste gedrag is. Het punt zou eigenlijk getekend moeten worden adhv de coördinaten in het CRS2 scherm. (na een onchangeEvent van CRS2 naar viewer bij wijzigen coördinaten).  Ik neem aan dat coördinaten ook met de hand ingevuld kunnen worden? dan moet de stip ook op de juiste locatie verschijnen.
@ejmeulenkamp Kun jij een onChange event versturen na wijzigen coördinaten?
@HZLWannes Kan je je hierin vinden?
.

**Comment by HZLWannes** [comment]
@LindaVels en @ejmeulenkamp Precies zoals je beschrijft Linda, de stip moet getekend worden aan de hand van het coördinaat, de digitaliseerstip is alleen maar bedoeld om dat coördinaat eventueel in te vullen, maar zoals je zegt we typen soms ook het coördinaat. Ook als we de stip midden in een hok willen zetten door het getal af te kappen (net effe anders dan afronden) en vervolgens een halve er bij op te tellen, dan wil ik daar de stip zien en niet waar ik heb geklikt met de digitaliseer stip. Dus de stip moet opgeslagen worden via de coördinaten die crs geeft (hij hoeft pas te verschijnen na opslaan).

**Comment by ejmeulenkamp** [comment]
Het is nu zover dat CRS2 de stip wil tonen nadat er op [Bewaren] is geklikt. Hiervoor geeft CRS2 een Refresh-commando aan de viewer. Dit refresh-commando werkt echter nog niet goed, maar daar wordt hard aan gewerkt. Momenteel moet het venster waarnemingen nog even opnieuw opgestart worden om de nieuwe stip te zien.
Het eindresultaat zal dus zijn dat de stip na [Bewaren] op de plaats gezet wordt van het (eventueel afgekapte) coördinaat dat in CRS2 opgeslagen is. Zelfs als je na het [Bewaren] merkt dat de stip toch nog verplaatst moet worden, dan kun je de coördinaten aanpassen (d.m.v. handmatige invoer of een klik op de kaart). Na [Bewaren] zal de oude stip dan 'verplaatst' worden naar de nieuwe locatie.
@HZLWannes  Is dit zoals het zou moeten werken?

**Comment by HZLWannes** [comment]
@LindaVels en @ejmeulenkamp Dat is opzich goed. Nu werkt het alleen net iets anders. Voor beide is iets te zeggen. Als je na opslaan in de huidige crs met de digitaliseerstip klikt wijzigt het coördinaat volgens mij niet en moet je hem dus handmatig wijzigen. Deze optie is veiliger, maar omslachtiger als je nu voorstelt. Zoals ik zeg is er voor beide wat te zeggen. Mag dus beide, maar hij mag pas wijzigen na het opnieuw opslaan, want anders kun je met een klik op de kaart per ongeluk waarnemingen wijzigen! Kunnen jullie me volgen?

**Comment by LindaVels** [comment]
@HZLWannes: De punt kan in de database alleen maar worden gewijzigd dmv opslaan via het CRS2 scherm. Het wijzigen of zetten van een punt in de kaart kan nooit leiden tot direct wijzigen in de database.

**Comment by HZLWannes** [comment]
@LindaVels In dat geval zou wijzigen met de digitaliseerstip natuurlijk wel heel handig zijn. Dan nog zal ik de invoerders goed moeten instrueren. Maar jullie voorstel is prima.

**Comment by ejmeulenkamp** [comment]
Het is nu zo gebouwd dat pas als de knoppen [Bewaren] en [Annuleren] in CRS2 actief zijn ("Edit-modus"), bij een klik in de kaart met de knop "Digitaliseer punt" de coördinaten overgenomen worden in CRS2. Je kunt dus tijdens het raadplegen niet per ongeluk een coördinaat veranderen.
Als je een nieuwe waarneming invoert, dan staat CRS2 altijd al in de edit-modus. Als je een coördinaat van een bestaande waarneming wilt veranderen, dan zul je CRS2 eerst in de "edit-modus" moeten zetten, door bijvoorbeeld een spatie in het opmerkingenveld toe te voegen.

**Comment by HZLWannes** [comment]
Ik had hier nog nooit op gereageerd, maar dit is ideaal!
