### ISSUE TITLE
viewer knop zoomen naar geselecteerd objecten reageert niet

### ISSUE THREAD

**Issue by MirellW** [IDgis/CRS2#220]
Bij ons werkt de viewer knop Zoom naar geselecteerde objecten niet.

**Comment by LindaVels** [comment]
Heb het probleem onderzocht, het bleek een mismatch tussen wat de composer wegschrijft en de viewer veronderstelt. Voor Fryslan heb ik het probleem opgelost door de db van de composer te updaten. Aan een definitieve oplossing wordt gewerkt.

**Comment by LindaVels** [comment]
Limburg, Zeeland en Groningen ook bijgewerkt.
