### ISSUE TITLE
service toevoegen aan kaarten werkt (nog) niet goed CRS

### ISSUE THREAD

**Issue by MirellW** [IDgis/CRS2#221]
Wanneer ik de opentopo.tms service toevoeg aan een kaartlaag en vervolgens in CRS de kaartlaag opvraag, werken bepaalde functies niet meer. Zo zoomt de kaart bijvoorbeeld niet meer automatisch in op geselecteerde afdelingen en werken een aantal koppen niet meer in CRS.
De toegevoegde service is wel zichtbaar in de viewer.

**Comment by MirellW** [comment]
![crs_geoide_viewer_kaart](https://cloud.githubusercontent.com/assets/10529807/20209586/6401d12a-a7f5-11e6-827c-0f5eae9ae277.JPG)

**Comment by ejmeulenkamp** [comment]
Hallo Mirella,

Zou je bij het indienen van een nieuw issue over de viewer direct het label 'GisViewer' en assignee 'Linda' kunnen instellen? Dan krijg je waarschijnlijk sneller antwoord.

**Comment by MirellW** [comment]
ok
