### ISSUE TITLE
BRK poos niet bijgewerkt

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#225]
Ik heb net de controle uitgevoerd wanneer de BRK voor het laatst is bijgewerkt, en het blijkt dat dat al een poos niet meer gebeurd is (25-10-2016). Kunnen jullie dit weer aan de praat krijgen.

**Comment by HermanAssink** [comment]
@NijzinkM Wil jij dit vanmiddag oppakken?

**Comment by NijzinkM** [comment]
Bedankt voor het melden.

De opdracht om BRK2DB te runnen in Windows Taakplanner verwees naar een oudere Java-versie. Blijkbaar is Java geüpdatet waardoor BRK2DB niet meer werd uitgevoerd. De verwijzing naar Java is nu vervangen door een versie-onafhankelijke verwijzing (JAVA_HOME).

Ik heb BRK2DB zojuist gerunt. De BRK-gegevens zijn nu weer actueel en zullen elke nacht geactualiseerd worden. Het updaten van Java is nu gewoon mogelijk zonder dat dit problemen oplevert voor BRK2DB.

**Comment by LimburgsLandschapHarry** [comment]
Dank.
