### ISSUE TITLE
Info gekoppelde WFS BKK kadaster niet zichtbaar in viewer

### ISSUE THREAD

**Issue by MirellW** [IDgis/CRS2#227]
Werkt de infotool alleen op de CRS gdb's?
Ik meende dat ook de info van de extern gekoppelde WFS opgevraagd konden worden met de infoknop, maar dan krijg je een leeg scherm.
Zie afbeeldingen

![wfsinfobkk](https://cloud.githubusercontent.com/assets/10529807/21141401/3932ca10-c13d-11e6-8227-279ad99cb3c3.JPG)

![bkklaagel](https://cloud.githubusercontent.com/assets/10529807/21141369/0c5f968a-c13d-11e6-9d79-d5d4114c58d2.JPG)

**Comment by HermanAssink** [comment]
Hallo Mirella, Heb je misschien https ipv http gebruikt? Met onderstaande service links werkt het bij mij wel:
- wms: http://geodata.nationaalgeoregister.nl/kadastralekaartv3/wms?
- wfs: http://geodata.nationaalgeoregister.nl/kadastralekaartv3/wfs?

De laag is bij mij zo geconfigureerd:

![image](https://cloud.githubusercontent.com/assets/2979044/21142993/1459ad50-c145-11e6-86e8-a56cf500580f.png)

Groeten, Herman

**Comment by MirellW** [comment]
Dat s-je  was inderdaad het probleem.
Bedankt,

Groet Mirella
