### ISSUE TITLE
geen kaartbeeld

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#228]
bij het openen van een venster met kaartbeeld verschijnt de volgende melding: 
De webpagina van de viewer kon niet gevonden worden. controleer of viewer en web services online zijn. neem eventueel contact op met de applicatie beheerder.

Bij deze dus het contact opnemen.

**Comment by HermanAssink** [comment]
Hallo Harry, De server was gisteravond ge-reboot en de viewer service start nog niet goed na een reboot omdat deze moet wachten op de composer service.
We zijn bezig met een verbetering die ervoor zorgt dat de viewer service wacht op de composer service.
Groeten, Herman

**Comment by HermanAssink** [comment]
Viewer service is dus gestart door mij.

**Comment by LimburgsLandschapHarry** [comment]
dank!
