### ISSUE TITLE
kaart verschijnt niet

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#229]

**Comment by HermanAssink** [comment]
Viewer service ie gestart. De oorzaak was weer dat server was herstart. Woensdag a.s. verwachten we een Geoide versie te hebben die na herstart van de server goed opkomt.

**Comment by LimburgsLandschapHarry** [comment]
Hoi,
dat is goed nieuws. Is te doen zo, maar als het automatisch gaat is natuurlijk stuk prettiger en beter.
We wachten af.
