### ISSUE TITLE
geen labels bij deel van de elementen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#233]
Als ik in het venster elementen de label button aanklik komen er alleen labels bij de lijnelementen. Bij de puntelementen komen geen labels.

**Comment by LindaVels** [comment]
De label (en de filter) knop werkt alleen op de "actieve" laag. De actieve laag is de laag  met de paars blauwe achtergrond in de legenda. Door op de puntelementen laag te klikken kan deze actief worden gemaakt, een druk op de label knop resulteert vervolgens op het labelen van de puntelementen.

**Comment by LimburgsLandschapHarry** [comment]
ok, ik heb het geprobeerd en het werkt. Door achtereenvolgens verschillende lagen actief te maken kun je toch alle labels te zien krijgen.
