### ISSUE TITLE
lijnelelement verschijnt niet in beeld bij crs

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#234]
in venster elementen kun je [select huidige] klikken en dan zoomt de kaart naar het geselecteerde element. Dit werkt voor alle elementen, maar niet voor 'knotbomenrij'. 
Enig idee hoe dit kan, en op te lossen is.

**Comment by LindaVels** [comment]
Hetzelfde verschijnsel doet zich voor op de testomgeving. 
Hier zie ik dat vanuit het CRS2 een query naar de viewer wordt gestuurd die geen resultaten oplevert in de database. Er wordt getracht puntelementen te selecteren met als type "Knotbomenrij". Knotbomenrij zit echter in de lijnelementen laag.

**Comment by LindaVels** [comment]
Om dit te debuggen heb ik het test formulier aangezet in CRS2 (testvfp in de url in de start.ini voor opstarten CRS2). Alle requests (ook die met de select query) vanuit CRS2 naar de viewer  worden in het testformulier gelogd. De query heb ik gekopieerd en direct afgevuurd op de database.
Dat Knotbomenrij in de lijnelementen laag zit is o.a. te zien in de legenda.

**Comment by LimburgsLandschapHarry** [comment]
Is er vervolgens ook een manier beschikbaar om de knotbomen wel in te laten zoomen / selecteerbaar te maken in CRS. Knotbomen worden opgegeven in stuks, net als poelen. Maar knotbomenrij is een lijnelement en poelen een puntelement.

**Comment by LindaVels** [comment]
Is zie in CRS2 geen elementsoort "Knotboom" enkel en alleen "Knotbomenrij". Ik denk dat Evert-Jan hier meer over weet te melden.

**Comment by LindaVels** [comment]
![even](https://user-images.githubusercontent.com/9080474/29764954-8c066eba-8bd9-11e7-8b9d-9ffde5f40736.png)

**Comment by LimburgsLandschapHarry** [comment]
klopt, is inderdaad knotbomenrij. Ik gebruik hierboven de beide termen door elkaar heen. 
Punt blijft natuurlijk hoe ik bij selectie in CRS-administratief het bijbehorende kaartbeeld krijg. Andersom werkt het wel. Als ik in het kaartbeeld op 'informatie' druk krijg ik wel de bijbehorende crs data te zien.

**Comment by LindaVels** [comment]
Het is naar mijn idee een bug in CRS2 (verkeerde laag gekoppeld aan knotbomenrij). Ik denk dat dit opgelost kan worden door Evert-Jan. Hij is per 1 september terug. Ik zal de issue aan hem toewijzen.

**Comment by ejmeulenkamp** [comment]
In het stambestand Elementsoorten in CRS2 staat bij jullie aangegeven dat een knotbomenrij als eenheid 'ST' (Stuks) heeft. Hierdoor gaat CRS2 er van uit dat het een commando naar de viewer moet sturen in de laag 'Puntelementen' om ze te tonen. Als de knotbomenrijen in gis echter als lijnelementen opgenomen staan, dan zal er niets geselecteerd worden. 
Mogelijke oplossingen, waarbij 1 de meest logische is volgens mij:
1: Veranderd de eenheid ST in M1 in het stambestand Elementsoorten in CRS2.
2: Verplaats de knotbomenrijen in gis naar de laag puntelementen.

**Comment by LimburgsLandschapHarry** [comment]
Er is in overleg voor gekozen om de eenheid van een knotbomenrij te veranderen in M1 in plaats van STUKS. Eerst moeten dan het aantal stuks dat ingevuld staat worden ingevuld in het veld Notities op het tabblad Details, zodat het aantal bekend blijft.
