### ISSUE TITLE
toevoegen percelen aan contract

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#237]
aan een contract een grote hoeveelheid percelen toevoegen dmv de button [koppelen] is niet handig ingericht.
Als je op basis van het kaartbeeld percelen aan een contract wilt koppelen zoom je in op het betreffende gebied klikt [koppelen] en selecteert 1 of meerdere (shift indrukken) percelen. 
(Eerst krijg je daar een scherm waar je algemene voorwaarden aan de toe te voegen percelen kunt koppelen. Handig voor sommige gebruikers. Voor mij echter een onnodige extra muisklik. )
Voor de veiligheid druk ik daarna nogmaals op [koppelen] en [bewaren]. Dan ga ik door naar het volgende te koppelen perceel op de kaart, zoom in en klik op [koppelen]. Het kaartbeeld zoomt hierbij naar de reeds gekoppelde percelen. Ik moet dan terugzoomen naar de te koppelen percelen; vervolgens de button [selecteer-punt] aanklikken en kan weer een paar percelen er aan toevoegen. Als ik pech heb vergeet ik om bij het toevoegen de shift knop ingedrukt te houden, dan moet ik .. keer klikken dat ik een reeds gekoppeld perceel niet wil verwijderen. Kortom een werkwijze die beter moet kunnen. 
Ik meen dat dit onderwerp eerder ter sprake is geweest. Graag overleg hierover of dit op een handigere manier ingericht kan worden.

**Comment by LimburgsLandschapHarry** [comment]
zag dat dit issue nr 160 is geweest. Is toen gesloten, werkt echter nog steeds niet handig.

**Comment by ejmeulenkamp** [comment]
Het koppelen van percelen aan een contract is tijdens de laatste update gewijzigd. Het lijkt me goed om ook dit via een TeamViewer-sessie samen te bekijken.

**Comment by ejmeulenkamp** [comment]
Zoals telefonisch besproken:
Het koppelen van afdelingen met behulp van de viewer is niet ingericht op het koppelen van grote hoeveelheden afdelingen die verspreid liggen over grote gebieden. Als je dit toch wilt adviseer ik om in plaats van één contract meerdere kleine contracten van eenzelfde (unieke) contractsoort per deelgebied te maken en de afdelingen daar aan te koppelen. Je kunt dan alle afdelingen toch in één keer selecteren door alle contracten van de unieke contractsoort te selecteren.

**Comment by LimburgsLandschapHarry** [comment]
In onderling overleg is er voor gekozen om voor een nieuwe  contractsoort aan te maken waar de gronden aan worden gekoppeld die bij de landbouw bv in beheer zijn (over de hele provincie). Deze vallen in groep A en mogen niet dubbelen met pacht en dergelijke. Er wordt ook voor gekozen om deze op te delen in deelgebieden, zodat bij het koppelen niet uitgezoomd wordt naar de hele provincie. En zie hierboven de opmerking van Evert Jan.
