### ISSUE TITLE
actief zijn van een contract

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#238]
Als een contract een einddatum heeft dan zou die na die datum als 'niet actief' aangemerkt moeten worden.
Als ik het scherm contracten open en ik klik in het kaartbeeld met de button [<-- informatie opvragen] op een perceel, dan komt ook een niet actief contract op dat perceel in mijn linker scherm. Dit gebeurt bijvoorbeeld op afdeling 10701G. Hier verschijnt een contract met einddatum 31-03-2014. 
Is dit de bedoeling? Moeten niet actieve contracten verwijderd worden om ze niet meer in de lijst te laten verschijnen?

**Comment by ejmeulenkamp** [comment]
Ja, het is de bedoeling dat alle contracten die in het contractenbestand staan, of ze nu afgelopen zijn, actief zijn of in de toekomst nog actief worden, gevonden kunnen worden als je via de kaart zoekt.
Als je last hebt van een afgelopen contract, en alle facturen zijn voor dat contract verstuurd, dan kun je het contract verwijderen. Het komt dan automatisch in de Contracthistorie terecht. Sinds de laatste update worden daarbij tevens de koppelingen met de documenten meegenomen. Zo kun je een oud contract altijd nog weer terugvinden, maar 'vervuilt' het het actuele bestand niet meer.

**Comment by LimburgsLandschapHarry** [comment]
ok. Dat wordt dus oude contracten verwijderen.
