### ISSUE TITLE
selectie subsidie gaat mis

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#24]
Ondanks dat ik subsidies niet gebruik ben ik er wel wat in aan het testen. Met oude subsidienummers die er nog in staan.
bij selectie van subsidienummer 00002 krijg ik de volgende foutmelding:
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET LIMBURGS LANDSCHAP

Datum / Tijd:    08-01-2015 09:52:37
Gebruiker:       Bussink, Harry                          
Programmaversie: 1.06.05
Foutnummer:      1806 
Programmaregel:  88   

Foutboodschap:
    SQL: Column 'AFD_AFD' is not found.

Methode/Programma:
    C2DESUB.SETSELECTED                                                                                                     

Code:
    

Inhoud AERROR():
    1806
    SQL: Column 'GNERRORNUMBER' is not found.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\LIMLAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DESUB.PGFPAGEREFRESH1.PAGE1.CTRSC.CMDSELECT.CLICK C:\HELPDESK\LIMLAND\C2FWMISC.VCT
    PROCEDURE C2DESUB.PGFPAGEREFRESH1.PAGE1.CTRSC.APPLY C:\HELPDESK\LIMLAND\C2FWMISC.VCT
    PROCEDURE C2DESUB.CMDZOOMTO1.CLICK C:\HELPDESK\LIMLAND\C2DESUB.SCT
    PROCEDURE C2DESUB.SETSELECTED C:\HELPDESK\LIMLAND\C2FWFRM.VCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DESUB.SETSELECTED)

Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================

**Comment by LimburgsLandschapHarry** [comment]
zie volgende subject. Bij herhaling ging de selectie wel goed. Weet niet of je iets met deze melding kunt.

**Comment by ejmeulenkamp** [comment]
Ik heb geprobeerd om de fout opnieuw op te laten treden, maar ben daar tot nu toe nog niet in geslaagd. @LimburgsLandschapHarry  Kun jij de fout opnieuw oproepen? Zo ja, graag de precieze stappen.

**Comment by HZLWannes** [comment]
@ejmeulenkamp Ik selecteer een object en kies selectie weergeven:

FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET ZEEUWSE LANDSCHAP

Datum / Tijd:    13-01-2015 08:55:28
Gebruiker:       Castelijns, Wannes                      
Programmaversie: 1.06.07
Foutnummer:      1806 
Programmaregel:  91   

Foutboodschap:
    SQL: Column 'AFD_AFD' is not found.

Methode/Programma:
    C2DESUB.SETSELECTED                                                                                                     

Code:
    

Inhoud AERROR():
    1806
    SQL: Column 'GNERRORNUMBER' is not found.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\ZEELAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DESUB.PGFPAGEREFRESH1.PAGE1.CTRSC.CMDSELECT.CLICK C:\HELPDESK\ZEELAND\C2FWMISC.VCT
    PROCEDURE C2DESUB.PGFPAGEREFRESH1.PAGE1.CTRSC.APPLY C:\HELPDESK\ZEELAND\C2FWMISC.VCT
    PROCEDURE C2DESUB.CMDZOOMTO1.CLICK C:\HELPDESK\ZEELAND\C2DESUB.SCT
    PROCEDURE C2DESUB.SETSELECTED C:\HELPDESK\ZEELAND\C2FWFRM.VCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DESUB.SETSELECTED)


Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================

**Comment by LimburgsLandschapHarry** [comment]
Hoi Evert Jan,

ik krijg de fout niet herhaald. Afsluiten maar?

**Comment by HZLWannes** [comment]
@LimburgsLandschapHarry  Nee want ik krijg hem nog wel!
