### ISSUE TITLE
selectie subsidie zoomt niet meteen in

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#25]
nogmaals subsidienummer 2 geselecteerd. selectie gaat nu wel goed, echter in het kaartbeeld zou ingezoomd moeten worden op de betreffende subsidie. Dat gebeurt niet.
Pas als ik in details ga staan en op [select alle] klik, wordt ingezoomd naar de betreffende afdelingen.

**Comment by ejmeulenkamp** [comment]
Zoals je het beschrijft is hoe het momenteel werkt. Omdat subsidies vaak over grote aantallen afdelingen en elementen gaan is ervoor gekozen om alleen vanaf het tabblad Details de bijbehorende afdelingen en elementen te tonen op de kaart. Dit wijkt iets af van andere vensters en ik kan me voorstellen dat het wat verwarrend kan zijn. Moeten we het misschien nog een keer over hebben.

**Comment by LimburgsLandschapHarry** [comment]
Als de selectie snel wordt uitgeoerd kan het gewoon gelijk aan de andere tabbladen. Als door de grote hoeveelheid de selectie traag wordt kunnen we het beter zo laten. Zoals ik al zei ik werk er niet mee dus mij maakt het niet zo veel uit.




Met vriendelijke groet,

Harry Bussink
medewerker Beheerplanning en Monitoring
Stichting het Limburgs Landschap

ps: vrijdags afwezig

Postbus 4301, 5944 ZG Arcen | bezoekadres: Rijksstraatweg 1, 5943 AA Lomm |
• 077-4737575 | 06-51130868 | • h.bussink@limburgs-landschap.nl<mailto:h.bussink@limburgs-landschap.nl> | www.limburgs-landschap.nl<http://www.limburgs-landschap.nl> |

Aan de inhoud van dit e-mailbericht kunnen geen rechten worden ontleend. De informatie is uitsluitend bestemd voor de geadresseerde. Stichting het Limburgs Landschap staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mailbericht, inclusief eventueel meegezonden bijlagen, noch voor tijdige aankomst daarvan. Stichting het Limburgs Landschap aanvaardt geen aansprakelijkheid voor schade, van welke aard ook, die verband houdt met risico's verbonden aan het elektronisch verzenden van berichten.

Van: Evert Jan Meulenkamp [mailto:notifications@github.com]
Verzonden: donderdag 8 januari 2015 10:51
Aan: IDgis/CRS2
CC: Harry Bussink
Onderwerp: Re: [CRS2] selectie subsidie zoomt niet meteen in (#25)


Zoals je het beschrijft is hoe het momenteel werkt. Omdat subsidies vaak over grote aantallen afdelingen en elementen gaan is ervoor gekozen om alleen vanaf het tabblad Details de bijbehorende afdelingen en elementen te tonen op de kaart. Dit wijkt iets af van andere vensters en ik kan me voorstellen dat het wat verwarrend kan zijn. Moeten we het misschien nog een keer over hebben.

**Comment by LimburgsLandschapHarry** [comment]
het vorige antwoord was een test; reply vanuit de mail. Zo werkt het dus ook.... ;).
