### ISSUE TITLE
overzicht bijdrage per afdeling per subsidiepakket

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#27]
werkt niet 

![capture](https://cloud.githubusercontent.com/assets/10415606/5661140/735ce9a0-9728-11e4-8aeb-7f3251c6772f.JPG)

**Comment by LimburgsLandschapHarry** [comment]
geldt voor alle overzichten met subsidies

**Comment by LimburgsLandschapHarry** [comment]
Getest: Foutmelding nog steeds aanwezig.

**Comment by ejmeulenkamp** [comment]
Overzicht "Bijdragen per afdeling per subsidiepakket"  wordt gegenereerd in Excel. Dit kan dus alleen lokaal getest worden. Lokaal getest en het werkt nu zonder fouten.
