### ISSUE TITLE
overzicht oppervlakte per object foutmelding

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#28]
![capture](https://cloud.githubusercontent.com/assets/10415606/5661194/110ac0b4-9729-11e4-98b0-05145112d908.JPG)

**Comment by ejmeulenkamp** [comment]
Onderaan de overzichten "Oppervlakte per object, beheerregio en district" wordt een totaaltelling gemaakt van alle oppervlaktes. Daaronder wordt apart vermeld hoeveel van die oppervlakte in beheer is. Mag dit veranderd worden naar alleen de oppervlaktes die in beheer zijn optellen, dus zonder aparte vermelding van de oppervlakte die in beheer is?

**Comment by LimburgsLandschapHarry** [comment]
wellicht in overleg maar even bespreken met een voorbeeld erbij, want zo snap ik het niet.
Mijn vraag kwam vanuit het venster afdelingen. Het lijkt erop dat het antwoord betrekking heeft op het venster kad.objecten.
Zie bijgevoegd knipsel vanuit overzichten kad.objecten.

[cid:image001.png@01D02F4B.A451A090]

Vanuit het venster Afdelingen krijg ik normaal het volgende overzicht. Geen oppervlakte in beheer erbij dus.
[cid:image002.png@01D02F4B.A451A090]

**Comment by LimburgsLandschapHarry** [comment]
Bovenstaand ging iets mis met de plaatjes.

overzicht vanuit afdelingen
![overzicht objecten vanuit afdelingen](https://cloud.githubusercontent.com/assets/10415606/5723239/d682197e-9b42-11e4-8d0f-e8ea5e16376a.JPG)

overzicht vanuit kad.objecten
![overzicht objecten vanuit kad-objecten](https://cloud.githubusercontent.com/assets/10415606/5723275/01c6fbea-9b43-11e4-9e2c-b0e58a7ad5eb.JPG)

**Comment by ejmeulenkamp** [comment]
@LimburgsLandschapHarry  Zou je in versie 1.06.10 nog eens willen testen of de fout in het overzicht "Oppervlakte per object" opgelost is?

**Comment by LimburgsLandschapHarry** [comment]
overzicht doet het.
