### ISSUE TITLE
overzichten per terreintype per ..

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#29]
volgende drie overzichten werken niet.
![capture](https://cloud.githubusercontent.com/assets/10415606/5661218/7c240d92-9729-11e4-9e0b-82be99e6daa6.JPG)

**Comment by ejmeulenkamp** [comment]
Deze drie overzichten kunnen alleen in Excel gegenereerd worden. Zie ook mijn antwoord in issue #30.
Het testen van deze overzichten zal in jullie eigen testomgeving moeten.

**Comment by LimburgsLandschapHarry** [comment]
moeten we deze niet open laten staan om in beeld te hebben als we op eigen server gaan testen.
