### ISSUE TITLE
overzicht Oppervlakte per terreintypegroep per beheerregio foutmelding

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#30]
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET LIMBURGS LANDSCHAP

Datum / Tijd:    08-01-2015 11:28:57
Gebruiker:       Bussink, Harry                          
Programmaversie: 1.06.05
Foutnummer:      1733 
Programmaregel:  54   

Foutboodschap:
    Class definition EXCEL.APPLICATION is not found.

Methode/Programma:
    C2EXCEL                                                                                                                 

Code:
    ASTACKINFO(laStackInfo)

Inhoud AERROR():
    1733
    Class definition GNERRORNUMBER is not found.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\LIMLAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEAFD.CMDPRINT.CLICK C:\HELPDESK\LIMLAND\C2FWFRM.VCT
    PROCEDURE CUSC2MENU.DOFORM C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE CUSC2FORMS.DOFORM C:\HELPDESK\LIMLAND\C2FW.VCT
    PROCEDURE FRMC2REPORTCATALOG.CMDRUN.CLICK C:\HELPDESK\VMP2005\XLIB\XXFWFRM.VCT
    PROCEDURE FRMC2REPORTCATALOG.RUNREPORT C:\HELPDESK\LIMLAND\C2FWFRM.VCT
    PROCEDURE FRMDIVTOT.INIT C:\HELPDESK\VMP2005\XLIB\XXFWMISC.VCT
    PROCEDURE FRMDIVTOT.PREPAREDATA C:\HELPDESK\LIMLAND\C2.VCT
    C2EXCEL.FXP
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2EXCEL)

Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    printen naar beeldscherm van het overzicht Oppervlakte per terreintypegroep per beheerregio

**Comment by ejmeulenkamp** [comment]
Sommige overzichten kunnen in de centrale testomgeving niet getest worden omdat ze alleen naar Excel uitgevoerd kunnen worden. In de centrale testomgeving is Excel echter niet aanwezig, omdat dit een complete Office-licentie vereist.
Als er dus een foutmelding komt met "Class definition EXCEL.APPLICATION is not found.", dan komt dat omdat Excel er niet is. Deze overzichten kunnen getest worden in de (toekomstige) testversie op jullie eigen server.
