### ISSUE TITLE
foutmelding Oppervlakte per terreintypegroep per Object

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#32]
![capture](https://cloud.githubusercontent.com/assets/10415606/5661320/bc38bab2-972a-11e4-84e0-d98814af7623.JPG)

**Comment by ejmeulenkamp** [comment]
Ook bij dit soort overzichten alleen de beheerde oppervlakte optellen?

**Comment by ejmeulenkamp** [comment]
De fout zou in versie 1.06.10 opgelost moeten zijn. @LimburgsLandschapHarry Kun je hem dan nog eens testen?

**Comment by LimburgsLandschapHarry** [comment]
2 x geprobeerd, gaat nog steeds fout.. 

FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET LIMBURGS LANDSCHAP

Datum / Tijd:    05-02-2015 12:39:10
Gebruiker:       Bussink, Harry                          
Programmaversie: 1.06.10
Foutnummer:      1733 
Programmaregel:  54   

Foutboodschap:
    Class definition EXCEL.APPLICATION is not found.

Methode/Programma:
    C2EXCEL                                                                                                                 

Code:
    ASTACKINFO(laStackInfo)

Inhoud AERROR():
    1733
    Class definition GNERRORNUMBER is not found.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\LIMLAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEAFD.CMDPRINT.CLICK C:\HELPDESK\LIMLAND\C2FWFRM.VCT
    PROCEDURE CUSC2MENU.DOFORM C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE CUSC2FORMS.DOFORM C:\HELPDESK\LIMLAND\C2FW.VCT
    PROCEDURE FRMC2REPORTCATALOG.CMDRUN.CLICK C:\HELPDESK\VMP2005\XLIB\XXFWFRM.VCT
    PROCEDURE FRMC2REPORTCATALOG.RUNREPORT C:\HELPDESK\LIMLAND\C2FWFRM.VCT
    PROCEDURE FRMDIVTOT.INIT C:\HELPDESK\VMP2005\XLIB\XXFWMISC.VCT
    PROCEDURE FRMDIVTOT.PREPAREDATA C:\HELPDESK\LIMLAND\C2.VCT
    C2EXCEL.FXP
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2EXCEL)


Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    in afdelingen, object = 102, oppervlakte per terrientypegroep per object van totale beheer,

**Comment by ejmeulenkamp** [comment]
Deze fout geeft aan dat Excel niet aanwezig is. Je zou het overzicht even kunnen testen op jullie eigen systeem. Beide versies zijn nu gelijk en daar is Excel wel aanwezig.

**Comment by LimburgsLandschapHarry** [comment]
het werkt lokaal
