### ISSUE TITLE
kaart elementen bouwt niet / traag op 

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#34]
de kaart bouwde niet op. met een leeg scherm rechts een selectie van object 102 gemaakt. Dit leverde een foutmelding op. Bij het intypen van het commentaar bij de foutmelding verscheen alsnog het scherm met kaart. Gevolg is dat ik bij de foutmelding niet meer in het commentaar schermpje kan. Het venster Elementen sluiten werkt niet meer. Foutmelding sluiten werkt ook niet meer. CRS helemaal afsluiten (rechtsboven) werkt ook niet. Krijg de melding cannot quit visual foxpro

![capture](https://cloud.githubusercontent.com/assets/10415606/5661541/5a4c1a26-972d-11e4-9ba6-4850cd9ac529.JPG)

**Comment by LimburgsLandschapHarry** [comment]
na in de processen crs te hebben afgesloten opnieuw elementen geopend. Totaal kaartbeeld komt wel in beeld. Selectie van object 102 gemaakt. kaart zoomt niet in. 'Select alle' aangeklikt: kaart zoomt nog steeds niet in. Button [inzoomen] blijft uitgegrijsd.
In het algemeen kan worden gesteld dat de opbouw van kaartlaag [elementen] zeer traag verloopt. Moet sneller.
Door traagheid lijkt het erop dat alleen de eerste [select huidige] werkt. Daarna duurt het 10-15 seconden als ik een ander element selecteer en [ select huidige] klik voordat er op dat element wordt ingezoomd.
[select alle] werkt helemaal niet. In ieder geval niet binnen 2 minuten wachten.

**Comment by ejmeulenkamp** [comment]
Linda, Ik heb het vermoeden dat de viewer even niet bereikbaar was vanwege de melding: "Member DOCUMENT does not evaluate to an object" Kan zoiest voorkomen? EN zo ja, moet ik daar dan een beveiliging voor inbouwen?

**Comment by LindaVels** [comment]
Bij controle op de database bleek dat de spatial indexen van een aantal ruimtelijke tabellen niet (meer) aanwezig waren. Dit was het geval voor database Limburg  voor alle ruimtelijke tabellen met uitzondering van afdelingen. Dit verklaart een deel van de traagheid. 

Echter: Ik heb een query die wordt gebruikt in de applicatie direct op de database proberen uit te voeren en deze deed er 16 sec over om 18 rijen te selecteren!!!

Ik denk dat dit komt door het gebruik van subqueries. @ejm: kun jij eens kijken of deze query niet te optimaliseren valt?

In database KROON:
SELECT Puntelementen.Element AS id, Puntelementen.Element, Puntelementen.ogr_geometry AS geom FROM Puntelementen, elm, eso WHERE Puntelementen.Element = elm.elm_code AND eso.eso_pk = elm.elm_eso_fk AND elm_pk IN ( SELECT elm_pk FROM elm, eso, etp WHERE eso.eso_pk = elm.elm_eso_fk AND etp.etp_pk = eso.eso_etp_fk AND elm.elm_pk IN (SELECT elm.elm_pk FROM elm, ael, obj, afd WHERE obj.obj_pk = afd.afd_obj_fk AND ael.element = elm.elm_code AND obj.obj_code + afd.afd_afd = ael.afdeling AND RTRIM(LTRIM(obj.obj_code)) = 'G') AND UPPER(eso_ehd) = 'ST' ) AND UPPER(eso_ehd) = 'ST'

**Comment by LindaVels** [comment]
Aanvulling:  Bovenbeschreven query wordt gebruikt bij "Select Alle" en "Toon Selectie" in het elementen scherm

**Comment by HZLWannes** [comment]
Ik zie nog steeds een leeg scherm rechts (geen kaart), bij alle modules.

**Comment by ejmeulenkamp** [comment]
Er zijn verbeteringen aangebracht in de selectie-opdrachten, waardoor het selecteren van elementen en het tonen in de viewer sneller zou moeten werken.

**Comment by HZLWannes** [comment]
Er is blijkbaar een fout bij mij (in crs zeeland) opgetreden ik zie helemaal geen kaart  scherm meer. In geen van de modules.
![image](https://cloud.githubusercontent.com/assets/10400913/5702814/6705277e-9a5e-11e4-958d-b22b9c1c90e4.png)

**Comment by ejmeulenkamp** [comment]
Linda, zou jij hier naar willen kijken?

**Comment by LindaVels** [comment]
Voor Zeeland werkt de kaart inmiddels ook weer. @HZLWannes: zou je kunnen hertesten

**Comment by LimburgsLandschapHarry** [comment]
kaart werkt, zoomt in binnen acceptabele tijd (nog niet al te snel). Ook nog een paar kaartlagen met 2de verdieping uitgezet (transacties en kadaster) voor minder laadwerk / laadtijd.

**Comment by ejmeulenkamp** [comment]
Hoi Linda, Ik weet het niet helemaal zeker of de performance minder wordt als de onderstaande velden van het type varchar(max) zijn, maar om twijfel uit te sluiten lijkt het me het beste dat de onderstaande velden het aangegeven type krijgen. Dit zal waarschijnlijk in ogr2ogr moeten gebeuren, zoals je op de testbijeenkomst zei?:
 Afdelingen.afdeling char(10)
 Lijnelementen.element char(10)
 Puntelementen.element char(10)
 Gebouwen.gebouw char(20)
 Grondnummers.grondnr char(13)
 Gemeenten.gemeente char(50)

**Comment by ejmeulenkamp** [comment]
De velden worden nu in de AddIn van Kragten aangemaakt.
