### ISSUE TITLE
Waarnemingen selecteren

### ISSUE THREAD

**Issue by HZLWannes** [IDgis/CRS2#36]
De parameters: district, beheerregio en object werken nog niet. De anderen lijken goed te werken. Ik krijg de volgende foutmelding.
![image](https://cloud.githubusercontent.com/assets/10400913/5663478/cb5bc6fc-9747-11e4-9242-d3290ae442de.png)

SELECT wrn.*, loc.*, opr.*, mth.*, soo.*, sgp.*, grp.*, hgp.*, abu.*, gsl.*, ddo.*, dom.*, std.*, vbp.*, vbs.*, obj.obj_code, obj.obj_afk, obj.obj_oms, bhr.*, dis.* FROM obj, bhr, dis, loc, mth, opr, sgp, grp, hgp,abu, gsl, ddo, dom, std, vbp, vbs, wrn, soo WHERE abu_pk = wrn_abu_fk AND gsl_pk = wrn_gsl_fk AND ddo_pk = wrn_ddo_fk AND dom_pk = wrn_dom_fk AND std_pk = wrn_std_fk AND vbp_pk = wrn_vbp_fk AND vbs_pk = wrn_vbs_fk AND loc_pk = wrn_loc_fk AND opr_pk = wrn_opr_fk AND mth_pk = wrn_mth_fk AND obj_pk = wrn_obj_fk AND bhr_pk = obj_bhr_fk AND dis_pk = bhr_dis_fk AND soo_pk = wrn_soo_fk AND sgp_pk = soo_sgp_fk AND grp_pk = sgp_grp_fk AND hgp_pk = grp_hgp_fk AND  ( TRIM(dis_oms) = 'Noord' )

**Comment by ejmeulenkamp** [comment]
Werkt het selecteren van waarnemingen via object, beheerregio en/of district nu wel?

**Comment by HZLWannes** [comment]
Prima, ook het top-down selecteren werkt prima (als ik walcheren selecteer, laat hij alleen nog die objecten zien). Perfect.

**Comment by HZLWannes** [comment]
![image](https://cloud.githubusercontent.com/assets/10400913/5898108/55878688-a54c-11e4-9e81-38cd4497dbe2.png)
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET ZEEUWSE LANDSCHAP

Datum / Tijd:    26-01-2015 11:13:28
Gebruiker:       Castelijns, Wannes                      
Programmaversie: 1.06.09
Foutnummer:      52   
Programmaregel:  133  

Foutboodschap:
    No table is open in the current work area.

Methode/Programma:
    C2DEWRN.PGFPAGEREFRESH1.PAGE1.CTRSC.CMDOBJ.CLICK                                                                        

Code:
    

Inhoud AERROR():
    52
    No table is open in the current work area.
    00000001: Incorrect function
    
    
    
    

Programmapad:
    C:\HELPDESK\ZEELAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWRN.PGFPAGEREFRESH1.PAGE1.CTRSC.CMDOBJ.CLICK C:\HELPDESK\ZEELAND\C2DEWRN.SCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DEWRN.PGFPAGEREFRESH1.PAGE1.CTRSC.CMDOBJ.CLICK)


Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    

@ejmeulenkamp Waarneming module, tabblad lijst, selecteren object. Dit was opgelost, maar omdat ik de fout kreeg in de werkversie op onze eigenserver dacht ik het hier ook weer te proberen...

**Comment by HZLWannes** [comment]
@ejmeulenkamp dezelfde fout blijft optreden, nu alleen niet bij de knop objecten, maar wel als je daarna op de knop regelingen klikt.
![image](https://cloud.githubusercontent.com/assets/10400913/6063405/3b8e821e-ad57-11e4-8d72-ad04aaf6bbbc.png)

**Comment by HZLWannes** [comment]
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET ZEEUWSE LANDSCHAP

Datum / Tijd:    05-02-2015 16:50:25
Gebruiker:       Castelijns, Wannes                      
Programmaversie: 1.06.10
Foutnummer:      52   
Programmaregel:  137  

Foutboodschap:
    No table is open in the current work area.

Methode/Programma:
    C2DEWRN.PGFPAGEREFRESH1.PAGE1.CTRSC.CMDREG.CLICK                                                                        

Code:
    

Inhoud AERROR():
    52
    No table is open in the current work area.
    00000001: Incorrect function
    
    
    
    

Programmapad:
    C:\HELPDESK\ZEELAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWRN.PGFPAGEREFRESH1.PAGE1.CTRSC.CMDREG.CLICK C:\HELPDESK\ZEELAND\C2DEWRN.SCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DEWRN.PGFPAGEREFRESH1.PAGE1.CTRSC.CMDREG.CLICK)


Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
