### ISSUE TITLE
Foutmelding bij opvragen standaard afd. lijst.

### ISSUE THREAD

**Issue by gelderland** [IDgis/CRS2#37]
Het opvragen van een overzicht  vanuit afdelingen, lijst, lijsten van afdelingen, standaard afd. lijst, waarbij ik het filter beheerregio gebruik levert de volgende melding op:
![foutmelding overzicht lijsten van afdelingen](https://cloud.githubusercontent.com/assets/10397485/5680093/7d545e44-9808-11e4-8e47-f8cf418c697c.png)
Overigens gebeurt hetzelfde in CRS2 versie 1.06.04

**Comment by gelderland** [comment]
Ook andere overzichten van afdelingen leveren vergelijkbare meldingen op, bijvoorbeeld het overzicht "bijdrage per afdeling per subsidiepakket"
![foutmelding bijdrage afdeling per subsidiepakket en andere overzichten](https://cloud.githubusercontent.com/assets/10397485/5680167/b93ffdb8-9809-11e4-91a6-a6497306c354.png)

**Comment by ejmeulenkamp** [comment]
Fout is opgelost. Werkt het (in versie 1.06.08)?

**Comment by gelderland** [comment]
Het werkt inderdaad.
