### ISSUE TITLE
Foutmelding bij opvragen oppervlakte per object

### ISSUE THREAD

**Issue by gelderland** [IDgis/CRS2#38]
Foutmelding ontstaat bij het opvragen vanuit de overzichtencatalogus van het overzicht "Oppervlakte per object", vanuit afdelingen, tabblad lijst.
![oppervlakte per object](https://cloud.githubusercontent.com/assets/10397485/5680242/d3fe6d5a-980a-11e4-87f6-e1c5aec1a3ac.png)
Dit overzicht werkt in CRS2 1.06.04 wel zonder problemen.

Binnen de overzichten op te vragen vanuit afdelingen zijn er nog verschillende vergelijkbare meldingen.

**Comment by ejmeulenkamp** [comment]
Dit is dezelfde melding als issue #28
