### ISSUE TITLE
Foutmelding bij opvragen actielijst, contracten

### ISSUE THREAD

**Issue by gelderland** [IDgis/CRS2#39]
Het opvragen van een actielijst waarbij ook afspraken worden geselecteerd levert een foutmelding op.
![actielijst inclusief selectie afspraken](https://cloud.githubusercontent.com/assets/10397485/5680400/2ce3934e-980d-11e4-8361-fdef2e30620e.png)

**Comment by gelderland** [comment]
Ook het opvragen van een afsprakenlijst vanuit de overzichtencatalogus bij contracten levert een foutmelding op.
![foutmelding opvragen afsprakenlijst bij contracten](https://cloud.githubusercontent.com/assets/10397485/5680458/d594155e-980d-11e4-95da-3c632b5786ec.png)

**Comment by ejmeulenkamp** [comment]
Werkt het in versie 1.06.08 wel?
