### ISSUE TITLE
houtoogst, muteren taxeenheid, toewijzen aan partijnr: Fatale fout

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#41]

**Comment by ejmeulenkamp** [comment]
Beste René,
Als ik via Houtoogsten > Details > Raadplegen / Wijzigen naar het venster "Houtoogstregel raadplegen / muteren" ga, dan kan ik een bestaand pertijnummer via de keuzelijst veranderen. Er verschijnt geen foutmelding.
Kun je preciezer omschrijven waar het mis gaat?

**Comment by rkcolthof** [comment]
Het ging om kolomsgewijs muteren, maar het problem doet zich nu niet meer voor. Ik zal het plaatje er nog even bijgeven. Ik kan me herinneren dat het fout ging bij het invoeren van een partijnummer, ook bij mutatie van een enkele record.
![capture png_crs2_fout12_kroondomein_ro](https://cloud.githubusercontent.com/assets/10460914/5724449/e3e1842a-9b4b-11e4-952e-a804b9b1766d.PNG)
![capture png_crs2_fout12_enkelerecord_kroondomein_ro](https://cloud.githubusercontent.com/assets/10460914/5724487/33e605ea-9b4c-11e4-9547-b25cf112b915.PNG)

**Comment by rkcolthof** [comment]
Ik zie dat het fout gaat wanneer je niet via verrekijkertje selecteerd en/of een verkeerd partijnummer manueel invoert.

![capture png_houtoogst_onbekend partijnummer invoeren](https://cloud.githubusercontent.com/assets/10460914/5724534/9ff55704-9b4c-11e4-966c-2d001b0fcc0a.PNG)

**Comment by ejmeulenkamp** [comment]
Ik heb de fout gevonden die optrad tijdens het koppelen van een partijnummer aan een houtoogstregel. Vanaf versie 1.06.09 zou het foutloos moeten werken. Ook het ontkoppelen van een partijnummer, dus het partijnummer leeg laten zou nu moeten werken.

**Comment by rkcolthof** [comment]
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
KROONDOMEIN HET LOO

Datum / Tijd:    03-02-2015 16:19:31
Gebruiker:       Olthof, Rene                            
Programmaversie: 1.06.09
Foutnummer:      26   
Programmaregel:  284  

Foutboodschap:
    Table has no index order set.

Methode/Programma:
    C2PKPTY.INIT                                                                                                            

Code:
    

Inhoud AERROR():
    26
    Table has no index order set.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\KROON\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEHOG.PGFPAGEREFRESH1.PAGE2.CTRHOR.GRDSUB.DBLCLICK C:\HELPDESK\KROON\C2DEHOG.SCT
    PROCEDURE GRDC2DATAENTRY.DBLCLICK C:\HELPDESK\KROON\C2FWGRD.VCT
    PROCEDURE C2DEHOGHOR.TXTPARTIJ.LOSTFOCUS C:\HELPDESK\KROON\C2DEHOGHOR.SCT
    PROCEDURE C2PKPTY.INIT C:\HELPDESK\VMP2005\XLIB\XXFWPICK.VCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2PKPTY.INIT)


Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    Deze fout treedt op wanneer je een niet bestaand partijnummer handmatig (niet via verrekijker) invult bij een taxatieeenheid

**Comment by rkcolthof** [comment]
Dit is natuurlijk een beetje onheus gebruik, maar het geeft nog steeds deze foutmelding.

**Comment by rkcolthof** [comment]
sorry ik heb deze fout opnieuw toegevoegd omdat ik deze niet meer kon vinden.
