### ISSUE TITLE
Houtoogst, toevoegen taxatie eenheid aan bestaande selectie kan niet

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#42]
Bestaande houtoogst met diverse taxatie eenheden. Ik wil hier wat taxatie eenheden aan toevoegen. Dit kan niet. (kon eerder wel)

**Comment by ejmeulenkamp** [comment]
Welke handelingen kun je niet uitvoeren of welke fout treedt er op als je taxatieeenheden aan een bestaande houtoogst toe wilt voegen?

**Comment by rkcolthof** [comment]
fout doet zich niet meer voor, maar denk dat het te maken had met incomplete db.
