### ISSUE TITLE
inzoomen op één afdeling

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#45]
Inzoomen op één afdeling is vaak te gedetailleerd. Het zou handig zijn om standard tot een bepaaldzoomniveau in te zoomen. Wanneer je dan verder wil inzoomen kan dat altijd. Nu moet je iedere keer weer uitzoomen om overzicht te krijgen.

**Comment by ejmeulenkamp** [comment]
In het venster Opties kun je op het tabblad GIS-Koppelingen het zoomniveau instellen (max en min). Hierdoor hou je het overzicht.

**Comment by rkcolthof** [comment]
oké, is gelukt en dat werkt uitstekend. bedankt.
