### ISSUE TITLE
afdelingen, selectie

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#47]
dubbele selectie aan de hand van kiemjaar, menging en t-bomen niet zinvol
jaarblok, ook twee heer hetzelfde (niet storend)

**Comment by ejmeulenkamp** [comment]
Beste René, kun je nader omschrijven wat je met dit issue bedoelt? Ik begrijp je vraag niet.

**Comment by rkcolthof** [comment]
Het gaat om het selectievenster waar je twee sdelectievakjes van hetzelfde item naast elkaar hebt. Dat is handig wanneer je wekt met een code en een omschrijving, maar in de omschreven gevallenis dit niet handig omdat twee x hetzelfde geselecteerd wordt. Wat betreft kiemjaar zou het bijvoorbeeld wel wat toevoegen wanneer jeperiodes van 10 of 20 jaar zou onderscheiden. En zo zou je ook bij menging met niveaus kunnen werken.

**Comment by ejmeulenkamp** [comment]
De selectie op kiemjaar, menging en T-bomen is bedoeld als "Van - Tot en met" Het eerst vakje is de Van-waarde en het tweede de TotEnMet-waarde. Dit in tegenstelling tot de rij met selectiecriteria aan de rechterkant van het selectievenster (object, Beheertype, etc.) Hier kun je een code selecteren als je de code kent of een omschrijving als je liever daar mee werkt.
Is dit een verhelderend antwoord?

**Comment by rkcolthof** [comment]
zeer verhelderend, beetje dom..... sorry
