### ISSUE TITLE
weekstaat, nieuw jaar invoeren

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#48]
in weekstaat nieuw jaar invoeren bij medewerker: fatale fout

**Comment by ejmeulenkamp** [comment]
Heb je een beschrijving van de fout tijdens het invoeren van een nieuw jaar bij een weekstaat? (kopieer naar klembord, in Paint bestand plakken, opslaan, in Github-issue opnemen)
En wat zijn je handelingen vlak voor de fout?

**Comment by rkcolthof** [comment]
Ik heb de plaatsjes in Pictures gezet. Toevoegen weekstaat, nieuw

FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
KROONDOMEIN HET LOO

Datum / Tijd:    13-01-2015 11:38:08
Gebruiker:       Olthof, Rene                            
Programmaversie: 1.06.07
Foutnummer:      12   
Programmaregel:  44   

Foutboodschap:
    Variable 'UJR_UTAR' is not found.

Methode/Programma:
    C2DEWKS.ADDAFTERAPPENDBLANK                                                                                             

Code:
    

Inhoud AERROR():
    12
    Variable 'GNERRORNUMBER' is not found.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\KROON\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWKS.CMDADD.CLICK C:\HELPDESK\VMP2005\XLIB\XXFWCTRL.VCT
    PROCEDURE C2DEWKS.ADDACTION C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWKS.ADDAFTERAPPENDBLANK C:\HELPDESK\KROON\C2DEWKS.SCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DEWKS.ADDAFTERAPPENDBLANK)


Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    In module weekstaten kies ik toevoegen weekstaat, nieuwe, krijg eerst een melding dat er iets niet gevonden wordt daarna vastloper.

**Comment by ejmeulenkamp** [comment]
Het aanmaken van een nieuwe weekstaat leverde een fout op omdat er nog geen enkele weekstaat van jou in het systeem zit. CRS2 probeert uit te vinden voor welk jaar de nieuwe weekstaat aangemaakt moet worden. Hierbij had ik geen rekening gehouden met bovenstaande situatie. Vanaf versie 1.06.08 wel. Werkt het dan wel goed?
