### ISSUE TITLE
partijen

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#49]
partijoverzicht boomsoort en vak: bij het totaal per vak valt een deel vh vaknr weg:

**Comment by ejmeulenkamp** [comment]
In de Opties van CRS2 stond per abuis ingesteld dat een vaknummer uit 2 tekens bestaat. Dit moet bij jullie 3 tekens zijn. Ik heb het aangepast en nu wordt het volledige vaknummer wel getoond.
Volgens mij het het issue hiermee opgelost.
