### ISSUE TITLE
partijen

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#50]
taxatie formulier en partijoverzicht en inschrijfformulier: Bij alle groepeerniveaus worden de kopgegevens getoont, waardoor het geheel rommelig wordt. liever de kopgegevens per blad.

**Comment by ejmeulenkamp** [comment]
Ik heb het formulier zodanig aangepast dat alleen per boomsoort de kopgegevens afgedrukt worden (en bovenaan iedere nieuwe pagina. Dit is een stuk overzichtelijker. Als het per pagina moet, dan kost dat iets meer moeite, maar dat kan eventueel ook nog wel. Dan hoor ik het graag.

**Comment by rkcolthof** [comment]
Ja, het zou veel overzichtelijker zijn wanneer het per pagina is. Bij het taxatieformulier is het trouwens nog niet aangepast. Bij het inschrijfformulier moet er gegroepeerd worden op boomsoort en diameterklasse. De afdelingen/vakken moet niet op worden gegroepeerd.

**Comment by ejmeulenkamp** [comment]
Wil je nog eens kijken of de overzichten nu kloppen en naar wens zijn?

**Comment by ejmeulenkamp** [comment]
Ik bedoel natuurlijk met NU, zodra versie 1.06.09 geïnstalleerd is.

**Comment by rkcolthof** [comment]
Heb er per ongeluk een nieuw issue van gemaakt alleen voor taxatieformulier. Rest is in orde zo. (soms nog wat te veel streepjes, maar ok
