### ISSUE TITLE
afdelingen selectie

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#51]
het zou handig zijn als je bij de selectie vh jaarblok zou kunnen zien welk jaar het volgens het schema gedund moet worden.

**Comment by ejmeulenkamp** [comment]
Waarschijnlijk bedoel je het eerstvolgende jaar waarop het jaarblok gedund moet worden, gezien vanaf 'vandaag'. Dat is echter niet mogelijk Ik kan wel het startjaar en de cyclus van het jaarblok tonen. Is dat werkbaar?

**Comment by rkcolthof** [comment]
oke
