### ISSUE TITLE
Maatregelgroepen verdwijnen, andere is dubbel

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#53]
Ik heb een aantal maatregelgroepen aangemaakt in stambestanden en bewaard. In het overzicht zie ik een aantal niet meer staan en een andere staat er dubbel in.

**Comment by rkcolthof** [comment]
Bij afsluiten en opnieuw oproepen stambestanden zitten de groepen er wel in. (plaatjes in Kroondomein/Pictures)

**Comment by ejmeulenkamp** [comment]
Ik kan niet in de map Kroondomein/Pictures kijken. Dit is een persoonlijke map. Zou je het plaatje toe willen voegen in het comment in GitHub. Onder het Write-venster staat een zinnetje "Attach images by .... or selecting them." Als je op 'selecting them' klikt, dan wordt het plaatje (of de plaatjes) toegevoegd in de vorm van wat rare tekstjes. Echter als je op 'PreView' klikt of het comment opslaat (via de groene knop [Comment]) dan verschijnen de plaatjes. Dat scheelt bovendien een hoop gezoek voor mij. Ik moet echt op volle toeren draaien om alle issues op te volgen...

**Comment by rkcolthof** [comment]
![capture png_maatregelgroepen aanmaken in stambest](https://cloud.githubusercontent.com/assets/10460914/5724210/7416e848-9b4a-11e4-9a9b-426fbc88e4d5.PNG)

**Comment by ejmeulenkamp** [comment]
Is dit nog steeds zo? Ik heb diverse nieuwe maatregelgroepen aangemaakt, met of zonder gekoppelde maatregelsoorten. Het lukt me niet om de beschreven fouten te reproduceren. Als het jou nog wel lukt, kun je dan kort aangeven welke handelingen je uitvoert?

**Comment by ejmeulenkamp** [comment]
@rkcolthof Zou je nog eens willen testen of er nog steeds maatregelgroepen verdwijnen? Zo ja, welke handeling voer je dan precies uit? Ik krijg het namelijk niet voor elkaar.

**Comment by rkcolthof** [comment]
Ik heb het opnieuw geprobeerd en krijg geen gekke dingen meer. Opgelost in huidige versie zak maar zegguh
