### ISSUE TITLE
bij toevoegen werkplanregel selecteer een beheertype hangt het systeem

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#54]
Probeer nieuw werkplan op te stellen, toevoegen werkplanregels, beheertype, selecteer een beheertype: system hangt zonder foutmelding. Kan vensters niet meer sluiten.

**Comment by ejmeulenkamp** [comment]
Nadat een werkplanregel aangemaakt is, kun je inderdaad via de knop [Toevoegen] afdelingen toevoegen. Hier verschijnt inderdaad een foutmelding. Deze zal ik proberen op te lossen.

Je kunt echter ook de knop [Vullen] gebruiken. Hiermee worden in een keer alle afdelingen opgezocht van het beheertype dat je geselecteerd hebt voor de werkplanregel. Ik heb al twee fictieve werkplanregels voor jullie aangemaakt.
Ik heb gemerkt dat de knop [Vullen] pas werkt nadat er eerst bewaard is. Dit zal ik proberen op te lossen.

**Comment by ejmeulenkamp** [comment]
De fout die optrad na het klikken op de knop [Toevoegen] (van afdelingen in de werkplanregel) is opgelost. @rkcolthof : kun je het aanmaken van een nieuwe werkplanregel nog eens testen zodra versie 1.06.10 geïnstalleerd is? Ik zal iedereen op de hoogte brengen zodra deze versie er is.

**Comment by ejmeulenkamp** [comment]
De knop [Vullen] is nu ook beschikbaar zonder dat je eerst moet bewaren. Ik hoop dat dat bij jou dan ook zo is.
