### ISSUE TITLE
In stambestanden afdelingen/objecten zie ik geen objecten in de lijsat

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#56]
De objecten zijn niet zichtbaar, maar wanneer ik een bestaand object invoer kan dat niet uiteraard. Zouden niet alle objecten standard te zien moeten zijn?

**Comment by ejmeulenkamp** [comment]
In het venster Objecten moet je altijd eerst een selectie maken voordat je iets ziet. Je kunt bijvoorbeeld de selectie "Beheerder = 'KROON'" maken en daarna op [Toon selectie F4] klikken. Al jullie objecten worden dan getoond.
Is je vraag hiermee beantwoordt?

**Comment by rkcolthof** [comment]
opgelost
