### ISSUE TITLE
weekstaten: Nieuwe invoer kan geen object kiezen

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#58]

**Comment by rkcolthof** [comment]
![capture png_weekstaten_object](https://cloud.githubusercontent.com/assets/10460914/5755787/e212e2ca-9ca8-11e4-8ef9-e45bc54b65e6.PNG)
Bij beschrijving ging wat mis toen ik plaatje probeerde bij te voegen.

Ik probeer in weekstaten een record toe te voegen voor mezelf. Daarbij moet je een object selecteren. Er zijn geen objecten beschikbaar.

Ik zal de werking van weekstaten wel niet doorgronden. Wij hebben dit nooit gebruikt, maar het lijkt me op zich wel handig dit te doen in het kader vd certificering/werkplannen/ etc

**Comment by ejmeulenkamp** [comment]
In het vensters weekstaten komen twee informatiestromen bij elkaar:
Aan de ene kant het vastleggen van bestede manuren, machine-uren, materialen, en kilometers voor projecten (bovenste tabel 'Weekstaatregels projecten'). Er kan alleen geboekt worden op begrootte posten in de week waarover de weekstaat gaat (zie begin- en einddatum project). Bovendien moet er in de begrotingsregel een vinkje staan bij "Boeken via weekstaat toestaan" (of zoiets) en moet je opgenomen zijn in de lijst met medewerkers op het tabblad Koppelingen van het project.
Aan de andere kant het vastleggen van bestede manuren, machine-uren, materialen, en kilometers voor werkplanregels (onderste tabel). Er kan alleen geboekt worden op geplande maatregelen in het jaar waarover de weekstaat gaat.
Ik hoop dat je zo kunt verklaren waarom er geen object geselecteerd kan worden.

**Comment by ejmeulenkamp** [comment]
Beste René, heb je al een werkplanregel aangemaakt en daarna in een weekstaat van het jaar waarvoor de werkplanregel opgenomen is een weekstaat aangemaakt? En kon je toen een object kiezen?
