### ISSUE TITLE
elementen, invoer elementnummer

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#60]
Bij het invoeren van een nieuw element moet je een elementnr invoeren. Dit is toch gewoon een system ID waar de gebruiker niets aan heft? Kan dit niet beter automatisch op de achtergrond worden ingevuld?

**Comment by rkcolthof** [comment]
Oke Ik snap hem al: Je voert het eerst in in GIS met een elementnummer. Ja dat blijft erg omslachtig, of ik snap het niet.

**Comment by ejmeulenkamp** [comment]
Normaalgesproken gaat het bij elementen als volgt: Je tekent eerst een element in GIS (lijn of punt) en geeft het een naam/nummer via de extensie van Tom. Omdat je in CRS2 ook gegevens van het element vast wilt leggen (vergelijkbaar met afdelingen) moet het element ook in de elemententabel van CRS2 aangemaakt worden. Om de juiste geometrie bij het juiste (CRS2)-element te kunnen tonen, hebben we afgesproken dat de elementcode in beide tabellen hetzelfde moet zijn.
Vanuit een pure GIS-benadering zou je de kenmerken van het element als velden op willen nemen in de tabellen waarin ook de geografie staat. Zo is CRS2 echter niet ontwikkeld.

**Comment by rkcolthof** [comment]
Hallo Evert Jan,

Het is voor het eerst dat ik van de gisextentie van Tom hoor. Ik vraag me dan ook af of die bij ons geïnstalleerd is en hoe het werkt. Ik zal het bij ons navragen.

Gr René Olthof

René Olthof
Boswachterij beheerder

Kroondomein Het Loo
Hoog Soeren 3
7346 AB Hoog Soeren
Tel.    +31 (0)55 5191285
Mob. +31 (0)6 51109024
www.kroondomeinhetloo.nl<http://www.kroondomeinhetloo.nl/>

[kroondomein logo oranje]



Van: Evert Jan Meulenkamp [mailto:notifications@github.com]
Verzonden: donderdag 15 januari 2015 15:32
Aan: IDgis/CRS2
CC: Olthof, R.K.C.
Onderwerp: Re: [CRS2] elementen, invoer elementnummer (#60)


Normaalgesproken gaat het bij elementen als volgt: Je tekent eerst een element in GIS (lijn of punt) en geeft het een naam/nummer via de extensie van Tom. Omdat je in CRS2 ook gegevens van het element vast wilt leggen (vergelijkbaar met afdelingen) moet het element ook in de elemententabel van CRS2 aangemaakt worden. Om de juiste geometrie bij het juiste (CRS2)-element te kunnen tonen, hebben we afgesproken dat de elementcode in beide tabellen hetzelfde moet zijn.
Vanuit een pure GIS-benadering zou je de kenmerken van het element als velden op willen nemen in de tabellen waarin ook de geografie staat. Zo is CRS2 echter niet ontwikkeld.

—
Reply to this email directly or view it on GitHub<https://github.com/IDgis/CRS2/issues/60#issuecomment-70093074>.

Dit e-mailbericht (en bijlagen) is uitsluitend bestemd voor de geadresseerde(n) en diegene die toestemming hebben dit bericht te lezen. Gebruik door onbevoegden is verboden. Dit e-mailbericht kan vertrouwelijk zijn en binnen het bereik vallen van een wettelijke geheimhoudingsplicht. Indien U het bericht ten onrechte hebt ontvangen, wordt U verzocht ons daarover per ommegaande te informeren, en de e-mail (en bijlagen) – zonder van de inhoud kennis te nemen – onmiddellijk te verwijderen.

This e-mail (and its attachments) is intended exclusively for the addressee(s) or those authorized by the recipient. Use by anyone other than the authorized recipient is prohibited. This e-mail may be confidential, legally privileged or exempt from disclosure. If you have received this e-mail by mistake, please notify us by return of mail and delete the message (and its attachments) – without taking note of its contents – immediately.

p2510_1625u109
