### ISSUE TITLE
arcMap karagtentool is verdwenen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#62]
Deze is voor Tom,

net ArcMap Limburg geopend. Met de Kragtentool Afdelingen toegevoegd. De rest verdwijnt dan, hou je alleen afdelingen over. Echter  na deze actie verdween ook de KragtenTool uit beeld. Geen idee hoe ik hem terug kan halen.
1. waarom verwijnt ie, zou niet moeten.
2. hoe zet ik hem weer terug.

Groet, Harry

**Comment by LimburgsLandschapHarry** [comment]
ps: ik krijg de tool ook niet meer terug als ik gis afsluit zonder saven en opnieuw opstart.

**Comment by gwenroyakkers** [comment]
Iemand had de toolbar gewoon weggeklikt. Ik heb even terug ingelogd en deze weer aangezet.

Meer informatie over hoe dit zit met ArcMap toolbars vind je op volgende locatie:
http://resources.arcgis.com/en/help/main/10.2/index.html#//00v000000010000000 

![image](https://cloud.githubusercontent.com/assets/10629981/5835987/3ac63b18-a16f-11e4-9e51-3addd7b7a815.png)

Verder klopt het Dat de toevoegen tool alleen de CRS lagen laat zien die je heb geselecteerd, en de andere terug uit het document weghaalt.
Dit is om te voorkomen dat je lagen dubbel toevoegt.

**Comment by LimburgsLandschapHarry** [comment]
Hoi,

Dat alleen de aangevinkte kagen erin komen is bekend en ok. Ging me om de toolbar, die spontaan(?) verdween. Lijkt me hierbij opgelost.


Met vriendelijke groet,

Harry Bussink


Op 21 jan. 2015 om 13:22 heeft Gwen <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Iemand had de toolbar gewoon weggeklikt. Ik heb even terug ingelogd en deze weer aangezet.

Meer informatie over hoe dit zit met ArcMap toolbars vind je op volgende locatie:
http://resources.arcgis.com/en/help/main/10.2/index.html#//00v000000010000000

[image]<https://cloud.githubusercontent.com/assets/10629981/5835987/3ac63b18-a16f-11e4-9e51-3addd7b7a815.png>

Verder klopt het Dat de toevoegen tool alleen de CRS lagen laat zien die je heb geselecteerd, en de andere terug uit het document weghaalt.
Dit is om te voorkomen dat je lagen dubbel toevoegt.
