### ISSUE TITLE
krijg het viewerscherm niet voleldig in beeld gesleept

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#63]
Hoi,

de viewer verschijnt meestal goed in beeld, maar soms ligt er een rand buiten beeld. Nu die rand aan de bovenkant ligt, krijg ik het beeld niet meer volledig binnen de kaders gezet. Zou hem toch met dubbelklikken moeten kunnen laten passen, of met handje verslepen? 
![capture](https://cloud.githubusercontent.com/assets/10415606/5834165/eef8f09a-a15a-11e4-815a-d8544b866d96.JPG)

**Comment by ejmeulenkamp** [comment]
Als de titelbalk van een venster in CRS2 buiten beeld raakt, dan kun je via menu-optie 'Venster' kiezen voor 'Allen schikken'. Het venster zal dan beeldvullend worden gemaakt. Als er nog andere vensters open staan, dan zal de schermruimte verdeeld worden tussen alle openstaande vensters. Je kunt daarna met de rechter muisknop klikken op het gespikkelde hoekje rechts onder in het venster (vlak naast de knop [Venster sluiten]), om een ander formaat te kiezen via het submenu dat daar verschijnt.
