### ISSUE TITLE
Fout bij selecteren andere medewerker voor weekstaat

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#64]
Als ik op het verrekijkerknopje achter het veld Medewerker klik, bij het invoeren van een nieuwe weekstaat voor een andere persoon, dan verschijnt er een fout.

**Comment by ejmeulenkamp** [comment]
Dit zou nu opgelost moeten zijn.

**Comment by ejmeulenkamp** [comment]
@LimburgsLandschapHarry en @HZLWannes 
Kunnen jullie in versie 1.06.09 ook een andere medewerker kiezen na het aanmaken van een nieuwe weekstaat?

**Comment by HZLWannes** [comment]
Ik heb die versie nog niet. En heb nog geen project om weekstaten op te boeken.

**Comment by HZLWannes** [comment]
Ja dat lukt. Ik kan gewoon op het verrekijkertje klikken en een collega's weekstaat invullen ;)

**Comment by HZLWannes** [comment]
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET ZEEUWSE LANDSCHAP

Datum / Tijd:    21-01-2015 14:43:21
Gebruiker:       Castelijns, Wannes                      
Programmaversie: 1.06.09
Foutnummer:      1545 
Programmaregel:  2    

Foutboodschap:
    Table buffer for alias "CWRR" contains uncommitted changes.

Methode/Programma:
    C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.CREATEINDEXTAGS                                                             

Code:
    SELECT cWrr

Inhoud AERROR():
    1545
    Table buffer for alias "GNERRORNUMBER" contains uncommitted changes.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\ZEELAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.CMDTOEV.CLICK C:\HELPDESK\VMP2005\XLIB\XXFWGRD.VCT
    PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.ADDROW C:\HELPDESK\ZEELAND\C2DEWKS.SCT
    PROCEDURE C2DEWKS.HERBEREKEN C:\HELPDESK\ZEELAND\C2DEWKS.SCT
    PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.OVOYEUR.REFRESH C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWKS.PGFPAGEREFRESH1.COMMONPAGEREFRESH C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWKS.PGFPAGEREFRESH1.MANUALPAGEREFRESHACTION C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.ONPAGEACTIVATE C:\HELPDESK\VMP2005\XLIB\XXFWGRD.VCT
    PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.SHELLREQUERY C:\HELPDESK\ZEELAND\C2DEWKS.SCT
    PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.PUSHPOPRECORDSOURCE C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.CREATEINDEXTAGS C:\HELPDESK\ZEELAND\C2DEWKS.SCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.CREATEINDEXTAGS)


Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    
@ejmeulenkamp ik krijg wel deze melding bij het boeken. van uren.

**Comment by HZLWannes** [comment]
tweede poging lukt het wel te boeken. Ik hoop dat je nog wat met de foutmelding kan.

**Comment by HZLWannes** [comment]
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET ZEEUWSE LANDSCHAP

Datum / Tijd:    21-01-2015 14:59:40
Gebruiker:       Castelijns, Wannes                      
Programmaversie: 1.06.09
Foutnummer:      31   
Programmaregel:  13   

Foutboodschap:
    Invalid subscript reference.

Methode/Programma:
    C2PKWPL.CBOBHT.REQUERY                                                                                                  

Code:
    SELECT cBegr

Inhoud AERROR():
    31
    Invalid subscript reference.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\ZEELAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.CMDTOEV.CLICK C:\HELPDESK\VMP2005\XLIB\XXFWGRD.VCT
    PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.ADDROW C:\HELPDESK\ZEELAND\C2DEWKS.SCT
    PROCEDURE GRDC2DATAENTRY.ADDROW C:\HELPDESK\ZEELAND\C2FWGRD.VCT
    PROCEDURE C2DEWKSWRR.CTRWPL.CMDICPICKLISTVALID1.CLICK C:\HELPDESK\VMP2005\XLIB\XXFWCOMP.VCT
    PROCEDURE C2DEWKSWRR.CTRWPL.ONBUTTONCLICK C:\HELPDESK\VMP2005\XLIB\XXFWCOMP.VCT
    PROCEDURE C2DEWKSWRR.CTRWPL.TXTPV.MENULOOKUP C:\HELPDESK\VMP2005\XLIB\XXFWCTRL.VCT
    PROCEDURE C2DEWKSWRR.CTRWPL.TXTPV.ACTIONONINVALID C:\HELPDESK\VMP2005\XLIB\XXFWCTRL.VCT
    PROCEDURE C2DEWKSWRR.CTRWPL.TXTPV.DOPICKLISTFORM C:\HELPDESK\VMP2005\XLIB\XXFWCTRL.VCT
    PROCEDURE C2PKWPL.CBOBHT.INIT C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2PKWPL.CBOBHT.REQUERY C:\HELPDESK\ZEELAND\C2PKWPL.SCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2PKWPL.CBOBHT.REQUERY)


Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    
Is dit dezelfde? Dan klikte ik op het verrekijkertje van planningsregels, voordat ik op object klikte.

**Comment by ejmeulenkamp** [comment]
@HZLWannes In het venstertje 'Werkplanweekstaatregel raadplegen / muteren' is vanaf versie 1.06.10 het veld 'Planningsregelnr' grijs totdat je een object hebt gekozen. Je kunt voortaan dus niet meer per ongeluk op het verrekijkertje van Planningsregelnr klikken. Je moet altijd eerst een object selecteren.
Kun je nog eens testen of dit in versie 1.06.10 opgelost is?

Verder wil ik je vriendelijk verzoeken om bij een nieuwe foutmelding een nieuwe bevinding aan te maken. Misschien was het hier niet meteen helemaal duidelijk dat de het een nieuwe fout was. Maar in het algemeen werkt het overzichtelijker als je er een nieuwe melding van maakt.
