### ISSUE TITLE
Foutmelding bij het boeken van uren

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#65]
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
 STICHTING HET ZEEUWSE LANDSCHAP

Datum / Tijd: 21-01-2015 14:43:21
 Gebruiker: Castelijns, Wannes

 Programmaversie: 1.06.09
 Foutnummer: 1545 
 Programmaregel: 2 

Foutboodschap:
 Table buffer for alias "CWRR" contains uncommitted changes.

Methode/Programma:
 C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.CREATEINDEXTAGS 

Code:
 SELECT cWrr

Inhoud AERROR():
 1545
 Table buffer for alias "GNERRORNUMBER" contains uncommitted changes.
 GNERRORNUMBER

Programmapad:
 C:\HELPDESK\ZEELAND\CRS2.EXE
 XXFWMAIN.FXP
 PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
 PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.CMDTOEV.CLICK C:\HELPDESK\VMP2005\XLIB\XXFWGRD.VCT
 PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.ADDROW C:\HELPDESK\ZEELAND\C2DEWKS.SCT
 PROCEDURE C2DEWKS.HERBEREKEN C:\HELPDESK\ZEELAND\C2DEWKS.SCT
 PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.OVOYEUR.REFRESH C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
 PROCEDURE C2DEWKS.PGFPAGEREFRESH1.COMMONPAGEREFRESH C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
 PROCEDURE C2DEWKS.PGFPAGEREFRESH1.MANUALPAGEREFRESHACTION C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
 PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.ONPAGEACTIVATE C:\HELPDESK\VMP2005\XLIB\XXFWGRD.VCT
 PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.SHELLREQUERY C:\HELPDESK\ZEELAND\C2DEWKS.SCT
 PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.PUSHPOPRECORDSOURCE C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
 PROCEDURE C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.CREATEINDEXTAGS C:\HELPDESK\ZEELAND\C2DEWKS.SCT
 XXERROR.FXP
 PROCEDURE LOGERROR XXERROR.FXP
 (C2DEWKS.PGFPAGEREFRESH1.PAGE2.CTRWRR.GRDSUB.CREATEINDEXTAGS)

Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:

@ejmeulenkamp ik krijg wel deze melding bij het boeken. van uren.

**Comment by ejmeulenkamp** [comment]
Hoi Wannes,

Ik heb er maar even een aparte melding van gemaakt, want anders klopt de titel niet meer met de fout.
Weet je nog wat je deed toen de fout optrad of vlak daarvoor? Dat zou me erg helpen bij het oplossen van deze fout.

**Comment by ejmeulenkamp** [comment]
@HZLWannes 
Ik heb er maar even een aparte melding van gemaakt, want anders klopt de titel niet meer met de fout.
 Weet je nog wat je deed toen de fout optrad of vlak daarvoor? Dat zou me erg helpen bij het oplossen van deze fout.

**Comment by ejmeulenkamp** [comment]
@HZLWannes Krijg je deze fout nog bij het invoeren van uren?

**Comment by HZLWannes** [comment]
Nee gaat nu goed! Sorry dat ik dit niet gemeld had.
