### ISSUE TITLE
projecten: eigenschappen medewerker wijzigen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#66]
in projecten, tabblad koppelingen een medewerker selecteren dmv knop wijzigen om de eigenschappen te veranderen. Bv projectleider maken.

![capture](https://cloud.githubusercontent.com/assets/10415606/5915573/7e9b7a00-a607-11e4-9782-1c84c1117485.JPG)

Als je in deze foutmelding op OK klikt kun je verder en de eigenschappen veranderen

**Comment by ejmeulenkamp** [comment]
In versie 1.06.10 zou deze fout opgelost moeten zijn. @LimburgsLandschapHarry Kun je dit nog eens controleren?
