### ISSUE TITLE
projecten: toevoegen document

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#67]
bij toevoegen document geeft ie aan dat directory niet bestaat. Kan ik me in vinden. Maar zou die niet een scherm moeten openen waar je de gewenste directory kunt opzoeken, in plaats dat er een standaarddirectory is waar je documenten in hebt staan.

**Comment by LimburgsLandschapHarry** [comment]
Bijbehorende print screen
![capture](https://cloud.githubusercontent.com/assets/10415606/5915648/8b0f9d06-a608-11e4-97b1-5ff47f568d81.JPG)

**Comment by ejmeulenkamp** [comment]
Dit onderdeel is zo gebouwd dat je via de Opties van CRS2 een map aan moet geven die CRS2 standaard opent als je een document wilt koppelen. Als je echter al eerder documenten hebt gekoppeld dan zal hij de laatst gebruikte map openen. Als die niet meer beschikbaar is, dan valt hij terug op de "Basismap documenten". Dit werkt al zo vanaf het begin.
Als je een andere manier van werken beter vindt, dan zou ik dat graag willen overleggen met andere gebruikers. Dan kan het eventueel wel aangepast worden.

**Comment by LimburgsLandschapHarry** [comment]
Hoi, dat ie teruggrijpt op een gedefinieerde map of de map met eerder gekoppelde documenten is prima. Punt is dat ik hier een melding krijg dat de map niet bestaat en vervolgens ook niet naar een andere directory kan. Dat is in de huidige crs anders. Daar kun je kiezen om naar een andere map te navigeren en daar een document te koppelen.

**Comment by ejmeulenkamp** [comment]
Het werkt nu zo dat als CRS2 de map kan vinden van waaruit voor het laatst een document gekoppeld is OF als CRS2 de standaard documentmap (Venster Opties) kan vinden, dan verschijnt een keuzescherm, waarin zowel een andere map geopend kan worden als één of meer bestanden gekoppeld kunnen worden. Zo is het volgens mij ook altijd geweest. Is dit werkbaar?

**Comment by LimburgsLandschapHarry** [comment]
Hoi,

net getest. Ik krijg een directorystructuur om in te navigeren naar het juiste document. Dat deed ie eerst niet en nu wel. Is daarmee prima.
