### ISSUE TITLE
projecten toevoegen realisatieregel

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#68]
bij toevoegen van een realisatieregel in tabblad maatregelen verschijnt deze regel in het scherm. Eerdere regels verdwijnen dan boven in het scherm. Om deze terug te halen moet je de scrolbar omhoog schuiven. De overige regels zouden in beeld moeten blijven. ps dit doet is ook in de huidige lopende versie.

**Comment by ejmeulenkamp** [comment]
Vanaf versie 1.06.14 zouden de regels gewoon moeten blijven staan na het toevoegen van nieuwe regels of het wijzigen van bestaande regels. Ik hoor graag of dit nu goed werkt.

**Comment by LimburgsLandschapHarry** [comment]
regels blijven staan
