### ISSUE TITLE
projecten met kaart: perceel toevoegen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#69]
als je in het linker scherm op koppelen drukt zou rechts in de viewer select punt geactiveerd moeten worden. Dat gebeurd niet. Je moet nu zelf select punt in het rechterscherm activeren. 
- tweede fout: Je kunt slechts 1 perceel selecteren, shift select werkt niet voor meerdere percelen.

**Comment by ejmeulenkamp** [comment]
Het selecteren van meerdere percelen met behulp van de Shift-toets werkt nog niet in de viewer. Tijdens de meeting is dit punt in de planning opgenomen. Het activeren van "Select punt" zal ik onderzoeken.

**Comment by ejmeulenkamp** [comment]
Vanaf versie 1.06.13 werkt het selecteren van meerdere percelen m.b.v. de shift-toets in de viewer. Kun je dat bevestigen?

**Comment by LimburgsLandschapHarry** [comment]
het werkt
