### ISSUE TITLE
stambestanden: relatie toevoegen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#70]
toevoegen van relatie in stambestand relaties.
geeft een foutmelding:
![capture](https://cloud.githubusercontent.com/assets/10415606/5916755/cab4a80a-a614-11e4-81cd-271ed416c1c6.JPG)

Vervolgens fatal error:
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET LIMBURGS LANDSCHAP

Datum / Tijd:    27-01-2015 11:08:36
Gebruiker:       Bussink, Harry                          
Programmaversie: 1.06.09
Foutnummer:      13   
Programmaregel:  24   

Foutboodschap:
    Alias 'CINSTEMP' is not found.

Methode/Programma:
    C2DEREL.ADDAFTERAPPENDBLANK                                                                                             

Code:
    

Inhoud AERROR():
    13
    Alias 'GNERRORNUMBER' is not found.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\LIMLAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEREL.CMDADD.CLICK C:\HELPDESK\VMP2005\XLIB\XXFWCTRL.VCT
    PROCEDURE C2DEREL.ADDACTION C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEREL.ADDAFTERAPPENDBLANK C:\HELPDESK\LIMLAND\C2DEREL.SCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DEREL.ADDAFTERAPPENDBLANK)

Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    toevoegen relatie aan stambestand

**Comment by ejmeulenkamp** [comment]
De fout is gevonden en opgelost in versie 1.06.10. Kun je nog eens controleren of je nu wel een nieuwe relatie toe kunt voegen?
