### ISSUE TITLE
contracten; nieuw nummer

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#71]
er wordt automatisch naar het hoogste contractnummer gezocht en met 1 opgehoogd voor het nieuwe nummer. Dit is voor ons niet nodig. Wij nummeren per object.

**Comment by ejmeulenkamp** [comment]
CRS2 stelt inderdaad automatisch een contractnummer voor bij het aanmaken van een nieuw contract. Eventueel kan ik in de opties een vinkje toevoegen waardoor CRS2 dat niet meer doet. Je moet dan dus zelf een contractnummer bedenken en invoeren. Is dit een gewenste oplossing?

**Comment by LimburgsLandschapHarry** [comment]
Dit kan. Zijn er gebruikers die hebben gevraagd  naar het opeenvolgend nummeren van de contracten? Je kunt er voor kiezen om een vinkje aan of uit te zetten. Als niemand opeenvolgend nummert kun je dit uit de programmatuur laten. Als dat wel gebeurt kun je er ook voor kiezen om het maar zo te laten en het nummer aan te passen naar je eigen behoefte. We moeten toch in dat veld wijzigen. Of je dan een volledig nieuw nummer in toetst of de automatische nummering moet selecteren en dan een nieuw nummer intoetst maakt niet zo veel uit in handelingen.
