### ISSUE TITLE
contracten, contractsoort toevoegen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#72]
FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET LIMBURGS LANDSCHAP

Datum / Tijd:    27-01-2015 11:12:08
Gebruiker:       Bussink, Harry                          
Programmaversie: 1.06.09
Foutnummer:      1    
Programmaregel:  25   

Foutboodschap:
    File 'c:\helpdesk\limland\cct.dbf' does not exist.

Methode/Programma:
    C2DECTR.PGFPAGEREFRESH1.PAGE2.CTRCSO.REPLACEADDITIONALFIELDS                                                            

Code:
    SELECT cCsoList

Inhoud AERROR():
    1
    File '00000001: Incorrect function' does not exist.
    00000001: Incorrect function
    
    
    
    

Programmapad:
    C:\HELPDESK\LIMLAND\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE CUSC2FORMS.EXECUTEACTIVECONTROLMETHOD C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DECTR.PGFPAGEREFRESH1.PAGE2.CTRCSO.TXTPV.MENULOOKUP C:\HELPDESK\VMP2005\XLIB\XXFWCTRL.VCT
    PROCEDURE C2DECTR.PGFPAGEREFRESH1.PAGE2.CTRCSO.TXTPV.ACTIONONINVALID C:\HELPDESK\VMP2005\XLIB\XXFWCTRL.VCT
    PROCEDURE C2DECTR.PGFPAGEREFRESH1.PAGE2.CTRCSO.TXTPV.PROCESSNEWVALUE C:\HELPDESK\VMP2005\XLIB\XXFWCTRL.VCT
    PROCEDURE C2DECTR.PGFPAGEREFRESH1.PAGE2.CTRCSO.ONCHANGED C:\HELPDESK\VMP2005\XLIB\XXFWCOMP.VCT
    PROCEDURE C2DECTR.PGFPAGEREFRESH1.PAGE2.CTRCSO.LBLDISPLAY.REFRESH C:\HELPDESK\LIMLAND\C2PV.VCT
    PROCEDURE C2DECTR.PGFPAGEREFRESH1.PAGE2.CTRCSO.REPLACEADDITIONALFIELDS C:\HELPDESK\LIMLAND\C2PV.VCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DECTR.PGFPAGEREFRESH1.PAGE2.CTRCSO.REPLACEADDITIONALFIELDS)

Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    toevoegen contractsoort loslandpacht eenmalig.

**Comment by ejmeulenkamp** [comment]
De fout die optrad tijdens het selecteren van een contractsoort bij het aanmaken van een nieuw contract is verholpen in versie 1.06.10. Wil je dit onderdeel nor eens testen?
