### ISSUE TITLE
contracten, datumveld

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#73]
volgende betaling heeft als jaar 2015 0

![capture](https://cloud.githubusercontent.com/assets/10415606/5916910/1c08cebe-a617-11e4-8268-7f334fa9464d.JPG)

**Comment by LimburgsLandschapHarry** [comment]
gebeurt alleen bij huidige vreemde datum eerste betaling die gelijk is aan volgende betaling.

**Comment by ejmeulenkamp** [comment]
De reden waarom in sommige datumvelden extra tekens (vaak 00:00:00) verschijnen is dat in SQL Server alle datums opgeslagen worden als tijdstippen, dus datum + tijd. In het door jou genoemde veld kan ik de tijd-aanduiding wel weghalen. Dat is vanaf versie 1.06.10 zo. Ik heb ook nog een snelle scan gedaan door het totale systeem om te kijken of er nog meer van dit soort velden waren. De aanmaakdatum van een prijsperiode was er ook een. Deze is nu ook aangepast.

Echter: In tabellen, zoals de tabel 'Prijsperiodes' op het tabblad 'Financiën', kan ik het tijdsdeel van de datums niet weghalen. Overal waar een datum in een tabel staat zul je dus het tijdsdeel geheel of gedeeltelijk zien. We zullen moeten kijken of dit storend werkt. Natuurlijk blijf ik wel speuren naar een methode om het tijdsdeel van datumvelden ook in tabellen weg te halen.

**Comment by LimburgsLandschapHarry** [comment]
Hallo,
dat er naast datum ook tijd aangehangen wordt is niet zo heel erg, als dat dan ook maar volledig zichtbaar is in het veld. 15-01-2015 00:00:00 levert wellicht wat gefronste wenkbrauwen op bij de gebruikers, maar ze zullen wel snappen dat dit de tijd is. Als de tijdsindicatie onzichtbaar gemaakt kan worden in het veld is het natuurlijk nog mooier, omdat er in CRS geen noodzaak is tot dit detailniveau. 
Oplossing: waar mogelijk de tijdcode niet opnemen in het veld. Waar dat niet mogelijk is zorgen dat je het niet ziet door het veld klein genoeg te maken, of zorgen dat je het totaal ziet, zodat duidelijk is waar het over gaat.
