### ISSUE TITLE
contracten: exporteren factuurregels

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#74]
Ik weet niet of dat hier al moet kunnen, maar er volgt een foutmelding.
![capture](https://cloud.githubusercontent.com/assets/10415606/5917186/658a87d2-a61a-11e4-85b0-45d2c8519f4e.JPG)

**Comment by ejmeulenkamp** [comment]
De fout die optrad tijdens het exporteren van factuurregels is opgelost in versie 1.06.10. Kun je dit nog een keer verifiëren?

**Comment by LimburgsLandschapHarry** [comment]
geen foutmeldingen meer. Wel melding dat factuurregels voor betreffende periode al zijn geexporteerd, maar dat is logisch.
