### ISSUE TITLE
contracte; printoverzicht

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#75]
formulier van contracten printen is erg langzaam, lijkt te blijven steken / nu 40sec bezig, afgebroken..

**Comment by LimburgsLandschapHarry** [comment]
waarschijnlijk te wijten aan een zeer ruime selectie. beperkte selectie levert geen problemen op.

**Comment by ejmeulenkamp** [comment]
Het afdrukken van een groot aantal contractformulieren kan inderdaad lang duren. Is het zinvol om een extra waarschuwing in te bouwen die verschijnt bij het afdrukken van bijvoorbeeld meer dan 15 formulieren?

**Comment by LimburgsLandschapHarry** [comment]
Als het een kleine moeite is om dit in te bouwen staat het wel zo netjes dat je een waarschuwing krijgt dat er veel informatie samengevoegd moet worden en dat dat langer kan duren. 
Bij veel programma's verschijnt er een zandlopertje als de computer bezig is met denken. Dat geeft ook goed aan dat er achter de schermen gewerkt wordt.

**Comment by ejmeulenkamp** [comment]
Ik heb een melding ingebouwd. Als je meer dan 25 formulieren hebt geselecteerd om af te drukken, dan verschijnt een extra vraag of je dat wel wilt. Ik sluit hiermee het issue af.
