### ISSUE TITLE
onderhoud; percelen splitsen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#76]
kan bewerking niet afronden, want knop is grijs.
![capture](https://cloud.githubusercontent.com/assets/10415606/5917689/150c3ae8-a620-11e4-9c88-ba6c2ba5f276.JPG)

**Comment by ejmeulenkamp** [comment]
Ik heb getest of de knop [Splitsen] actief wordt nadat de informatie van twee deelpercelen compleet ingevoerd is in het venster Kad.object splitsen. Bij mij wordt de knop echter wel bedienbaar. Kun je me een precieze omschrijving geven van de volgorde en de stappen die je uitvoert?
Ik zie bijvoorbeeld in jou schermafdruk dat het actieve veld het veld "Gemeente" is van "Kad.object 2". Als ik de velden in de 'normale' volgorde doorloop dan wordt de knop [Splitsen] al bedienbaar nadat ik het veld 'Nummer' van 'Kad.object 2' ingevoerd heb. Ik hoop dat je me kunt aanduiden hoe jij te werk bent gegaan, waardoor de knop grijs blijft.

**Comment by LimburgsLandschapHarry** [comment]
getest, werkt zoals het moet.
