### ISSUE TITLE
arcgis: sleutel toeveogen is uitgegrijsd

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#77]
in arcgis probeerde ik een sleutel toe te voegen aan een afdeling zonder nummer. Dit ging niet omdat de knop 'uitgegrijsd' was.

**Comment by LimburgsLandschapHarry** [comment]
na koppelen tabellen is de knop niet meer grijs en kan ik sleutel toevoegen.

**Comment by gwenroyakkers** [comment]
De sleutelknop blijft uitgeschakeld totdat je in de TOC (Table of Contents) de CRS-laag selecteert waaraan je een sleutel wil toevoegen.

Dit heeft niets met koppelen te maken.

![sleutel1](https://cloud.githubusercontent.com/assets/10629981/5936808/7e2af780-a6e8-11e4-98bc-8bf59ef24ad4.png)
![sleutel2](https://cloud.githubusercontent.com/assets/10629981/5936812/818dde74-a6e8-11e4-9e4a-7a4938ba455c.png)
