### ISSUE TITLE
info uit kaart opvragen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#78]
in kaart afdeling selecteren, dan moet je via knop info links de bijbehorende afdelingen info op kunnen vragen. Knop info blijft grijs. Kan dus geen info opvragen van geselecteerde afdeling (terwijl die wel administratief bekend is).

**Comment by ejmeulenkamp** [comment]
De knop [Info] (tussen de knoppen [Nieuwe] en [Grote kaart]) wordt pas bedienbaar nadat je minimaal één afdeling op de kaart hebt geselecteerd (via de knop 'Selecteer met punt' of via de knop 'Selecteer met vlak'). Volgens mij zeg je in je beschrijving ook dat je een afdeling hebt geselecteerd. Als ik dat nu doe in jullie systeem, dan wordt de knop [Info] bedienbaar en na een klik verschijnt de informatie van de bijbehorende afdeling(en), zoals het zou moeten.
Zou je nog een keer willen testen of je bevinding nog steeds optreedt?

**Comment by LimburgsLandschapHarry** [comment]
Werkt zoals het zou moeten.
