### ISSUE TITLE
onderhoud- geomutaties verwerken

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#79]
werkt niet. toegevoegd afdelingsnummer in gis krijg ik niet in crs te zien. Afdeling is administratief wel in crs ingevoegd en teogevoegde beheertype verschijnt in gis wel in juiste kleur op kaart. Echter niet in crs.

![capture](https://cloud.githubusercontent.com/assets/10415606/5935462/998a7aee-a6db-11e4-90d4-fd71d4367474.JPG)

**Comment by ejmeulenkamp** [comment]
Ik zal de foutmelding onderzoeken. De reden waarom je een toegevoegde afdeling wel in GIS maar niet in CRS2 te zien krijgt is omdat de conversietool 'ogr2ogr' nog niet gedraaid is. Hierdoor is de mutaties alleen bekend in de FGDB, maar nog niet in SQL Server. CRS2 toont alleen geografische informatie die in SQL Server staat. Zie ook #80.

**Comment by ejmeulenkamp** [comment]
Werkt dit onderdeel nu naar behoren?

**Comment by LimburgsLandschapHarry** [comment]
Hoi, het lijkt erop alsof het nu foutloos werkt. Ik heb een geomutatie kunnen draaien zonder foutmelding. Wat ik echter niet heb kunnen testen is het wijzigigen van een afdeling en dan geomutaties draaien, omdat ik GIS niet meer aan de praat krijg. Ik denk dat de proeflicentie verlopen is.

**Comment by ejmeulenkamp** [comment]
Harry, bedankt voor de melding.
@gwenroyakkers 
Klopt het dat de tijdelijke licentie van ArcGis op de centrale testserver verlopen is?
Als dat zo is, dan kan de CRS2-AddIn vanaf nu alleen nog in de lokale omgevingen gebruikt worden.
@HermanAssink  en @LindaVels

**Comment by LimburgsLandschapHarry** [comment]
at zo is, moeten we GIS op de server zetten waar we nu CRS2 testen. Dat houdt dan ook in dat de usb key die nu in mijn eigen compi zit dan achter in de server moet en ik dan via de server aan gis moet werken. Klopt dat?

**Comment by gwenroyakkers** [comment]
Helaas klopt dit.
De Demo van ArcGis kan je maar 60 dagen gebruiken.
Deze is geactiveerd op 15 januari en op 16 maart vervallen.

**Comment by ejmeulenkamp** [comment]
De oorspronkelijke foutmelding onder dit issue is opgelost. Als er nog vragen zijn over het lokaal testen met ArcGis, zouden jullie dan een nieuw issue aan willen maken? Dan dekt de vlag de lading weer.
