### ISSUE TITLE
Ik zie de kaartlaag waarnemingen niet

### ISSUE THREAD

**Issue by HZLWannes** [IDgis/CRS2#8]
Er zijn geen stippen zichtbaar. Laag lijkt niet gekoppeld, kaart zoomt namelijk ook niet naar de geselecteerde waarnemingen toe.

**Comment by LindaVels** [comment]
Het niet zichtbaar zijn van de laag waarnemingen wordt ws veroorzaakt door een fout in de configuratie van deze laag in de kaart services. Het opslaan van een waarneming (issue #9) loop via het administratieve deel van de applicatie -> EJM

**Comment by LindaVels** [comment]
Vanochtend heb ik een nieuwe versie van de services geplaatst waarin de fouten in de configuratie aangaande waarnemingen zijn verbeterd. Zou je overnieuw kunnen testen?

**Comment by HZLWannes** [comment]
Helaas, zie ik nog niets. Ik heb één keer de stippen gezien, bij de eerste keer de module opstarten na ongeveer 40-50 seconden wachten (dat is lang in modern computerland). Nadat ik een selectie heb gemaakt gebeurde er niets op de kaart behalve dat de stippen verdwenen. Ik heb de module meermaals opnieuw opgestart en heb ze nooit weer gezien ook niet bij het opstarten van de module en enkele minuten wachten eht steeds opnieuw geprobeerd.

**Comment by HZLWannes** [comment]
Ook de wel aangevinkte afdelingen kaart lijkt niet meer te verschijnen (ook bij inzoomen niet). Te zware data...

**Comment by LindaVels** [comment]
@ejmeulenkamp: Ik zie dat na het drukken op de knop Toon selectie een zoomToLayer wordt afgevuurd op de viewer met een "foutieve" query op de laag afdelingen ipv waarnemingen. Dit verklaart waarom de waarnemingen verdwijnen uit het kaartbeeld. 

Ik kan echter nog niet verklaren waarom het opstarten zolang duurt.  

zoomToLayer(waarnemingen,SELECT Afdelingen.Afdeling AS id, Afdelingen.Afdeling, Afdelingen.ogr_geometry AS geom FROM Afdelingen, wrn WHERE Afdelingen.Afdeling = obj.obj_code + afd.afd_afd AND wrn_pk > 0 AND wrn_pk IN ( SELECT wrn_pk FROM wrn, obj, bhr, dis, loc, mth, opr, sgp, grp, hgp, abu, gsl, ddo, dom, std, vbp, vbs, soo WHERE abu_pk = wrn_abu_fk AND gsl_pk = wrn_gsl_fk AND ddo_pk = wrn_ddo_fk AND dom_pk = wrn_dom_fk AND std_pk = wrn_std_fk AND vbp_pk = wrn_vbp_fk AND vbs_pk = wrn_vbs_fk AND loc_pk = wrn_loc_fk AND opr_pk = wrn_opr_fk AND mth_pk = wrn_mth_fk AND obj_pk = wrn_obj_fk AND bhr_pk = obj_bhr_fk AND dis_pk = bhr_dis_fk AND soo_pk = wrn_soo_fk AND sgp_pk = soo_sgp_fk AND grp_pk = sgp_grp_fk AND hgp_pk = grp_hgp_fk AND RTRIM(LTRIM(wrn_opname)) = '8' ),0,99999999,true)

**Comment by HZLWannes** [comment]
Momenteel zie ik zelfs helemaal geen kaart in deze module. Jullie zijn er vast aan bezig.
