### ISSUE TITLE
gis - wijziging afdelingsvorm werkt niet door in crs

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#80]
In gis een afdeling bewerkt, enkele vertices verplaatst en gedelete. De vorm van de afdeling verandert hierdoor. Dit zou ook zichtbaar moeten zijn in de afdelingen kaart als ik die in crs oproep. Dit is niet het geval.

**Comment by ejmeulenkamp** [comment]
Je geeft aan dat je in GIS een afdeling hebt bewerkt. Dat gebeurt dus eigenlijk in de File Geo Database van ESRI. Nadat je wijzigingen in de FGDB hebt gemaakt moeten de bijgewerkte kaartlagen naar SQL Server worden gekopieerd. Herman heeft hiervoor een tool gemaakt met het programma 'ogr2ogr'. Het opstarten van deze tool zou volgens mij vanuit de extensie van Kragten moeten geschieden. @gwenroyakkers: Is hier al een knop voor? @HermanAssink: Werkt ogr2ogr al?

**Comment by gwenroyakkers** [comment]
@ejmeulenkamp: Dit zou inderdaad op een knop gezet kunnen worden in onze toolbalk.
@HermanAssink: Hoe moet ik je ogr2ogr aanroepen? Is dit een webservice, DDL, of ga je hier een function of stored procedure van maken in de sql-database die ik kan aanroepen?

Het maken van deze knop aan mijn kant stelt op zich niet zoveel voor.
Ik moet alleen weten wat er precies moet gebeuren.
Hier zijn zoveel mogelijkheden voor dat we dit misschien beter mee nemen naar een overleg, of dit verder per mail of telefoon afhandelen? 

Is het misschien handig om over ogr2ogr, en hoe we deze gaan implementeren op de toolbalk een aparte discussie te openen?

Alvast bedankt!

**Comment by LimburgsLandschapHarry** [comment]
Probeer vanuit de gebruiker te redeneren. Hoe minder werk ik er mee heb, hoe liever het me is. En als ik geen aparte knop ogr2ogr nodig heb, zie ik hem liever ingebed in bestaande knoppen

**Comment by gwenroyakkers** [comment]
Als je nu de koppeltabellen maakt wordt automatisch de geometrie naar SQL-server gestuurd.
Is het probleem nu opgelost?
Dan zou deze vraag gesloten kunnen worden.

**Comment by ejmeulenkamp** [comment]
@gwenroyakkers Mooi dat het verversen van de geometrie in de SQL Server database toegevoegd is aan het proces 'Koppeltabellen maken'. Wordt dit ook vermeld in de naam of ToolTip van de knop? Ik vind wel dat zo'n belangrijke stap duidelijk moet zijn voor de gebruiker.

**Comment by gwenroyakkers** [comment]
Neen dit is nog niet gebeurd.
Ik zal dit nu even snel doen, dan is de tooltip in orde bij de volgende compilatie.

**Comment by LimburgsLandschapHarry** [comment]
Helaas krijg ik het niet meer getest op de testserver. Ik krijg GIS niet meer open. Dacht dat de test versie 2 maand geldig was.  Ik kan eventueel wel lokaal testen, maar dan moet ik hier gis op de nieuwe server (laten) instaleren, zodat ie in kan grijpen op de juiste (geo)databases.

**Comment by gwenroyakkers** [comment]
Deze functionaliteit voor geometry naar SQL-server te kopiëren zit sinds 26-02-2015 in de toolbalk.
Ik had niet gezien dat deze issue nog open stond.
