### ISSUE TITLE
projecten; projectmedewerker toevoegen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#81]
zie onderstaande melding:

![capture](https://cloud.githubusercontent.com/assets/10415606/5999332/2571771c-aad1-11e4-94b8-e9f263ee1443.JPG)

Vervolgens kun je wel door, maar bij invoeren naam medewerker krijg ik onderstaande foutmelding en breekt programma af.
![capture2](https://cloud.githubusercontent.com/assets/10415606/5999351/5bc00626-aad1-11e4-87b9-3FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
STICHTING HET LIMBURGS LANDSCHAP

Datum / Tijd:    02-02-2015 11:48:31
Gebruiker:       Bussink, Harry                          
Programmaversie: 1.06.09
Foutnummer:      1925 
Programmaregel:  11   

Foutboodschap:
    Unknown member IOBOMGR.

Methode/Programma:
    C2DEPROPGB.CTRPGB.TXTPV.BEFOREDOPICKLISTFORM                                                                            

Code:
    

Inhoud AERROR():
    1925
    Unknown member PCFATALERRORMESSAGE1.
    PCFATALERRORMESSAGE1
    
    
    
    

Programmapad:
    PROCEDURE C2DEPROPGB.CTRPGB.CMDICPICKLISTVALID1.CLICK C:\HELPDESK\VMP2005\XLIB\XXFWCOMP.VCT
    PROCEDURE C2DEPROPGB.CTRPGB.ONBUTTONCLICK C:\HELPDESK\VMP2005\XLIB\XXFWCOMP.VCT
    PROCEDURE C2DEPROPGB.CTRPGB.TXTPV.MENULOOKUP C:\HELPDESK\VMP2005\XLIB\XXFWCTRL.VCT
    PROCEDURE C2DEPROPGB.CTRPGB.TXTPV.ACTIONONINVALID C:\HELPDESK\VMP2005\XLIB\XXFWCTRL.VCT
    PROCEDURE C2DEPROPGB.CTRPGB.TXTPV.DOPICKLISTFORM C:\HELPDESK\VMP2005\XLIB\XXFWCTRL.VCT
    PROCEDURE C2DEPROPGB.CTRPGB.TXTPV.BEFOREDOPICKLISTFORM C:\HELPDESK\LIMLAND\C2PV.VCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DEPROPGB.CTRPGB.TXTPV.BEFOREDOPICKLISTFORM)

Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    

d061784b78d.JPG)

**Comment by LimburgsLandschapHarry** [comment]
vervolgens via omweg geprobeerd. Bestanden, medewerkers (ingelogd als sys, want dat doet Sjors nu ook altijd om namen toe te voegen aan projecten). En daar namen toegevoegd. Vervolgens wel aan het project te koppelen, als ik een gekoppelde naam als projectleider aan wil vinken, krijg ik weer het eerst ingevoegde plaatje als foutmelding. Ik kan echter uiteindelijk wel mezelf projectleider maken.

**Comment by ejmeulenkamp** [comment]
De fout tijdens het toevoegen van een nieuwe gebruiker bij een project is opgelost in versie 1.06.10. Kun je het nog een keer testen?
