### ISSUE TITLE
projecten tabblad subsidies, eigen bijdrage

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#82]
in het tabblad subsidies staat een aanvinkmogelijkheid voor eigen bijdrage. Dit staat niet in de help, waar dat voor is. (we hebben dus ook geen idee ;) )

**Comment by ejmeulenkamp** [comment]
In het projectenoverzicht "Stand van zaken per project (of projectdeel)" worden de bedragen die aangevinkt zijn als 'Eigen bijdrage' apart opgeteld. Ik zal het opnemen in de Help. Bedankt voor de tip.

**Comment by ejmeulenkamp** [comment]
Ik heb de uitleg over het vinkje "Eigen bijdrage" toegevoegd in de helpfunctie en sluit hiermee dit issue.
