### ISSUE TITLE
projecten; afspraken toeveogen

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#83]
bij afspraken toevoegen onderstaande foutmelding
![capture](https://cloud.githubusercontent.com/assets/10415606/5999832/65756cba-aad6-11e4-99b8-49fc06569a7f.JPG)

vervolgens invoer scherm zonder verdere foutmeldingen.

**Comment by ejmeulenkamp** [comment]
Het toevoegen van een afspraak aan een project zou vanaf versie 1.06.10 weer foutloos moeten werken.
