### ISSUE TITLE
werkplanregels nieuwe invoer en dan koppeling afdelingen

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#84]
In werkplanregels plan ik een nieuw werkplan, voor nieuw jaar  voor object. Ik voeg een maatregel toe, bewaar dit en wil vervolgens afdelingen koppelen. Melding dat dit niet lukt. zie plaatje scherm
![capture png_werkplan_selecteer afdelingen](https://cloud.githubusercontent.com/assets/10460914/6020778/3ec316f0-abb0-11e4-8507-756b8c81da62.PNG)

**Comment by ejmeulenkamp** [comment]
Het koppelen van afdelingen aan een werkplanregel zou vanaf versie 1.06.10 weer foutloos moeten werken. Kun je dit nog eens testen?
