### ISSUE TITLE
werkplanregels vastloper

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#86]
in werkplanregels in onderste scherm bij realisatie (van de twee) voeg ik een willeleurige relatie toe: vastloper

FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
KROONDOMEIN HET LOO

Datum / Tijd:    03-02-2015 15:40:14
Gebruiker:       Olthof, Rene                            
Programmaversie: 1.06.09
Foutnummer:      1545 
Programmaregel:  2    

Foutboodschap:
    Table buffer for alias "CWRR" contains uncommitted changes.

Methode/Programma:
    C2DEWPR.PGFPAGEREFRESH1.PAGE3.CTRWRR.GRDSUB.CREATEINDEXTAGS                                                             

Code:
    SELECT cWrr

Inhoud AERROR():
    1545
    Table buffer for alias "00000001: Incorrect function" contains uncommitted changes.
    00000001: Incorrect function
    
    
    
    

Programmapad:
    C:\HELPDESK\KROON\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWPR.PGFPAGEREFRESH1.PAGE3.CTRWRR.CMDTOEV.CLICK C:\HELPDESK\VMP2005\XLIB\XXFWGRD.VCT
    PROCEDURE C2DEWPR.PGFPAGEREFRESH1.PAGE3.CTRWRR.GRDSUB.ADDROW C:\HELPDESK\KROON\C2DEWPR.SCT
    PROCEDURE C2DEWPR.PGFPAGEREFRESH1.PAGE3.CTRWPL.GRDSUB.SHELLREQUERY C:\HELPDESK\KROON\C2DEWPR.SCT
    PROCEDURE C2DEWPR.PGFPAGEREFRESH1.PAGE3.CTRWRR.GRDSUB.SHELLREQUERY C:\HELPDESK\KROON\C2DEWPR.SCT
    PROCEDURE C2DEWPR.PGFPAGEREFRESH1.PAGE3.CTRWRR.GRDSUB.PUSHPOPRECORDSOURCE C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEWPR.PGFPAGEREFRESH1.PAGE3.CTRWRR.GRDSUB.CREATEINDEXTAGS C:\HELPDESK\KROON\C2DEWPR.SCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2DEWPR.PGFPAGEREFRESH1.PAGE3.CTRWRR.GRDSUB.CREATEINDEXTAGS)

Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    Relatie toevoegen in onderste scherm

**Comment by rkcolthof** [comment]
![capture png_werkplan_realisatie2](https://cloud.githubusercontent.com/assets/10460914/6022863/4514c854-abc0-11e4-8b23-34c2f9469181.PNG)

**Comment by ejmeulenkamp** [comment]
Vanaf versie 1.06.12 zou er geen fout meer op mogen treden tijdens het invoeren van een realisatieregel in het venster 'Werkplanregels'.

**Comment by ejmeulenkamp** [comment]
@rkcolthof  Kun je bevestigen dat dit issue nu opgelost is?
