### ISSUE TITLE
Houtoogsten, fatale fout 

### ISSUE THREAD

**Issue by rkcolthof** [IDgis/CRS2#87]
Houtoogst, details, taxatieeenheid, invoer gegevens: Bij partijnummer voer ik handmatig een partij in die niet bestaat. (geen verrekijkertje) 

FOUTMELDING CENTRAAL REGISTRATIE SYSTEEM
KROONDOMEIN HET LOO

Datum / Tijd:    03-02-2015 16:19:31
Gebruiker:       Olthof, Rene                            
Programmaversie: 1.06.09
Foutnummer:      26   
Programmaregel:  284  

Foutboodschap:
    Table has no index order set.

Methode/Programma:
    C2PKPTY.INIT                                                                                                            

Code:
    

Inhoud AERROR():
    26
    Table has no index order set.
    GNERRORNUMBER
    
    
    
    

Programmapad:
    C:\HELPDESK\KROON\CRS2.EXE
    XXFWMAIN.FXP
    PROCEDURE CTRC2APP.READEVENTS C:\HELPDESK\VMP2005\XLIB\XXFW.VCT
    PROCEDURE C2DEHOG.PGFPAGEREFRESH1.PAGE2.CTRHOR.GRDSUB.DBLCLICK C:\HELPDESK\KROON\C2DEHOG.SCT
    PROCEDURE GRDC2DATAENTRY.DBLCLICK C:\HELPDESK\KROON\C2FWGRD.VCT
    PROCEDURE C2DEHOGHOR.TXTPARTIJ.LOSTFOCUS C:\HELPDESK\KROON\C2DEHOGHOR.SCT
    PROCEDURE C2PKPTY.INIT C:\HELPDESK\VMP2005\XLIB\XXFWPICK.VCT
    XXERROR.FXP
    PROCEDURE LOGERROR XXERROR.FXP
    (C2PKPTY.INIT)

Commentaar van de gebruiker over de omstandigheden voorafgaand aan de fout:
============================================================
    Deze fout treedt op wanneer je een niet bestaand partijnummer handmatig (niet via verrekijker) invult bij een taxatieeenheid

**Comment by ejmeulenkamp** [comment]
Bij het zonder keuzelijst intypen van een onbestaand partijnummer bij een houtoogstregel, zou vanaf versie 1.06.10 de keuzelijst moeten verschijnen, en geen foutmelding. Kun je dit nog een keer testen?
