### ISSUE TITLE
activateSelectType('point') werkt niet

### ISSUE THREAD

**Issue by ejmeulenkamp** [IDgis/CRS2#88]
Hoi Linda,
Het lijkt er op dat activateSelectType niet werkt. Ik heb het zowel vanuit CRS2 als vanuit IE geprobeerd. Ook met 'graphic' i.p.v. 'point' gebeurt er niks. Volgens mij zou bij 'point' de knop 'Selecteer met punt' grijs moeten worden en bij 'graphic' de knop 'Selecteer met vlak'.

**Comment by LindaVels** [comment]
Dit is in de huidige versie nog niet geïmplementeerd

**Comment by LindaVels** [comment]
In de versie (print without red-lining) zou dit wel moeten werken.
@ejmeulenkamp Heb je dit gebruikt/getest?

**Comment by ejmeulenkamp** [comment]
Ja, dit heb ik getest en het werkt volgens mij zoals het bedoeld is.
