### ISSUE TITLE
projecten, subsidies, afspraak toevoegen, toevoegen xxx

### ISSUE THREAD

**Issue by LimburgsLandschapHarry** [IDgis/CRS2#89]
bij toevoegen relatie, contract, beheersubsidie, projecten of transacties volgt de bijgevoegde niet fatale fout.
![capture](https://cloud.githubusercontent.com/assets/10415606/6060381/a3f0a97e-ad3c-11e4-85c6-4fb4b6fab273.JPG)

**Comment by LimburgsLandschapHarry** [comment]
krijg nu wel wat toegevoegd. WErkt dus.
Bij aktiepunten kan ik wel toevoegen, maar als ik dan een aktiepunt wil afvinken of overslaan krijg ik een scherm waar ik niet direct op akkoord kan drukken. Eerst moet ik het vinkje een keer uit en weer aan zetten voordat ik kan bevestigen. Dat klopt dus nog niet.

**Comment by ejmeulenkamp** [comment]
Vanaf versie 1.06.12 is in het venstertje "Actiepunt raadplegen / muteren" de knop [Doorgaan] direct bedienbaar, zowel bij contracten, als bij projecten, transacties en beheersubsidies.
