### ISSUE TITLE
Nieuwe waarneming toevoegen lukt niet

### ISSUE THREAD

**Issue by HZLWannes** [IDgis/CRS2#9]
Bij opslaan geeft hij aan dat het niet kan wegens odbc/verbindingsfout met server

**Comment by ejmeulenkamp** [comment]
Er is een nieuwe versie van CRS2 geplaatst. Nu lukt het opslaan van waarnemingen wel.

**Comment by ejmeulenkamp** [comment]
Werkt het opslaan van een waarneming nu wel?
