### ISSUE TITLE
Waarnemingen, selectie datumveld

### ISSUE THREAD

**Issue by HZLWannes** [IDgis/CRS2#91]
In de module waarnemingen, tabblad lijst. Kun je selecties maken op basis van datum, met van en tot kun je afbakenen in welke periode je waarnemingen wilt selecteren. Dit is nu een scrollijst van ingevoerde datums, liever wil ik gewoon een datum kunnen invullen, het gebeurt tenslotte op basis van een echt datumveld.

**Comment by ejmeulenkamp** [comment]
Deze wens wordt nu ingebouwd volgens de uitbreidingen maart 2015.
