### ISSUE TITLE
Waarnemingen, verwijderen van selecties als groep

### ISSUE THREAD

**Issue by HZLWannes** [IDgis/CRS2#92]
In de module waarnemingen, tabblad selecties. Kun je nu alleen waarnemingen één voor één verwijderen nadat je een selectie hebt gemaakt. Het zou goed zijn om net als bij goedkeuren selecties in één keer te kunnen verwijderen. Graag wel met weet u dit heel zeker als vraag er tussen. Maar dit kan het schoonhouden van de database flink vereenvoudigen.

**Comment by ejmeulenkamp** [comment]
Deze wens wordt nu ingebouwd volgens de uitbreidingen maart 2015

**Comment by HZLWannes** [comment]
In de vorige versie van crs kon dit toch al?

**Comment by ejmeulenkamp** [comment]
Via het menu Onderhoud kun je vanaf versie 2.00.00  'Opnamen verwijderen'. In het venster Waarnemingen kun je alleen waarnemingen stuk voor stuk verwijderen omdat het de opbouw van het venster verwijderen van meerdere waarnemingen in één keer niet toestaat (technisch verhaal).
Ik hoop dat je er zo mee verder kunt?
