### ISSUE TITLE
Foutmelding bij Bewaren in CRS Transacties

### ISSUE THREAD

**Issue by willempeters** [IDgis/CRS2#93]
Hoi Evert Jan,

Het is weer gelukt om op de testversie in Rijssen te komen.
Nu krijg ik een foutmelding bij het Bewaren na een stukje ingevoerd te hebben in CRS-Transacties.

“De Transactieregel kan niet worden afgerond vanwege een ODBC/verbindingsfout met de server. Meld dit probleem a.u.b.”

Bij deze.
Als ik annuleer kan ik ook weer gewoon verder in dezelfde Transactie

Willem

**Comment by willempeters** [comment]
Opnieuw kreeg ik een zelfde foutmelding bij Bewaren nadat de Tabbladen CRS-Transacties-Financienen & Subsidies wat had ingevuld.

**Comment by willempeters** [comment]
Opnieuw kreeg ik een zelfde foutmelding bij Bewaren nadat ik het document Vrolijke Aankoop had toegevoegd. Het kan natuurlijk zijn dat hij dit document niet weet te staan??
Als ik dan op anuleren druk dan kan ik weer gewoon verder. Het is wel fijn dat we niet hoeven opstarten.

**Comment by ejmeulenkamp** [comment]
Ik heb geprobeerd om de fout opnieuw op te laten treden die je bij het bewaren van een transactie kreeg. Dat is me niet gelukt. Kun je een manier vinden waarmee ik de fout kan herhalen, zodat ik kan onderzoeken wat er fout gaat?

**Comment by ejmeulenkamp** [comment]
@willempeters Willem, kun je mij vertellen op welke manier deze fout optreedt. Het lukt mij niet om hem te herhalen. Als hij nog optreedt, dan ik hem graag oplossen voordat het vernieuwde CRS2 straks live gaat, anders lopen jullie dan vast!
