### ISSUE TITLE
Aanmaken van nieuwe Transactie start automatisch altijd bij 1. 

### ISSUE THREAD

**Issue by willempeters** [IDgis/CRS2#94]
Als ik een nieuwe test aankoop wil aanmaken staat het Transactienr veld ingevuld met 1. Omdat ik de andere blauwe velden nog niet heb ingevuld ga dat maar eerst doen. Als ik die heb ingevuld en Bewaar dan wordt het Transactienr veld pas lichtblauw en kan ik er een aankoopnr aan geven.
Dit leidt tot misverstanden en moet echt zoals het was worden. Gelijk met de start van het invullen van een nieuwe aankoop moet ik er een aankoopnummer aan kunnen geven.

**Comment by ejmeulenkamp** [comment]
Vanaf versie 1.06.12 zal het veld "Transactienummer" weer direct na een klik op de knop [Nieuwe] muteerbaar zijn.

**Comment by ejmeulenkamp** [comment]
@willempeters  Kun je bevestigen dat dit nu goed werkt?
