### ISSUE TITLE
De hele hectaren voor de komma worden bij Trasactieregel niet aangegeven

### ISSUE THREAD

**Issue by willempeters** [IDgis/CRS2#97]
Bij het vullen van de Transactieregels voeg je grondnummers toe. Toen ik een kadastraal perceel wilde koppelen, zag ik dat bij oppervlakten kleiner dan een hectaren er geen 0 voor de komma hadden staan. De bedragen groter dan één hectaren hadden wel een 1 of meer ervoor staan. Deze nul moet voor de leesbaarheid wel ervoor staan.

**Comment by ejmeulenkamp** [comment]
Vanaf versie 1.06.12 staat er in de keuzelijst, tijdens het selecteren van een kad.object, weer een '0' voor de komma, als het perceel kleiner is dan 1 hectare.
