### ISSUE TITLE
Het overzicht Bijlage bij vrijstellingsbezoek overdrachtsbelasting incorrect

### ISSUE THREAD

**Issue by willempeters** [IDgis/CRS2#98]
In het ovezichtencatalogus van CRS-Transacties-Details staan 3 overzichten. Het vrijstellingsverzoek heeft een dubbele printregel ter hoogte van Notaris staan. Er lijkt een datum doorheen te staan.
De printafdruk heeft dat ook. 
Overigens heeft de afdruk op het beeldscherm een zelfde opmaak als wanneer ik hem opvraag via Excel. Dat zou niet moeten kunnen. We hebben juist de dure excelmogelijkheid erbij gekocht om van de vaste opmaak een eigen opmaak te kunnen maken indien gewenst.

**Comment by ejmeulenkamp** [comment]
De datum wordt vanaf versie 1.06.12 correct afgedrukt.
Dit overzicht is een formulier en output van formulieren naar Excel wordt niet ondersteund. Dit is vanaf het begin altijd duidelijk aangegeven. De reden is dat er dan in Excel een heleboel tabbladen aangemaakt moet worden als je meerdere formulieren gaat exporteren. Dit duurt heel lang en is erg onoverzichtelijk.
