### ISSUE TITLE
Formulieren van Transacties in overzichten geeft ook een dubbele printregel 

### ISSUE THREAD

**Issue by willempeters** [IDgis/CRS2#99]
In de overzichtencatalogus van CRS-Transacties-Details staan in het Formulieren van Transacties ook een dubbeling ter hoogte van leverdatum. Deze is in de test-aankoop 10001 in CRS nog niet ingevuld. 
Dit formulier moet v.w.b. Brabant na deze CRS-Update nog aangepast op een aantal zaken.

**Comment by ejmeulenkamp** [comment]
Vanaf versie 1.06.12 worden de datums op het transactieformulier en op de bijlage bij het vrijstellingsverzoek van overdrachtsbelasting foutloos afgedrukt.
